package model

import (
	"database/sql"
	"time"

	"github.com/uptrace/bun"
)

type OeHdr struct {
	bun.BaseModel `bun:"table:oe_hdr"`

	OrderNo                        string          `bun:"order_no,type:varchar(8),pk"`
	CustomerId                     float64         `bun:"customer_id,type:decimal(19,0)"`
	OrderDate                      sql.NullTime    `bun:"order_date,type:datetime"`
	Ship2Name                      sql.NullString  `bun:"ship2_name,type:varchar(50)"`
	Ship2Add1                      sql.NullString  `bun:"ship2_add1,type:varchar(50)"`
	Ship2Add2                      sql.NullString  `bun:"ship2_add2,type:varchar(50)"`
	Ship2City                      sql.NullString  `bun:"ship2_city,type:varchar(50)"`
	Ship2State                     sql.NullString  `bun:"ship2_state,type:varchar(50)"`
	Ship2Zip                       sql.NullString  `bun:"ship2_zip,type:varchar(10)"`
	Ship2Country                   sql.NullString  `bun:"ship2_country,type:varchar(50)"`
	RequestedDate                  sql.NullTime    `bun:"requested_date,type:datetime"`
	PoNo                           sql.NullString  `bun:"po_no,type:varchar(50)"`
	Terms                          sql.NullString  `bun:"terms,type:varchar(2)"`
	ShipToPhone                    sql.NullString  `bun:"ship_to_phone,type:varchar(20)"`
	DeleteFlag                     string          `bun:"delete_flag,type:char"`
	Completed                      sql.NullString  `bun:"completed,type:char"`
	CompanyId                      sql.NullString  `bun:"company_id,type:varchar(8)"`
	DateCreated                    time.Time       `bun:"date_created,type:datetime"`
	DateLastModified               time.Time       `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy               string          `bun:"last_maintained_by,type:varchar(30)"`
	CodFlag                        sql.NullString  `bun:"cod_flag,type:char"`
	GrossMargin                    sql.NullFloat64 `bun:"gross_margin,type:decimal(19,9)"`
	ProjectedOrder                 sql.NullString  `bun:"projected_order,type:char"`
	PoNoAppend                     sql.NullString  `bun:"po_no_append,type:varchar(20)"`
	LocationId                     sql.NullFloat64 `bun:"location_id,type:decimal(19,0)"`
	CarrierId                      sql.NullFloat64 `bun:"carrier_id,type:decimal(19,0)"`
	AddressId                      sql.NullFloat64 `bun:"address_id,type:decimal(19,0)"`
	ContactId                      sql.NullString  `bun:"contact_id,type:varchar(16)"`
	CorpAddressId                  sql.NullFloat64 `bun:"corp_address_id,type:decimal(19,0)"`
	HandlingChargeReqFlag          sql.NullString  `bun:"handling_charge_req_flag,type:char"`
	PaymentMethod                  sql.NullString  `bun:"payment_method,type:varchar(8)"`
	FobFlag                        sql.NullString  `bun:"fob_flag,type:char"`
	Class1id                       sql.NullString  `bun:"class_1id,type:varchar(255)"`
	Class2id                       sql.NullString  `bun:"class_2id,type:varchar(255)"`
	Class3id                       sql.NullString  `bun:"class_3id,type:varchar(255)"`
	Class4id                       sql.NullString  `bun:"class_4id,type:varchar(255)"`
	Class5id                       sql.NullString  `bun:"class_5id,type:varchar(255)"`
	RmaFlag                        sql.NullString  `bun:"rma_flag,type:char"`
	Taker                          sql.NullString  `bun:"taker,type:varchar(30)"`
	JobName                        sql.NullString  `bun:"job_name,type:varchar(40)"`
	ThirdPartyBillingFlag          sql.NullString  `bun:"third_party_billing_flag,type:char"`
	Approved                       sql.NullString  `bun:"approved,type:char"`
	SourceLocationId               sql.NullFloat64 `bun:"source_location_id,type:decimal(19,0)"`
	PackingBasis                   sql.NullString  `bun:"packing_basis,type:varchar(16)"`
	DeliveryInstructions           sql.NullString  `bun:"delivery_instructions,type:varchar(255)"`
	PickTicketType                 sql.NullString  `bun:"pick_ticket_type,type:varchar(2)"`
	RequestedDownpayment           sql.NullFloat64 `bun:"requested_downpayment,type:decimal(19,4)"`
	DownpaymentInvoiced            sql.NullString  `bun:"downpayment_invoiced,type:char"`
	CancelFlag                     sql.NullString  `bun:"cancel_flag,type:char"`
	WillCall                       sql.NullString  `bun:"will_call,type:char"`
	FrontCounter                   sql.NullString  `bun:"front_counter,type:char"`
	ValidationStatus               sql.NullString  `bun:"validation_status,type:varchar(8)"`
	OeHdrUid                       int32           `bun:"oe_hdr_uid,type:int"`
	SourceId                       sql.NullString  `bun:"source_id,type:varchar(8)"`
	SourceCodeNo                   int32           `bun:"source_code_no,type:int"`
	CreditCardHold                 sql.NullInt32   `bun:"credit_card_hold,type:int"`
	InvoiceBatchUid                int32           `bun:"invoice_batch_uid,type:int"`
	FreightCodeUid                 sql.NullInt32   `bun:"freight_code_uid,type:int"`
	FreightOut                     float64         `bun:"freight_out,type:decimal(19,4)"`
	ShippingRouteUid               sql.NullInt32   `bun:"shipping_route_uid,type:int"`
	ExcludeRebates                 string          `bun:"exclude_rebates,type:char"`
	CaptureUsageDefault            string          `bun:"capture_usage_default,type:char"`
	JobPriceHdrUid                 sql.NullInt32   `bun:"job_price_hdr_uid,type:int"`
	FrontCounterRma                string          `bun:"front_counter_rma,type:varchar"`
	Ship2EmailAddress              sql.NullString  `bun:"ship2_email_address,type:varchar(255)"`
	OrderType                      sql.NullInt32   `bun:"order_type,type:int"`
	Taxable                        sql.NullString  `bun:"taxable,type:char"`
	ProfitPercent                  float64         `bun:"profit_percent,type:decimal(19,9)"`
	OrderCostBasis                 int32           `bun:"order_cost_basis,type:int"`
	CurrencyLineUid                sql.NullInt32   `bun:"currency_line_uid,type:int"`
	InvoiceExchRateSourceCd        sql.NullInt32   `bun:"invoice_exch_rate_source_cd,type:int"`
	RmaExpirationDate              sql.NullTime    `bun:"rma_expiration_date,type:datetime"`
	CreatedBy                      sql.NullString  `bun:"created_by,type:varchar(255)"`
	InvoiceNo                      sql.NullString  `bun:"invoice_no,type:varchar(10)"`
	BillToContactId                sql.NullString  `bun:"bill_to_contact_id,type:varchar(16)"`
	TagHoldCancelDate              sql.NullTime    `bun:"tag_hold_cancel_date,type:datetime"`
	CostCenterTrackingOption       sql.NullInt32   `bun:"cost_center_tracking_option,type:int"`
	SkipProfitExceptionCheck       string          `bun:"skip_profit_exception_check,type:char"`
	ConsBackorderProcessingFlag    sql.NullString  `bun:"cons_backorder_processing_flag,type:char"`
	RestockFeePercentage           sql.NullFloat64 `bun:"restock_fee_percentage,type:decimal(19,9)"`
	DateOrderCompleted             sql.NullTime    `bun:"date_order_completed,type:datetime"`
	ValidatedViaOpenOrdersFlag     sql.NullString  `bun:"validated_via_open_orders_flag,type:char"`
	AcknowledgementDate            sql.NullTime    `bun:"acknowledgement_date,type:datetime"`
	ProductGroupCostBasis          sql.NullInt32   `bun:"product_group_cost_basis,type:int"`
	OriginalPromiseDate            sql.NullTime    `bun:"original_promise_date,type:datetime"`
	PromiseDate                    sql.NullTime    `bun:"promise_date,type:datetime"`
	RequestedShipDate              sql.NullTime    `bun:"requested_ship_date,type:datetime"`
	ExpectedCompletionDate         sql.NullTime    `bun:"expected_completion_date,type:datetime"`
	JobControlFlag                 sql.NullString  `bun:"job_control_flag,type:char"`
	ApplyBuilderAllowanceFlag      string          `bun:"apply_builder_allowance_flag,type:char"`
	MerchandiseCreditFlag          string          `bun:"merchandise_credit_flag,type:char"`
	ReqPymtUponReleaseFlag         string          `bun:"req_pymt_upon_release_flag,type:char"`
	PmDate                         sql.NullTime    `bun:"pm_date,type:datetime"`
	DownpaymentPercentage          sql.NullFloat64 `bun:"downpayment_percentage,type:decimal(19,2)"`
	PrepaidInvoiceFlag             sql.NullString  `bun:"prepaid_invoice_flag,type:char"`
	LandedCostIncludedCd           sql.NullInt32   `bun:"landed_cost_included_cd,type:int"`
	ExportedFlag                   sql.NullString  `bun:"exported_flag,type:char"`
	WebReferenceNo                 sql.NullString  `bun:"web_reference_no,type:varchar(255)"`
	UpsCode                        sql.NullString  `bun:"ups_code,type:varchar(40)"`
	DefaultPricingCd               sql.NullInt32   `bun:"default_pricing_cd,type:int"`
	FreightChargeByMileHdrUid      sql.NullInt32   `bun:"freight_charge_by_mile_hdr_uid,type:int"`
	FreightMileageAmt              sql.NullFloat64 `bun:"freight_mileage_amt,type:decimal(19,2)"`
	SupplierOrderNo                sql.NullString  `bun:"supplier_order_no,type:varchar(255)"`
	SupplierReleaseNo              sql.NullString  `bun:"supplier_release_no,type:varchar(255)"`
	RoutedEtaDate                  sql.NullTime    `bun:"routed_eta_date,type:datetime"`
	RouteOverrideDate              sql.NullTime    `bun:"route_override_date,type:datetime"`
	ExpediteDate                   sql.NullTime    `bun:"expedite_date,type:datetime"`
	OrderOpenStartDate             sql.NullTime    `bun:"order_open_start_date,type:datetime"`
	EnvironmentalFeeFlag           sql.NullString  `bun:"environmental_fee_flag,type:char"`
	AdminFeeFlag                   sql.NullString  `bun:"admin_fee_flag,type:char"`
	PromiseDateExtendedDesc        sql.NullString  `bun:"promise_date_extended_desc,type:varchar(8000)"`
	PromiseDateEditedDate          sql.NullTime    `bun:"promise_date_edited_date,type:datetime"`
	OrderDiscType                  sql.NullInt32   `bun:"order_disc_type,type:int"`
	OrderDiscFactor                sql.NullFloat64 `bun:"order_disc_factor,type:decimal(19,9)"`
	OrderAckPrintedFlag            sql.NullString  `bun:"order_ack_printed_flag,type:char"`
	PackingListSentFlag            sql.NullInt32   `bun:"packing_list_sent_flag,type:int"`
	RmaDeliveryListStatus          sql.NullInt32   `bun:"rma_delivery_list_status,type:int"`
	StrategicLibraryUid            sql.NullInt32   `bun:"strategic_library_uid,type:int"`
	StrategicLibraryOriginalUid    sql.NullInt32   `bun:"strategic_library_original_uid,type:int"`
	SendPartialOrderFlag           sql.NullString  `bun:"send_partial_order_flag,type:char"`
	SupplierStatus                 sql.NullString  `bun:"supplier_status,type:char"`
	OrderPriorityUid               sql.NullInt32   `bun:"order_priority_uid,type:int"`
	B2bUpsFreightAmount            sql.NullFloat64 `bun:"b2b_ups_freight_amount,type:decimal(19,9)"`
	UserDefinedDate                sql.NullTime    `bun:"user_defined_date,type:datetime"`
	BlindAddressingFlag            sql.NullString  `bun:"blind_addressing_flag,type:char"`
	ReplaceCompanyNameFlag         sql.NullString  `bun:"replace_company_name_flag,type:char"`
	UseVendorItemTermsFlag         sql.NullString  `bun:"use_vendor_item_terms_flag,type:char"`
	FirstPackingListNo             sql.NullFloat64 `bun:"first_packing_list_no,type:decimal(19,0)"`
	SalesMarketGroupUid            sql.NullInt32   `bun:"sales_market_group_uid,type:int"`
	ShipConfirmedFlag              sql.NullString  `bun:"ship_confirmed_flag,type:char"`
	PriceConfirmedFlag             sql.NullString  `bun:"price_confirmed_flag,type:char"`
	QuotedFreightOut               sql.NullFloat64 `bun:"quoted_freight_out,type:decimal(19,9)"`
	GeocomAppend                   sql.NullInt32   `bun:"geocom_append,type:int"`
	ApplyFuelSurchargeFlag         sql.NullString  `bun:"apply_fuel_surcharge_flag,type:char"`
	OverrideFreightCodeFlag        sql.NullString  `bun:"override_freight_code_flag,type:char"`
	ServiceOrderPriorityUid        sql.NullInt32   `bun:"service_order_priority_uid,type:int"`
	ExcludeFromCreditLimitFlag     sql.NullString  `bun:"exclude_from_credit_limit_flag,type:char"`
	PackingListFilename            sql.NullString  `bun:"packing_list_filename,type:char"`
	OverrideMinOrderChargeFlag     sql.NullString  `bun:"override_min_order_charge_flag,type:char"`
	PlacedByName                   sql.NullString  `bun:"placed_by_name,type:varchar(255)"`
	ApprovedForArFlag              sql.NullString  `bun:"approved_for_ar_flag,type:char"`
	SecondRouteOverrideDate        sql.NullTime    `bun:"second_route_override_date,type:datetime"`
	Subject                        sql.NullString  `bun:"subject,type:varchar(255)"`
	ServicePlanUid                 sql.NullInt32   `bun:"service_plan_uid,type:int"`
	CentralFaxNumber               sql.NullString  `bun:"central_fax_number,type:varchar(20)"`
	Url                            sql.NullString  `bun:"url,type:varchar(255)"`
	OriginalPackingBasis           sql.NullString  `bun:"original_packing_basis,type:varchar(16)"`
	FreightOutEditedFlag           sql.NullString  `bun:"freight_out_edited_flag,type:char"`
	OverrideContactEmailFlag       sql.NullString  `bun:"override_contact_email_flag,type:char"`
	OverrideEmailAddress           sql.NullString  `bun:"override_email_address,type:varchar(255)"`
	PrintPricesOnPackinglist       sql.NullString  `bun:"print_prices_on_packinglist,type:char"`
	ImportSource                   sql.NullString  `bun:"import_source,type:varchar(255)"`
	QuoteLockedFlag                sql.NullString  `bun:"quote_locked_flag,type:char"`
	WebShopperId                   sql.NullInt32   `bun:"web_shopper_id,type:int"`
	WebShopperEmail                sql.NullString  `bun:"web_shopper_email,type:varchar(255)"`
	RecalcScheduledDsPrice         sql.NullString  `bun:"recalc_scheduled_ds_price,type:char"`
	OrderTypeCust                  sql.NullString  `bun:"order_type_cust,type:varchar(255)"`
	EngineerId                     sql.NullString  `bun:"engineer_id,type:varchar(255)"`
	CarrierContractHdrUid          sql.NullInt32   `bun:"carrier_contract_hdr_uid,type:int"`
	OrderAckPrintPricesFlag        sql.NullString  `bun:"order_ack_print_prices_flag,type:char"`
	FreightOutEstimate             sql.NullFloat64 `bun:"freight_out_estimate,type:decimal(19,9)"`
	FreightChargeEstimate          sql.NullFloat64 `bun:"freight_charge_estimate,type:decimal(19,9)"`
	DocumentCaptureDate            sql.NullTime    `bun:"document_capture_date,type:datetime"`
	LimitMaxShipmentsPerOrder      sql.NullFloat64 `bun:"limit_max_shipments_per_order,type:decimal(19,4)"`
	ReasonCreditMemoCodeUid        sql.NullInt32   `bun:"reason_credit_memo_code_uid,type:int"`
	SourceCreditMemoCodeUid        sql.NullInt32   `bun:"source_credit_memo_code_uid,type:int"`
	NetBillingFlag                 string          `bun:"net_billing_flag,type:char"`
	NetBillingEdited               string          `bun:"net_billing_edited,type:char"`
	SchedOrderDiscFlag             sql.NullString  `bun:"sched_order_disc_flag,type:char"`
	WillCallDiscFlag               sql.NullString  `bun:"will_call_disc_flag,type:char"`
	SingleOrderDiscFlag            sql.NullString  `bun:"single_order_disc_flag,type:char"`
	VolumeDiscFlag                 sql.NullString  `bun:"volume_disc_flag,type:char"`
	ServiceInvoiceNo               sql.NullString  `bun:"service_invoice_no,type:varchar(10)"`
	Ship2Add3                      sql.NullString  `bun:"ship2_add3,type:varchar(50)"`
	BillToId                       sql.NullFloat64 `bun:"bill_to_id,type:decimal(19,0)"`
	ElectronicOrderFlag            sql.NullString  `bun:"electronic_order_flag,type:char"`
	CodWithoutRemittanceFlag       sql.NullString  `bun:"cod_without_remittance_flag,type:char"`
	SoTotalPartsPriceOnInvoice     sql.NullString  `bun:"so_total_parts_price_on_invoice,type:char"`
	SoTotalLaborPriceOnInvoice     sql.NullString  `bun:"so_total_labor_price_on_invoice,type:char"`
	InquiryFlag                    sql.NullString  `bun:"inquiry_flag,type:char"`
	HoldInvoiceFlag                string          `bun:"hold_invoice_flag,type:char"`
	DoNotExportToPtsFlag           sql.NullString  `bun:"do_not_export_to_pts_flag,type:char"`
	GenericDescOnPackinglistFlag   sql.NullString  `bun:"generic_desc_on_packinglist_flag,type:char"`
	GenericDescOnInvoiceAckFlag    sql.NullString  `bun:"generic_desc_on_invoice_ack_flag,type:char"`
	WillCallNotificationFlag       sql.NullString  `bun:"will_call_notification_flag,type:char"`
	PrebillingDate                 sql.NullTime    `bun:"prebilling_date,type:datetime"`
	BlindShipFlag                  sql.NullString  `bun:"blind_ship_flag,type:char"`
	ArchitectId                    sql.NullFloat64 `bun:"architect_id,type:decimal(19,0)"`
	BuilderId                      sql.NullFloat64 `bun:"builder_id,type:decimal(19,0)"`
	ContractorId                   sql.NullFloat64 `bun:"contractor_id,type:decimal(19,0)"`
	DesignerId                     sql.NullFloat64 `bun:"designer_id,type:decimal(19,0)"`
	HomeownerId                    sql.NullFloat64 `bun:"homeowner_id,type:decimal(19,0)"`
	QuoteType                      sql.NullInt32   `bun:"quote_type,type:int"`
	PtsLabelPrintFlag              sql.NullString  `bun:"pts_label_print_flag,type:char"`
	DiscountItemId                 sql.NullString  `bun:"discount_item_id,type:varchar(255)"`
	CustomerDiscPct                sql.NullFloat64 `bun:"customer_disc_pct,type:decimal(19,9)"`
	ConsolidatePerOrderFlag        sql.NullString  `bun:"consolidate_per_order_flag,type:char"`
	DfltUpsShipViaCode             sql.NullInt32   `bun:"dflt_ups_ship_via_code,type:int"`
	DfltFedexServiceTypeUid        sql.NullInt32   `bun:"dflt_fedex_service_type_uid,type:int"`
	InvoiceOnlyFlag                sql.NullString  `bun:"invoice_only_flag,type:char"`
	Ship2Latitude                  sql.NullString  `bun:"ship2_latitude,type:varchar(20)"`
	Ship2Longitude                 sql.NullString  `bun:"ship2_longitude,type:varchar(20)"`
	BypassHandlingChargeFlag       sql.NullString  `bun:"bypass_handling_charge_flag,type:char"`
	FreightChargeUid               sql.NullInt32   `bun:"freight_charge_uid,type:int"`
	LumpSumBillingFlag             sql.NullString  `bun:"lump_sum_billing_flag,type:char"`
	FieldDestroyFlag               sql.NullString  `bun:"field_destroy_flag,type:char"`
	WarrantyReturnOrderFlag        sql.NullString  `bun:"warranty_return_order_flag,type:char"`
	AllowAutoApplyOrigInvFlag      sql.NullString  `bun:"allow_auto_apply_orig_inv_flag,type:char"`
	DaysEarly                      sql.NullInt32   `bun:"days_early,type:int"`
	TransitDays                    sql.NullInt32   `bun:"transit_days,type:int"`
	DisplayInvoiceExchRateSourceCd sql.NullInt32   `bun:"display_invoice_exch_rate_source_cd,type:int"`
	NatlAcctCustomerUid            sql.NullInt32   `bun:"natl_acct_customer_uid,type:int"`
	SlaRequestedDate               sql.NullTime    `bun:"sla_requested_date,type:datetime"`
	EdiManualOverrideFlag          sql.NullString  `bun:"edi_manual_override_flag,type:char"`
	RevisioningEnabledFlag         sql.NullString  `bun:"revisioning_enabled_flag,type:char"`
	QuoteSubmittedFlag             sql.NullString  `bun:"quote_submitted_flag,type:char"`
	WarrantyRmaFlag                sql.NullString  `bun:"warranty_rma_flag,type:char"`
	GenerateProFormaInvoicesFlag   sql.NullString  `bun:"generate_pro_forma_invoices_flag,type:char"`
	AsbDeliveryMethodUid           sql.NullInt32   `bun:"asb_delivery_method_uid,type:int"`
	DeliveryContactId              sql.NullString  `bun:"delivery_contact_id,type:varchar(16)"`
	AdvancedBillingFlag            sql.NullString  `bun:"advanced_billing_flag,type:char"`
	AdvancedBillingPrintFlag       sql.NullString  `bun:"advanced_billing_print_flag,type:char"`
	EwingJobNo                     sql.NullInt32   `bun:"ewing_job_no,type:int"`
	PricingLocId                   sql.NullInt32   `bun:"pricing_loc_id,type:int"`
	RentalTransactionNo            sql.NullString  `bun:"rental_transaction_no,type:varchar(255)"`
	RentalQuoteNo                  sql.NullString  `bun:"rental_quote_no,type:varchar(255)"`
	RentalTransactionStatusCd      sql.NullInt32   `bun:"rental_transaction_status_cd,type:int"`
	RentalReturnDate               sql.NullTime    `bun:"rental_return_date,type:datetime"`
	MafSurchargeOverride           string          `bun:"maf_surcharge_override,type:varchar"`
	MafSurchargeReasonCode         sql.NullString  `bun:"maf_surcharge_reason_code,type:varchar(255)"`
	OracleCarrierId                sql.NullFloat64 `bun:"oracle_carrier_id,type:decimal(19,9)"`
	RentalBillingFlag              sql.NullString  `bun:"rental_billing_flag,type:char"`
	InsideSales                    sql.NullString  `bun:"inside_sales,type:varchar(30)"`
	Ship2Url                       sql.NullString  `bun:"ship2_url,type:varchar(255)"`
	GlDimensionProjectNo           sql.NullString  `bun:"gl_dimension_project_no,type:varchar(255)"`
	RentalStartDate                sql.NullTime    `bun:"rental_start_date,type:datetime"`
	PickupContactId                sql.NullString  `bun:"pickup_contact_id,type:varchar(16)"`
	UnitType                       sql.NullString  `bun:"unit_type,type:varchar(255)"`
	UnitNumber                     sql.NullString  `bun:"unit_number,type:varchar(255)"`
	CpqQuoteNo                     sql.NullInt32   `bun:"cpq_quote_no,type:int"`

	OeLineItems []OeLine `bun:"rel:has-many,join:order_no=order_no"`
	Contact     Contact  `bun:"rel:has-one,join:contact_id=id"`
}
