package model

import (
	"database/sql"
	"time"

	"github.com/uptrace/bun"
)

type OeLine struct {
	bun.BaseModel `bun:"table:oe_line"`

	OrderNo                      string          `bun:"order_no,type:varchar(8),pk"`
	UnitPrice                    sql.NullFloat64 `bun:"unit_price,type:decimal(19,9)"`
	QtyOrdered                   sql.NullFloat64 `bun:"qty_ordered,type:decimal(19,9)"`
	QtyPerAssembly               float64         `bun:"qty_per_assembly,type:decimal(19,9)"`
	CompanyNo                    string          `bun:"company_no,type:varchar(8)"`
	DeleteFlag                   string          `bun:"delete_flag,type:char"`
	ManualPriceOveride           sql.NullString  `bun:"manual_price_overide,type:char"`
	DateCreated                  time.Time       `bun:"date_created,type:datetime"`
	DateLastModified             time.Time       `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy             string          `bun:"last_maintained_by,type:varchar(30)"`
	ExtendedPrice                sql.NullFloat64 `bun:"extended_price,type:decimal(19,4)"`
	SalesTax                     sql.NullFloat64 `bun:"sales_tax,type:decimal(19,4)"`
	LineNo                       float64         `bun:"line_no,type:decimal(19,0),pk"`
	Complete                     sql.NullString  `bun:"complete,type:char"`
	UnitOfMeasure                sql.NullString  `bun:"unit_of_measure,type:varchar(8)"`
	BaseUtPrice                  sql.NullFloat64 `bun:"base_ut_price,type:decimal(19,9)"`
	CalcType                     sql.NullString  `bun:"calc_type,type:varchar(10)"`
	CalcValue                    sql.NullFloat64 `bun:"calc_value,type:decimal(19,4)"`
	Combinable                   sql.NullString  `bun:"combinable,type:char"`
	Disposition                  sql.NullString  `bun:"disposition,type:char"`
	QtyAllocated                 sql.NullFloat64 `bun:"qty_allocated,type:decimal(19,9)"`
	QtyOnPickTickets             sql.NullFloat64 `bun:"qty_on_pick_tickets,type:decimal(19,9)"`
	QtyInvoiced                  sql.NullFloat64 `bun:"qty_invoiced,type:decimal(19,9)"`
	ExpediteDate                 sql.NullTime    `bun:"expedite_date,type:datetime"`
	RequiredDate                 sql.NullTime    `bun:"required_date,type:datetime"`
	SourceLocId                  sql.NullFloat64 `bun:"source_loc_id,type:decimal(19,0)"`
	ShipLocId                    sql.NullFloat64 `bun:"ship_loc_id,type:decimal(19,0)"`
	SupplierId                   sql.NullFloat64 `bun:"supplier_id,type:decimal(19,0)"`
	ProductGroupId               sql.NullString  `bun:"product_group_id,type:varchar(8)"`
	Assembly                     sql.NullString  `bun:"assembly,type:char"`
	Scheduled                    sql.NullString  `bun:"scheduled,type:char"`
	LotBill                      string          `bun:"lot_bill,type:char"`
	ExtendedDesc                 sql.NullString  `bun:"extended_desc,type:varchar(255)"`
	UnitSize                     float64         `bun:"unit_size,type:decimal(19,4)"`
	UnitQuantity                 float64         `bun:"unit_quantity,type:decimal(19,9)"`
	NextBreak                    sql.NullFloat64 `bun:"next_break,type:decimal(19,9)"`
	NextUtPrice                  sql.NullFloat64 `bun:"next_ut_price,type:decimal(19,9)"`
	CustomerPartNumber           string          `bun:"customer_part_number,type:varchar(40)"`
	TaxItem                      sql.NullString  `bun:"tax_item,type:char"`
	OkToInterchange              sql.NullString  `bun:"ok_to_interchange,type:char"`
	OtherCharge                  string          `bun:"other_charge,type:char"`
	SalesCost                    sql.NullFloat64 `bun:"sales_cost,type:decimal(19,9)"`
	CommissionCost               sql.NullFloat64 `bun:"commission_cost,type:decimal(19,9)"`
	RequestedDownpayment         sql.NullFloat64 `bun:"requested_downpayment,type:decimal(19,9)"`
	DownpaymentDate              sql.NullTime    `bun:"downpayment_date,type:datetime"`
	WillCall                     sql.NullString  `bun:"will_call,type:char"`
	OtherCost                    sql.NullFloat64 `bun:"other_cost,type:decimal(19,9)"`
	DownpaymentRemaining         sql.NullFloat64 `bun:"downpayment_remaining,type:decimal(19,9)"`
	CancelFlag                   sql.NullString  `bun:"cancel_flag,type:char"`
	CommissionCostEdited         sql.NullString  `bun:"commission_cost_edited,type:char"`
	OtherCostEdited              sql.NullString  `bun:"other_cost_edited,type:char"`
	PoCost                       sql.NullFloat64 `bun:"po_cost,type:decimal(19,9)"`
	QtyCanceled                  sql.NullFloat64 `bun:"qty_canceled,type:decimal(19,9)"`
	PricingUnit                  sql.NullString  `bun:"pricing_unit,type:varchar(8)"`
	PricingUnitSize              sql.NullFloat64 `bun:"pricing_unit_size,type:decimal(19,4)"`
	QtyStaged                    sql.NullFloat64 `bun:"qty_staged,type:decimal(19,9)"`
	ItemSource                   int16           `bun:"item_source,type:smallint"`
	OeHdrUid                     int32           `bun:"oe_hdr_uid,type:int"`
	ParentOeLineUid              int32           `bun:"parent_oe_line_uid,type:int"`
	OeLineUid                    int32           `bun:"oe_line_uid,type:int"`
	PricePageUid                 sql.NullInt32   `bun:"price_page_uid,type:int"`
	PricingOption                int32           `bun:"pricing_option,type:int"`
	DetailType                   int32           `bun:"detail_type,type:int"`
	UserLineNo                   sql.NullString  `bun:"user_line_no,type:varchar(25)"`
	ItemTermsDiscountPct         float64         `bun:"item_terms_discount_pct,type:decimal(19,2)"`
	DefaultInOe                  sql.NullString  `bun:"default_in_oe,type:char"`
	InvMastUid                   int32           `bun:"inv_mast_uid,type:int"`
	FreightIn                    float64         `bun:"freight_in,type:decimal(19,4)"`
	PeerOeLineUid                int32           `bun:"peer_oe_line_uid,type:int"`
	PeerType                     int32           `bun:"peer_type,type:int"`
	SubstituteItem               sql.NullString  `bun:"substitute_item,type:char"`
	AllocateUsageToOriginalItem  sql.NullString  `bun:"allocate_usage_to_original_item,type:char"`
	OrderCostEdited              string          `bun:"order_cost_edited,type:char"`
	CaptureUsage                 string          `bun:"capture_usage,type:char"`
	PurchaseClassId              sql.NullString  `bun:"purchase_class_id,type:varchar(8)"`
	PickDate                     sql.NullTime    `bun:"pick_date,type:datetime"`
	ShippingRouteUid             sql.NullInt32   `bun:"shipping_route_uid,type:int"`
	InvXrefUid                   sql.NullInt32   `bun:"inv_xref_uid,type:int"`
	HoseQtyNeeded                float64         `bun:"hose_qty_needed,type:decimal(19,9)"`
	CreatedBy                    sql.NullString  `bun:"created_by,type:varchar(255)"`
	OriginalQtyOrdered           sql.NullFloat64 `bun:"original_qty_ordered,type:decimal(19,9)"`
	TagHoldClassUid              sql.NullInt32   `bun:"tag_hold_class_uid,type:int"`
	CostCenter                   sql.NullString  `bun:"cost_center,type:varchar(255)"`
	DispositionEditedFlag        sql.NullString  `bun:"disposition_edited_flag,type:char"`
	JobPriceHdrUid               sql.NullInt32   `bun:"job_price_hdr_uid,type:int"`
	DeaRestrictionFailed         sql.NullString  `bun:"dea_restriction_failed,type:char"`
	RestockFeePercentage         sql.NullFloat64 `bun:"restock_fee_percentage,type:decimal(19,9)"`
	CustomerConfiguredPrice      sql.NullFloat64 `bun:"customer_configured_price,type:decimal(19,9)"`
	CustomerPickedFlag           sql.NullString  `bun:"customer_picked_flag,type:char"`
	JobPriceLineUid              sql.NullInt32   `bun:"job_price_line_uid,type:int"`
	CustPoNo                     sql.NullString  `bun:"cust_po_no,type:varchar(255)"`
	JobPriceBinUid               sql.NullInt32   `bun:"job_price_bin_uid,type:int"`
	UseContractCost              string          `bun:"use_contract_cost,type:char"`
	CostPricePageUid             sql.NullInt32   `bun:"cost_price_page_uid,type:int"`
	PackageTypeUid               sql.NullInt32   `bun:"package_type_uid,type:int"`
	TagPackageQtyPer             sql.NullFloat64 `bun:"tag_package_qty_per,type:decimal(19,0)"`
	FreightCodeUid               sql.NullInt32   `bun:"freight_code_uid,type:int"`
	AcknowledgementDate          sql.NullTime    `bun:"acknowledgement_date,type:datetime"`
	UsedSpecificCostFlag         string          `bun:"used_specific_cost_flag,type:char"`
	OperationUid                 sql.NullInt32   `bun:"operation_uid,type:int"`
	ServiceLaborUid              sql.NullInt32   `bun:"service_labor_uid,type:int"`
	QuoteOutcomeCd               sql.NullInt32   `bun:"quote_outcome_cd,type:int"`
	ItemCommissionClassId        sql.NullString  `bun:"item_commission_class_id,type:varchar(8)"`
	FromAltPrevRequestsFlag      sql.NullString  `bun:"from_alt_prev_requests_flag,type:char"`
	UdCost                       sql.NullFloat64 `bun:"ud_cost,type:decimal(19,9)"`
	TankName                     sql.NullString  `bun:"tank_name,type:varchar(255)"`
	ItemBillToId                 sql.NullFloat64 `bun:"item_bill_to_id,type:decimal(19,0)"`
	BuybackNo                    sql.NullString  `bun:"buyback_no,type:varchar(255)"`
	RoutingStatusFlag            sql.NullString  `bun:"routing_status_flag,type:char"`
	SplitFlag                    sql.NullString  `bun:"split_flag,type:char"`
	AdditionalDescription        sql.NullString  `bun:"additional_description,type:varchar(255)"`
	BillHoldFlag                 sql.NullString  `bun:"bill_hold_flag,type:char"`
	CorePrice                    sql.NullFloat64 `bun:"core_price,type:decimal(19,9)"`
	Clock                        sql.NullString  `bun:"clock,type:varchar(255)"`
	Cell                         sql.NullString  `bun:"cell,type:varchar(255)"`
	EnvironmentalFee             sql.NullFloat64 `bun:"environmental_fee,type:decimal(19,4)"`
	AdminFee                     sql.NullFloat64 `bun:"admin_fee,type:decimal(19,4)"`
	ExtDiscAmt                   sql.NullFloat64 `bun:"ext_disc_amt,type:decimal(19,9)"`
	SystemCalcUnitPrice          sql.NullFloat64 `bun:"system_calc_unit_price,type:decimal(19,9)"`
	Buyer                        sql.NullString  `bun:"buyer,type:varchar(255)"`
	Recipient                    sql.NullString  `bun:"recipient,type:varchar(255)"`
	StrategicUnitPrice           sql.NullFloat64 `bun:"strategic_unit_price,type:decimal(19,9)"`
	StrategicPricePageUid        sql.NullInt32   `bun:"strategic_price_page_uid,type:int"`
	VerifiedFlag                 sql.NullString  `bun:"verified_flag,type:char"`
	VerifiedCode                 sql.NullString  `bun:"verified_code,type:varchar(255)"`
	CoreStatusCd                 sql.NullInt32   `bun:"core_status_cd,type:int"`
	UsedStrategicPricingFlag     sql.NullString  `bun:"used_strategic_pricing_flag,type:char"`
	LoanUid                      sql.NullInt32   `bun:"loan_uid,type:int"`
	LoanItemUid                  sql.NullInt32   `bun:"loan_item_uid,type:int"`
	OriginalUnitPrice            sql.NullFloat64 `bun:"original_unit_price,type:decimal(19,9)"`
	OriginalFreightIn            sql.NullFloat64 `bun:"original_freight_in,type:decimal(19,9)"`
	StrategicListCostValue       sql.NullFloat64 `bun:"strategic_list_cost_value,type:decimal(19,9)"`
	StrategicListCostCd          sql.NullInt32   `bun:"strategic_list_cost_cd,type:int"`
	SalesMarketGroupUid          sql.NullInt32   `bun:"sales_market_group_uid,type:int"`
	SpecialItemIndicator         sql.NullInt32   `bun:"special_item_indicator,type:int"`
	AwardedDate                  sql.NullTime    `bun:"awarded_date,type:datetime"`
	SampleFlag                   sql.NullString  `bun:"sample_flag,type:char"`
	RoutingAllocationChange      sql.NullFloat64 `bun:"routing_allocation_change,type:decimal(19,9)"`
	Price1                       sql.NullFloat64 `bun:"price1,type:decimal(19,9)"`
	UnitPickFee                  sql.NullFloat64 `bun:"unit_pick_fee,type:decimal(19,9)"`
	OeLineAltCode                sql.NullString  `bun:"oe_line_alt_code,type:varchar(40)"`
	RetailPrice                  sql.NullFloat64 `bun:"retail_price,type:decimal(19,9)"`
	QuotePriceOeLineUid          sql.NullInt32   `bun:"quote_price_oe_line_uid,type:int"`
	CoreItemCost                 sql.NullFloat64 `bun:"core_item_cost,type:decimal(19,9)"`
	ItemCommitmentDetailUid      sql.NullInt32   `bun:"item_commitment_detail_uid,type:int"`
	SuppressCustomCost           sql.NullString  `bun:"suppress_custom_cost,type:char"`
	BuyListApprovalInitial       sql.NullString  `bun:"buy_list_approval_initial,type:varchar(3)"`
	GeocomForcedSendFlag         sql.NullString  `bun:"geocom_forced_send_flag,type:char"`
	GeocomForcedQuantity         sql.NullFloat64 `bun:"geocom_forced_quantity,type:decimal(19,0)"`
	SuppressPickTicketIndicator  sql.NullInt32   `bun:"suppress_pick_ticket_indicator,type:int"`
	BeltingWidth                 sql.NullFloat64 `bun:"belting_width,type:decimal(19,9)"`
	BeltingLength                sql.NullFloat64 `bun:"belting_length,type:decimal(19,9)"`
	BeltingNumCuts               sql.NullInt32   `bun:"belting_num_cuts,type:int"`
	CarrierId                    sql.NullFloat64 `bun:"carrier_id,type:decimal(19,0)"`
	FreightInEditedFlag          sql.NullString  `bun:"freight_in_edited_flag,type:char"`
	SalesDiscountGroupId         sql.NullString  `bun:"sales_discount_group_id,type:varchar(8)"`
	PriceFamilyUid               sql.NullInt32   `bun:"price_family_uid,type:int"`
	CostCarrierContractLineUid   sql.NullInt32   `bun:"cost_carrier_contract_line_uid,type:int"`
	PriceCarrierContractLineUid  sql.NullInt32   `bun:"price_carrier_contract_line_uid,type:int"`
	PumpOffFlag                  sql.NullString  `bun:"pump_off_flag,type:char"`
	CostCarrierContractZLineUid  sql.NullInt32   `bun:"cost_carrier_contract_z_line_uid,type:int"`
	TargetPrice                  sql.NullFloat64 `bun:"target_price,type:decimal(19,9)"`
	Edi830LastShipmentNo         sql.NullString  `bun:"edi830_last_shipment_no,type:varchar(255)"`
	Edi830LastReceiveQty         sql.NullFloat64 `bun:"edi830_last_receive_qty,type:decimal(19,9)"`
	Edi830LastReceiveDate        sql.NullTime    `bun:"edi830_last_receive_date,type:datetime"`
	FaspacYtdQtyInvoiced         sql.NullFloat64 `bun:"faspac_ytd_qty_invoiced,type:decimal(19,9)"`
	CompetitorUid                sql.NullInt32   `bun:"competitor_uid,type:int"`
	PriceAdjNote                 sql.NullString  `bun:"price_adj_note,type:varchar(255)"`
	ImportedPrice                sql.NullFloat64 `bun:"imported_price,type:decimal(19,9)"`
	GlCode                       sql.NullString  `bun:"gl_code,type:varchar(255)"`
	RfqIndicatorFlag             sql.NullString  `bun:"rfq_indicator_flag,type:char"`
	BuyGetRewardsFlag            sql.NullString  `bun:"buy_get_rewards_flag,type:char"`
	BuyGetXRewardsProgramUid     sql.NullInt32   `bun:"buy_get_x_rewards_program_uid,type:int"`
	CarrierRebateCost            sql.NullFloat64 `bun:"carrier_rebate_cost,type:decimal(19,9)"`
	ExtendedDescLocation         sql.NullString  `bun:"extended_desc_location,type:varchar(255)"`
	ExtendedDescCustomer         sql.NullString  `bun:"extended_desc_customer,type:varchar(255)"`
	LineDiscount                 sql.NullFloat64 `bun:"line_discount,type:decimal(19,9)"`
	LineDiscountDescription      sql.NullString  `bun:"line_discount_description,type:varchar(255)"`
	UnitDistributorNet           sql.NullFloat64 `bun:"unit_distributor_net,type:decimal(19,9)"`
	ExtendedDistributorNet       sql.NullFloat64 `bun:"extended_distributor_net,type:decimal(19,4)"`
	EcoFeeAmount                 sql.NullFloat64 `bun:"eco_fee_amount,type:decimal(19,9)"`
	BypassProdOrderProcessing    sql.NullString  `bun:"bypass_prod_order_processing,type:char"`
	GenericCustomDescription     sql.NullString  `bun:"generic_custom_description,type:varchar(255)"`
	LineSeqNo                    sql.NullInt32   `bun:"line_seq_no,type:int"`
	OeBuyGetRewardsUid           sql.NullInt32   `bun:"oe_buy_get_rewards_uid,type:int"`
	RestrictedByAddressFlag      sql.NullString  `bun:"restricted_by_address_flag,type:char"`
	SecondaryUnitPrice           sql.NullFloat64 `bun:"secondary_unit_price,type:decimal(19,9)"`
	SecondaryExtendedPrice       sql.NullFloat64 `bun:"secondary_extended_price,type:decimal(19,9)"`
	OriginalDisposition          sql.NullString  `bun:"original_disposition,type:char"`
	SecondaryManualPriceOveride  sql.NullString  `bun:"secondary_manual_price_overide,type:char"`
	ExtendedItemFlag             sql.NullString  `bun:"extended_item_flag,type:char"`
	PrintDescOnFormsFlag         sql.NullString  `bun:"print_desc_on_forms_flag,type:char"`
	PrintPartNo                  sql.NullString  `bun:"print_part_no,type:varchar(40)"`
	CourtesyCoreReturnFlag       sql.NullString  `bun:"courtesy_core_return_flag,type:char"`
	CurrentbinUid                sql.NullInt32   `bun:"currentbin_uid,type:int"`
	QaStatus                     sql.NullString  `bun:"qa_status,type:varchar(255)"`
	ServiceItemFlag              sql.NullString  `bun:"service_item_flag,type:char"`
	PrediscountUnitPrice         sql.NullFloat64 `bun:"prediscount_unit_price,type:decimal(19,9)"`
	CustPercentageDisc           sql.NullFloat64 `bun:"cust_percentage_disc,type:decimal(19,9)"`
	OriginalQtyAllocated         sql.NullFloat64 `bun:"original_qty_allocated,type:decimal(19,9)"`
	PriceLockFlag                sql.NullString  `bun:"price_lock_flag,type:char"`
	ExtElectronicDiscAmt         sql.NullFloat64 `bun:"ext_electronic_disc_amt,type:decimal(19,9)"`
	ServiceItemId                sql.NullString  `bun:"service_item_id,type:varchar(255)"`
	PoContractNumber             sql.NullString  `bun:"po_contract_number,type:varchar(255)"`
	ExcludeFromEdi844867Flag     sql.NullString  `bun:"exclude_from_edi_844_867_flag,type:char"`
	AddToOpenPtFlag              sql.NullString  `bun:"add_to_open_pt_flag,type:char"`
	SplitToOeLineUid             sql.NullInt32   `bun:"split_to_oe_line_uid,type:int"`
	SplitFromOeLineUid           sql.NullInt32   `bun:"split_from_oe_line_uid,type:int"`
	FullRolledItemCd             sql.NullInt32   `bun:"full_rolled_item_cd,type:int"`
	RequiredTransferShipDate     sql.NullTime    `bun:"required_transfer_ship_date,type:datetime"`
	ReasonId                     sql.NullString  `bun:"reason_id,type:varchar(5)"`
	DamagedItemSerialNumber      sql.NullString  `bun:"damaged_item_serial_number,type:varchar(40)"`
	ExportParkerPrinterName      sql.NullString  `bun:"export_parker_printer_name,type:varchar(255)"`
	ExportParkerLabelCopies      sql.NullInt32   `bun:"export_parker_label_copies,type:int"`
	CreateTrackaboutLeaseFlag    sql.NullString  `bun:"create_trackabout_lease_flag,type:char"`
	JobPriceShipControlNoUid     sql.NullInt32   `bun:"job_price_ship_control_no_uid,type:int"`
	PricingMultiplierFromLot     sql.NullFloat64 `bun:"pricing_multiplier_from_lot,type:decimal(19,9)"`
	RentalFlag                   sql.NullString  `bun:"rental_flag,type:char"`
	RentalReturnQty              sql.NullFloat64 `bun:"rental_return_qty,type:decimal(19,9)"`
	RentalPrice                  sql.NullFloat64 `bun:"rental_price,type:decimal(19,9)"`
	QuoteConversionListPrice     sql.NullFloat64 `bun:"quote_conversion_list_price,type:decimal(19,9)"`
	QuotedPrice                  sql.NullFloat64 `bun:"quoted_price,type:decimal(19,9)"`
	ConversionOrderCost          sql.NullFloat64 `bun:"conversion_order_cost,type:decimal(19,9)"`
	DirectShipFreightAmount      sql.NullFloat64 `bun:"direct_ship_freight_amount,type:decimal(19,4)"`
	ReturnCylinderQuantity       sql.NullInt32   `bun:"return_cylinder_quantity,type:int"`
	LinkedChargeParentOeLineUid  sql.NullInt32   `bun:"linked_charge_parent_oe_line_uid,type:int"`
	LinkedChargeScaleQtyFlag     sql.NullString  `bun:"linked_charge_scale_qty_flag,type:char"`
	SourceQuoteOeLineUid         sql.NullInt32   `bun:"source_quote_oe_line_uid,type:int"`
	OrgValue                     sql.NullString  `bun:"org_value,type:varchar(3)"`
	RestrictedClassUid           sql.NullInt32   `bun:"restricted_class_uid,type:int"`
	LineSupplierExchangeRate     sql.NullFloat64 `bun:"line_supplier_exchange_rate,type:decimal(19,6)"`
	CpqQuoteProductId            sql.NullInt32   `bun:"cpq_quote_product_id,type:int"`
	DefaultSourceLocId           sql.NullFloat64 `bun:"default_source_loc_id,type:decimal(19,0)"`
	DirectThroughStockFlag       sql.NullString  `bun:"direct_through_stock_flag,type:char"`
	DtsReleaseQty                sql.NullFloat64 `bun:"dts_release_qty,type:decimal(19,9)"`
	CustomerSerialRequirementUid sql.NullInt32   `bun:"customer_serial_requirement_uid,type:int"`
	SalesLocationId              sql.NullFloat64 `bun:"sales_location_id,type:decimal(19,0)"`

	InvMast InvMast `bun:"rel:has-one,join:inv_mast_uid=inv_mast_uid"`
}
