apiVersion: apps/v1
kind: 'Deployment'
metadata:
  name: 'prophet-redpanda-dev'
  namespace: 'default'
  labels:
    app: 'redpanda-dev'
spec:
  template:
    metadata:
        labels:
            app: 'redpanda-dev'
    spec:
      containers:
        - name: 'broker-0'
          image: 'docker.redpanda.com/redpandadata/redpanda:v23.3.11'
          args:
            - redpanda
            - start
            - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
            - --advertise-kafka-addr internal://broker-0:9092,external://localhost:19092
            - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
            - --advertise-pandaproxy-addr internal://broker-0:8082,external://localhost:18082
            - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
            - --rpc-addr broker-0:33145
            - --advertise-rpc-addr broker-0:33145
            - --mode dev-container
            - --smp 1
            - --default-log-level=info
          ports:
            - containerPort: 18081
              hostPort: 18081
            - containerPort: 18082
            - containerPort: 19092
              hostPort: 19092
            - containerPort: 19644
        - name: 'console'
          image: 'docker.redpanda.com/redpandadata/console:v2.4.6'
          command:
            - /bin/sh
          args:
          - -c
          - 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
          env:
            - name: CONFIG_FILEPATH
              value: /tmp/config.yml
            - name: CONSOLE_CONFIG_FILE
              value: |
                kafka:
                  brokers: ["broker-0:9092"]
                  schemaRegistry:
                    enabled: true
                    urls: ["http://broker-0:8081"]
                redpanda:
                  adminApi:
                    enabled: true
                    urls: ["http://broker-0:9644"]
          ports:
            - containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - mountPath: /var/lib/redpanda/data
              name: broker-volume
      volumes:
        - name: broker-volume
          persistentVolumeClaim:
            claimName: redpanda-dev


  selector:
    matchLabels:
      app: 'redpanda-dev'
