// Code generated by mockery v2.40.1. DO NOT EDIT.

package repomocks

import (
	entities "github.com/materials-resources/s_prophet/pkg/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// FindOrderById provides a mock function with given fields: id
func (_m *OrderRepository) FindOrderById(id string) (*entities.ValidatedOrder, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindOrderById")
	}

	var r0 *entities.ValidatedOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.ValidatedOrder, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.ValidatedOrder); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ValidatedOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPickTicketByID provides a mock function with given fields: id
func (_m *OrderRepository) FindPickTicketByID(id string) (*entities.ValidatedPickTicket, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindPickTicketByID")
	}

	var r0 *entities.ValidatedPickTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.ValidatedPickTicket, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.ValidatedPickTicket); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ValidatedPickTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
