// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: warehouse/v1alpha0/warehouse.proto

package v1alpha0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WarehouseService_GetAllocatedOrdersForReceiptItem_FullMethodName = "/warehouse.v1alpha0.WarehouseService/GetAllocatedOrdersForReceiptItem"
	WarehouseService_GetReceivingReport_FullMethodName               = "/warehouse.v1alpha0.WarehouseService/GetReceivingReport"
	WarehouseService_GetPickTicket_FullMethodName                    = "/warehouse.v1alpha0.WarehouseService/GetPickTicket"
)

// WarehouseServiceClient is the client API for WarehouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseServiceClient interface {
	GetAllocatedOrdersForReceiptItem(ctx context.Context, in *GetAllocatedOrdersForReceiptItemRequest, opts ...grpc.CallOption) (*GetAllocatedOrdersForReceiptItemResponse, error)
	GetReceivingReport(ctx context.Context, in *GetReceivingReportRequest, opts ...grpc.CallOption) (*GetReceivingReportResponse, error)
	GetPickTicket(ctx context.Context, in *GetPickTicketRequest, opts ...grpc.CallOption) (*GetPickTicketResponse, error)
}

type warehouseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseServiceClient(cc grpc.ClientConnInterface) WarehouseServiceClient {
	return &warehouseServiceClient{cc}
}

func (c *warehouseServiceClient) GetAllocatedOrdersForReceiptItem(ctx context.Context, in *GetAllocatedOrdersForReceiptItemRequest, opts ...grpc.CallOption) (*GetAllocatedOrdersForReceiptItemResponse, error) {
	out := new(GetAllocatedOrdersForReceiptItemResponse)
	err := c.cc.Invoke(ctx, WarehouseService_GetAllocatedOrdersForReceiptItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) GetReceivingReport(ctx context.Context, in *GetReceivingReportRequest, opts ...grpc.CallOption) (*GetReceivingReportResponse, error) {
	out := new(GetReceivingReportResponse)
	err := c.cc.Invoke(ctx, WarehouseService_GetReceivingReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) GetPickTicket(ctx context.Context, in *GetPickTicketRequest, opts ...grpc.CallOption) (*GetPickTicketResponse, error) {
	out := new(GetPickTicketResponse)
	err := c.cc.Invoke(ctx, WarehouseService_GetPickTicket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseServiceServer is the server API for WarehouseService service.
// All implementations should embed UnimplementedWarehouseServiceServer
// for forward compatibility
type WarehouseServiceServer interface {
	GetAllocatedOrdersForReceiptItem(context.Context, *GetAllocatedOrdersForReceiptItemRequest) (*GetAllocatedOrdersForReceiptItemResponse, error)
	GetReceivingReport(context.Context, *GetReceivingReportRequest) (*GetReceivingReportResponse, error)
	GetPickTicket(context.Context, *GetPickTicketRequest) (*GetPickTicketResponse, error)
}

// UnimplementedWarehouseServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWarehouseServiceServer struct {
}

func (UnimplementedWarehouseServiceServer) GetAllocatedOrdersForReceiptItem(context.Context, *GetAllocatedOrdersForReceiptItemRequest) (*GetAllocatedOrdersForReceiptItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllocatedOrdersForReceiptItem not implemented")
}
func (UnimplementedWarehouseServiceServer) GetReceivingReport(context.Context, *GetReceivingReportRequest) (*GetReceivingReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceivingReport not implemented")
}
func (UnimplementedWarehouseServiceServer) GetPickTicket(context.Context, *GetPickTicketRequest) (*GetPickTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPickTicket not implemented")
}

// UnsafeWarehouseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseServiceServer will
// result in compilation errors.
type UnsafeWarehouseServiceServer interface {
	mustEmbedUnimplementedWarehouseServiceServer()
}

func RegisterWarehouseServiceServer(s grpc.ServiceRegistrar, srv WarehouseServiceServer) {
	s.RegisterService(&WarehouseService_ServiceDesc, srv)
}

func _WarehouseService_GetAllocatedOrdersForReceiptItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllocatedOrdersForReceiptItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetAllocatedOrdersForReceiptItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetAllocatedOrdersForReceiptItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetAllocatedOrdersForReceiptItem(ctx, req.(*GetAllocatedOrdersForReceiptItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_GetReceivingReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceivingReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetReceivingReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetReceivingReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetReceivingReport(ctx, req.(*GetReceivingReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_GetPickTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPickTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetPickTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetPickTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetPickTicket(ctx, req.(*GetPickTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarehouseService_ServiceDesc is the grpc.ServiceDesc for WarehouseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarehouseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse.v1alpha0.WarehouseService",
	HandlerType: (*WarehouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllocatedOrdersForReceiptItem",
			Handler:    _WarehouseService_GetAllocatedOrdersForReceiptItem_Handler,
		},
		{
			MethodName: "GetReceivingReport",
			Handler:    _WarehouseService_GetReceivingReport_Handler,
		},
		{
			MethodName: "GetPickTicket",
			Handler:    _WarehouseService_GetPickTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warehouse/v1alpha0/warehouse.proto",
}
