package model

import (
	"github.com/uptrace/bun"
	"time"
)

type Address struct {
	bun.BaseModel               `bun:"table:address"`
	Id                          float64   `bun:"id,type:decimal(19,0),pk"`
	Name                        string    `bun:"name,type:varchar(50)"`
	MailAddress1                string    `bun:"mail_address1,type:varchar(50),nullzero"`
	MailAddress2                string    `bun:"mail_address2,type:varchar(50),nullzero"`
	MailCity                    string    `bun:"mail_city,type:varchar(50),nullzero"`
	MailState                   string    `bun:"mail_state,type:varchar(50),nullzero"`
	MailPostalCode              string    `bun:"mail_postal_code,type:varchar(10),nullzero"`
	MailCountry                 string    `bun:"mail_country,type:varchar(50),nullzero"`
	PhysAddress1                string    `bun:"phys_address1,type:varchar(50),nullzero"`
	PhysAddress2                string    `bun:"phys_address2,type:varchar(50),nullzero"`
	PhysCity                    string    `bun:"phys_city,type:varchar(50),nullzero"`
	PhysState                   string    `bun:"phys_state,type:varchar(50),nullzero"`
	PhysPostalCode              string    `bun:"phys_postal_code,type:varchar(10),nullzero"`
	PhysCountry                 string    `bun:"phys_country,type:varchar(50),nullzero"`
	CentralPhoneNumber          string    `bun:"central_phone_number,type:varchar(20),nullzero"`
	CentralFaxNumber            string    `bun:"central_fax_number,type:varchar(20),nullzero"`
	FederalIdNumber             string    `bun:"federal_id_number,type:varchar(255),nullzero"`
	ResaleCertificate           string    `bun:"resale_certificate,type:varchar(40),nullzero"`
	UpsCode                     string    `bun:"ups_code,type:varchar(40),nullzero"`
	CorpAddressId               float64   `bun:"corp_address_id,type:decimal(19,0),nullzero"`
	BillingAddressId            float64   `bun:"billing_address_id,type:decimal(19,0),nullzero"`
	CreditAddressId             float64   `bun:"credit_address_id,type:decimal(19,0),nullzero"`
	Customer                    string    `bun:"customer,type:char,nullzero"`
	Vendor                      string    `bun:"vendor,type:char,nullzero"`
	Employee                    string    `bun:"employee,type:char,nullzero"`
	Prospect                    string    `bun:"prospect,type:char,nullzero"`
	BillingAddress              string    `bun:"billing_address,type:char,nullzero"`
	ShippingAddress             string    `bun:"shipping_address,type:char,nullzero"`
	PaymentAddress              string    `bun:"payment_address,type:char,nullzero"`
	Incorporated                string    `bun:"incorporated,type:char,nullzero"`
	DateCreated                 time.Time `bun:"date_created,type:datetime"`
	DateLastModified            time.Time `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy            string    `bun:"last_maintained_by,type:varchar(30),default:(user_name())"`
	DeleteFlag                  string    `bun:"delete_flag,type:char"`
	DefaultShipTime             time.Time `bun:"default_ship_time,type:datetime,nullzero"`
	PreferredLocationId         float64   `bun:"preferred_location_id,type:decimal(19,0),nullzero"`
	CarrierId                   string    `bun:"carrier_id,type:varchar(10),nullzero"`
	DeliveryInstructions1       string    `bun:"delivery_instructions1,type:varchar(20),nullzero"`
	DeliveryInstructions2       string    `bun:"delivery_instructions2,type:varchar(20),nullzero"`
	DeliveryInstructions3       string    `bun:"delivery_instructions3,type:varchar(20),nullzero"`
	MorBegDelivery              time.Time `bun:"mor_beg_delivery,type:datetime,nullzero"`
	MorEndDelivery              time.Time `bun:"mor_end_delivery,type:datetime,nullzero"`
	EveBegDelivery              time.Time `bun:"eve_beg_delivery,type:datetime,nullzero"`
	EveEndDelivery              time.Time `bun:"eve_end_delivery,type:datetime,nullzero"`
	InventoryLocationFlag       string    `bun:"inventory_location_flag,type:char,nullzero"`
	ShowOutItems                string    `bun:"show_out_items,type:char,nullzero"`
	StoreNo                     string    `bun:"store_no,type:varchar(5),nullzero"`
	InvoiceType                 string    `bun:"invoice_type,type:varchar(2),nullzero"`
	AddressIdString             string    `bun:"address_id_string,type:varchar(22),nullzero"`
	CarrierFlag                 string    `bun:"carrier_flag,type:char,nullzero"`
	DefaultCarrierId            float64   `bun:"default_carrier_id,type:decimal(19,0),nullzero"`
	TradePercentDisc            float64   `bun:"trade_percent_disc,type:decimal(19,0),nullzero"`
	Class1Id                    string    `bun:"class1_id,type:varchar(255),nullzero"`
	Class2Id                    string    `bun:"class2_id,type:varchar(255),nullzero"`
	Class3Id                    string    `bun:"class3_id,type:varchar(255),nullzero"`
	Class4Id                    string    `bun:"class4_id,type:varchar(255),nullzero"`
	Class5Id                    string    `bun:"class5_id,type:varchar(255),nullzero"`
	CentralWattsNumber          string    `bun:"central_watts_number,type:varchar(20),nullzero"`
	Alternative1099Name         string    `bun:"alternative_1099_name,type:varchar(40),nullzero"`
	NameControl                 string    `bun:"name_control,type:varchar(4),nullzero"`
	DefaultShipToCompany        string    `bun:"default_ship_to_company,type:varchar(8),nullzero"`
	DefaultShipToBranch         string    `bun:"default_ship_to_branch,type:varchar(8),nullzero"`
	ShipToPackingBasis          string    `bun:"ship_to_packing_basis,type:varchar(16),nullzero"`
	BillOfLadingType            string    `bun:"bill_of_lading_type,type:varchar(2),nullzero"`
	EmailAddress                string    `bun:"email_address,type:varchar(255),nullzero"`
	Url                         string    `bun:"url,type:varchar(255),nullzero"`
	CarrierFedexFlag            string    `bun:"carrier_fedex_flag,type:char,default:('N')"`
	RouteviewRequireRoutingFlag string    `bun:"routeview_require_routing_flag,type:char,default:('N')"`
	CarrierTypeCd               int32     `bun:"carrier_type_cd,type:int,default:((300))"`
	CarrierDoNotRouteFlag       string    `bun:"carrier_do_not_route_flag,type:char,default:('N')"`
	RoadnetDoNotRouteFlag       string    `bun:"roadnet_do_not_route_flag,type:char,nullzero"`
	CarrierStrategicFreightFlag string    `bun:"carrier_strategic_freight_flag,type:char,nullzero"`
	CarrierFixedFreightCharge   float64   `bun:"carrier_fixed_freight_charge,type:decimal(19,2),nullzero"`
	CarrierFreightEstPercentage float64   `bun:"carrier_freight_est_percentage,type:decimal(19,9),nullzero"`
	ExpeditedFreightOptionCd    int32     `bun:"expedited_freight_option_cd,type:int,nullzero"`
	OrderPriorityUid            int32     `bun:"order_priority_uid,type:int,nullzero"`
	DcDoNotRouteFlag            string    `bun:"dc_do_not_route_flag,type:char,nullzero"`
	RoadnetPtPrintOption        string    `bun:"roadnet_pt_print_option,type:char,nullzero"`
	SfdcAccountId               string    `bun:"sfdc_account_id,type:varchar(255),nullzero"`
	SfdcCreateDate              time.Time `bun:"sfdc_create_date,type:datetime,nullzero"`
	SfdcUpdateDate              time.Time `bun:"sfdc_update_date,type:datetime,nullzero"`
	CarrierFixedFreightMarkup   float64   `bun:"carrier_fixed_freight_markup,type:decimal(19,9),nullzero"`
	PhysCounty                  string    `bun:"phys_county,type:varchar(255),nullzero"`
	ScacCode                    string    `bun:"scac_code,type:varchar(4),nullzero"`
	CarrierPalletWeightLimit    int32     `bun:"carrier_pallet_weight_limit,type:int,nullzero"`
	CarrierPalletFreightCharge  float64   `bun:"carrier_pallet_freight_charge,type:decimal(19,4),nullzero"`
	FreightCodeUid              int32     `bun:"freight_code_uid,type:int,nullzero"`
	CarrierTransitDays          int32     `bun:"carrier_transit_days,type:int,nullzero"`
	FidelitoneCarrierId         string    `bun:"fidelitone_carrier_id,type:varchar(255),nullzero"`
	MailAddress3                string    `bun:"mail_address3,type:varchar(50),nullzero"`
	PhysAddress3                string    `bun:"phys_address3,type:varchar(50),nullzero"`
	ShippingRouteUid            int32     `bun:"shipping_route_uid,type:int,nullzero"`
	FreightSurchargeFlag        string    `bun:"freight_surcharge_flag,type:char,default:('N')"`
	FreightSurchargePkgWeight   float64   `bun:"freight_surcharge_pkg_weight,type:decimal(19,9),default:((0))"`
	FreightSurchargePerPkg      float64   `bun:"freight_surcharge_per_pkg,type:decimal(19,9),default:((0))"`
	ExpressCarrierFlag          string    `bun:"express_carrier_flag,type:char,default:('N')"`
	Latitude                    string    `bun:"latitude,type:varchar(20),nullzero"`
	Longitude                   string    `bun:"longitude,type:varchar(20),nullzero"`
	CarrierProviderTypeUid      int32     `bun:"carrier_provider_type_uid,type:int,nullzero"`
	RateGroupId                 int32     `bun:"rate_group_id,type:int,nullzero"`
	LtlFreightCalcPercentage    float64   `bun:"ltl_freight_calc_percentage,type:decimal(19,9),default:((0))"`
	ParcelCarrierFlag           string    `bun:"parcel_carrier_flag,type:char,default:('N')"`
	DqDoNotRouteFlag            string    `bun:"dq_do_not_route_flag,type:char,nullzero"`
	DqPrintPtFlag               string    `bun:"dq_print_pt_flag,type:char,nullzero"`
	TransportationTypeCode      string    `bun:"transportation_type_code,type:varchar(255),nullzero"`
	DisplayInOeFlag             string    `bun:"display_in_oe_flag,type:char,nullzero"`
	NeighborhoodCode            string    `bun:"neighborhood_code,type:varchar(255),nullzero"`
	CityCode                    string    `bun:"city_code,type:varchar(255),nullzero"`
	LocalityCode                string    `bun:"locality_code,type:varchar(255),nullzero"`
}
