package model

type Company struct {
	bun.BaseModel                     `bun:"table:company"`
	CompanyId                         string    `bun:"company_id,type:varchar(8),pk"`
	CompanyName                       string    `bun:"company_name,type:varchar(40)"`
	FederalIdNo                       string    `bun:"federal_id_no,type:varchar(255),nullzero"`
	FiscalYearEnd                     string    `bun:"fiscal_year_end,type:varchar(5),nullzero"`
	DateCreated                       time.Time `bun:"date_created,type:datetime"`
	DateLastModified                  time.Time `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy                  string    `bun:"last_maintained_by,type:varchar(30),default:(suser_name(null))"`
	AddressId                         float64   `bun:"address_id,type:decimal(19,0)"`
	DeleteFlag                        string    `bun:"delete_flag,type:char"`
	RePriceLineItems                  string    `bun:"re_price_line_items,type:char,nullzero"`
	PricingByLocation                 string    `bun:"pricing_by_location,type:char,nullzero"`
	GlAccountLength                   string    `bun:"gl_account_length,type:varchar(32)"`
	GlCapitalizedOverhead             string    `bun:"gl_capitalized_overhead,type:varchar(32),nullzero"`
	GlFreightIn                       string    `bun:"gl_freight_in,type:varchar(32),nullzero"`
	NumberOfPeriods                   float64   `bun:"number_of_periods,type:decimal(3,0),nullzero"`
	RetainedEarningsAcctNo            string    `bun:"retained_earnings_acct_no,type:varchar(32),nullzero"`
	TermsTakenAccountNo               string    `bun:"terms_taken_account_no,type:varchar(32),nullzero"`
	HomeCurrencyId                    float64   `bun:"home_currency_id,type:decimal(19,0)"`
	GlGainOrLossAcct                  string    `bun:"gl_gain_or_loss_acct,type:varchar(32),nullzero"`
	San                               string    `bun:"san,type:varchar(15),nullzero"`
	GroupControlNo                    string    `bun:"group_control_no,type:varchar(9),nullzero"`
	IntlSan                           string    `bun:"intl_san,type:varchar(15),nullzero"`
	GstPaidAcct                       string    `bun:"gst_paid_acct,type:varchar(32),nullzero"`
	MaxInvoiceAllowance               float64   `bun:"max_invoice_allowance,type:decimal(19,4),nullzero"`
	GstRegistrationNo                 string    `bun:"gst_registration_no,type:varchar(20),nullzero"`
	StageClearingAccountNo            string    `bun:"stage_clearing_account_no,type:varchar(32),nullzero"`
	TransmitterControlCode            string    `bun:"transmitter_control_code,type:varchar(5),nullzero"`
	ForeignEntityIndicator            string    `bun:"foreign_entity_indicator,type:char,nullzero"`
	UseBranchAccounting               string    `bun:"use_branch_accounting,type:char,nullzero"`
	BranchSegmentInCoa                float64   `bun:"branch_segment_in_coa,type:decimal(2,0),nullzero"`
	InvScan1                          float64   `bun:"inv_scan_1,type:decimal(1,0),nullzero"`
	InvScan2                          float64   `bun:"inv_scan_2,type:decimal(1,0),nullzero"`
	InvScan3                          float64   `bun:"inv_scan_3,type:decimal(1,0),nullzero"`
	InvScan4                          float64   `bun:"inv_scan_4,type:decimal(1,0),nullzero"`
	InvScan5                          float64   `bun:"inv_scan_5,type:decimal(1,0),nullzero"`
	InvScan6                          float64   `bun:"inv_scan_6,type:decimal(1,0),nullzero"`
	ArAgingPeriod1                    float64   `bun:"ar_aging_period1,type:decimal(3,0),nullzero"`
	ArAgingPeriod2                    float64   `bun:"ar_aging_period2,type:decimal(3,0),nullzero"`
	ArAgingPeriod3                    float64   `bun:"ar_aging_period3,type:decimal(3,0),nullzero"`
	JcFlag                            string    `bun:"jc_flag,type:char,nullzero"`
	InvReceiptsClearingAcct           string    `bun:"inv_receipts_clearing_acct,type:varchar(32),nullzero"`
	InterbranchRecPayableAcct         string    `bun:"interbranch_rec_payable_acct,type:varchar(32),nullzero"`
	BranchDebitEqualCredit            string    `bun:"branch_debit_equal_credit,type:char,nullzero"`
	FcPercentage                      float64   `bun:"fc_percentage,type:decimal(19,4),nullzero"`
	FcGraceDays                       float64   `bun:"fc_grace_days,type:decimal(19,4),nullzero"`
	MinimumFc                         float64   `bun:"minimum_fc,type:decimal(19,9),nullzero"`
	MinimumFcToInvoice                float64   `bun:"minimum_fc_to_invoice,type:decimal(19,9),nullzero"`
	WipCosAccountNumber               string    `bun:"wip_cos_account_number,type:varchar(32),nullzero"`
	CompoundFc                        string    `bun:"compound_fc,type:char,nullzero"`
	FcAllowedAcct                     string    `bun:"fc_allowed_acct,type:varchar(32),nullzero"`
	FcInvoiceClass                    string    `bun:"fc_invoice_class,type:varchar(8),nullzero"`
	GenerateFinanceCharges            string    `bun:"generate_finance_charges,type:char,nullzero"`
	FcAllowedAccount                  string    `bun:"fc_allowed_account,type:varchar(32),nullzero"`
	FcRevenueAccount                  string    `bun:"fc_revenue_account,type:varchar(32),nullzero"`
	UsingEncumbrances                 string    `bun:"using_encumbrances,type:char,nullzero"`
	CostToOrder                       float64   `bun:"cost_to_order,type:decimal(19,9),nullzero"`
	CarryingCost                      float64   `bun:"carrying_cost,type:decimal(19,9),nullzero"`
	UnitCost                          float64   `bun:"unit_cost,type:decimal(19,9),nullzero"`
	TrackApByBranch                   string    `bun:"track_ap_by_branch,type:char,nullzero"`
	TrackArByBranch                   string    `bun:"track_ar_by_branch,type:char,nullzero"`
	TrackProdCapitalizedOh            string    `bun:"track_prod_capitalized_oh,type:char,nullzero"`
	LogoPathFilename                  string    `bun:"logo_path_filename,type:varchar(255),nullzero"`
	CommissionExpenseAcct             string    `bun:"commission_expense_acct,type:varchar(32),nullzero"`
	AccrualAcct                       string    `bun:"accrual_acct,type:varchar(32),nullzero"`
	InvCostVarianceAcct               string    `bun:"inv_cost_variance_acct,type:varchar(32),nullzero"`
	InvFreightVarianceAcct            string    `bun:"inv_freight_variance_acct,type:varchar(32),nullzero"`
	InvQtyVarianceAcct                string    `bun:"inv_qty_variance_acct,type:varchar(32),nullzero"`
	PostVarianceToAvgCost             string    `bun:"post_variance_to_avg_cost,type:char"`
	ProrateFreight                    string    `bun:"prorate_freight,type:char"`
	PostFreightToAvgCost              string    `bun:"post_freight_to_avg_cost,type:char"`
	FrlUseFrx                         string    `bun:"frl_use_frx,type:char,nullzero"`
	FrlAcctMask                       string    `bun:"frl_acct_mask,type:varchar(128),nullzero"`
	FrlNumberOfSegments               int32     `bun:"frl_number_of_segments,type:int,nullzero"`
	FrlNaturalSegment                 int32     `bun:"frl_natural_segment,type:int,nullzero"`
	CreateOrderBasedTransfers         string    `bun:"create_order_based_transfers,type:char"`
	MarkUpOnTransfers                 string    `bun:"mark_up_on_transfers,type:char"`
	MarkUpType                        string    `bun:"mark_up_type,type:char,nullzero"`
	MarkUpValue                       float64   `bun:"mark_up_value,type:decimal(19,9),nullzero"`
	SourceMarkUpAccount               string    `bun:"source_mark_up_account,type:varchar(32),nullzero"`
	MarkUpSource                      string    `bun:"mark_up_source,type:char,nullzero"`
	SourceOtherChargeAccount          string    `bun:"source_other_charge_account,type:varchar(32),nullzero"`
	DestinationMarkUpAcct             string    `bun:"destination_mark_up_acct,type:varchar(32),nullzero"`
	DestinationOtherChargeAcct        string    `bun:"destination_other_charge_acct,type:varchar(32),nullzero"`
	FrlLastTransferDate               string    `bun:"frl_last_transfer_date,type:smalldatetime,default:('1/1/1980')"`
	DefaultSourcePriceCd              int32     `bun:"default_source_price_cd,type:int,nullzero"`
	DefaultMultiplier                 float64   `bun:"default_multiplier,type:decimal(19,9),nullzero"`
	LandedCostClearingAcct            string    `bun:"landed_cost_clearing_acct,type:varchar(32),default:(null)"`
	FrlMaxBatchId                     int32     `bun:"frl_max_batch_id,type:int,nullzero"`
	DefaultSalesLocationId            float64   `bun:"default_sales_location_id,type:decimal(19,0),nullzero"`
	EdiExportPath                     string    `bun:"edi_export_path,type:varchar(255),nullzero"`
	FreightCodeUid                    int32     `bun:"freight_code_uid,type:int,nullzero"`
	NumberOfDemandPeriods             int16     `bun:"number_of_demand_periods,type:smallint,default:(1)"`
	InvFreightExpenseAcct             string    `bun:"inv_freight_expense_acct,type:varchar(32),nullzero"`
	RequisitionClearingAcct           string    `bun:"requisition_clearing_acct,type:varchar(32),nullzero"`
	RestockingFeeAccountNo            string    `bun:"restocking_fee_account_no,type:varchar(32),nullzero"`
	SignaturePath                     string    `bun:"signature_path,type:varchar(255),nullzero"`
	LotCostChangeAccountNo            string    `bun:"lot_cost_change_account_no,type:varchar(32),nullzero"`
	RebateAccountNo                   string    `bun:"rebate_account_no,type:varchar(32),nullzero"`
	RebateAllowanceAccountNo          string    `bun:"rebate_allowance_account_no,type:varchar(32),nullzero"`
	AllowDiscountsOnPartialPmt        string    `bun:"allow_discounts_on_partial_pmt,type:char,default:('N')"`
	AutoApplyAvailDiscounts           string    `bun:"auto_apply_avail_discounts,type:char,default:('N')"`
	GracePeriodDays                   int32     `bun:"grace_period_days,type:int,default:(0)"`
	DisassemblyReasonId               string    `bun:"disassembly_reason_id,type:varchar(5),nullzero"`
	TpcxMember                        string    `bun:"tpcx_member,type:char,default:('N')"`
	VendorConsignInvOffsetAcct        string    `bun:"vendor_consign_inv_offset_acct,type:varchar(32),nullzero"`
	FinanceChgInvDueDateCode          int32     `bun:"finance_chg_inv_due_date_code,type:int,default:(1248)"`
	RmaReceiptClearingAcct            string    `bun:"rma_receipt_clearing_acct,type:varchar(32),nullzero"`
	RmaAdjustmentReasonId             string    `bun:"rma_adjustment_reason_id,type:varchar(5),nullzero"`
	RmaDefaultRtsLocationId           float64   `bun:"rma_default_rts_location_id,type:decimal(19,0),default:(null)"`
	RmaAutoReturnToStock              string    `bun:"rma_auto_return_to_stock,type:char,default:('N')"`
	InventoryAdjustmentReasonId       string    `bun:"inventory_adjustment_reason_id,type:varchar(5),nullzero"`
	ReturnedCheckFeeAcct              string    `bun:"returned_check_fee_acct,type:varchar(32),nullzero"`
	AllowableInvoiceVariance          float64   `bun:"allowable_invoice_variance,type:decimal(19,9),nullzero"`
	InvoiceVarianceTypeFlag           string    `bun:"invoice_variance_type_flag,type:char,default:('A')"`
	CreatePrepaidInvoiceFlag          string    `bun:"create_prepaid_invoice_flag,type:char,default:('Y')"`
	TagSuffix                         string    `bun:"tag_suffix,type:varchar(255),nullzero"`
	DataIdentifierGroupUid            int32     `bun:"data_identifier_group_uid,type:int,nullzero"`
	RfScannerPrefix                   string    `bun:"rf_scanner_prefix,type:varchar(255),nullzero"`
	DefaultArpymtBankNo               float64   `bun:"default_arpymt_bank_no,type:decimal(19,0),nullzero"`
	DefaultArpymtBranchId             string    `bun:"default_arpymt_branch_id,type:varchar(8),nullzero"`
	CarrierInsuranceAcct              string    `bun:"carrier_insurance_acct,type:varchar(32),nullzero"`
	PostLcVarianceToAvgCost           string    `bun:"post_lc_variance_to_avg_cost,type:char,default:('N')"`
	RestockFeePercentage              float64   `bun:"restock_fee_percentage,type:decimal(19,9),default:(0)"`
	RestockFeeAccount                 string    `bun:"restock_fee_account,type:varchar(32),nullzero"`
	CouponClearingAcctNo              string    `bun:"coupon_clearing_acct_no,type:varchar(32),nullzero"`
	DisassemblyCostVarAcctNo          string    `bun:"disassembly_cost_var_acct_no,type:varchar(32),nullzero"`
	CouponIssuedAcctNo                string    `bun:"coupon_issued_acct_no,type:varchar(32),nullzero"`
	JobIdRequiredFlag                 string    `bun:"job_id_required_flag,type:char,default:('N')"`
	AssemblyCostVarianceAcct          string    `bun:"assembly_cost_variance_acct,type:varchar(255),nullzero"`
	TrackLostSalesFlag                string    `bun:"track_lost_sales_flag,type:char,default:('N')"`
	RestockingFeeTaxableFlag          string    `bun:"restocking_fee_taxable_flag,type:char,default:('Y')"`
	CompanyMacRoundingAcct            string    `bun:"company_mac_rounding_acct,type:varchar(32),nullzero"`
	SpecialInventoryAcct              string    `bun:"special_inventory_acct,type:varchar(32),nullzero"`
	InvInVesselAcct                   string    `bun:"inv_in_vessel_acct,type:varchar(32),nullzero"`
	InvInTransitClearingAcct          string    `bun:"inv_in_transit_clearing_acct,type:varchar(32),nullzero"`
	CommissionReceivableAcct          string    `bun:"commission_receivable_acct,type:varchar(32),nullzero"`
	CommissionRevenueAcct             string    `bun:"commission_revenue_acct,type:varchar(32),nullzero"`
	CommissionAllowanceAcct           string    `bun:"commission_allowance_acct,type:varchar(32),nullzero"`
	LotBillClearingAcct               string    `bun:"lot_bill_clearing_acct,type:varchar(32),nullzero"`
	AssemblyVarianceAcct              string    `bun:"assembly_variance_acct,type:varchar(32),nullzero"`
	GlAcctForAppliedLabor             string    `bun:"gl_acct_for_applied_labor,type:varchar(32),nullzero"`
	GlAcctForLaborCos                 string    `bun:"gl_acct_for_labor_cos,type:varchar(32),nullzero"`
	GlAcctForFreightClearing          string    `bun:"gl_acct_for_freight_clearing,type:varchar(32),nullzero"`
	CurrencyBankClearingAcct          string    `bun:"currency_bank_clearing_acct,type:varchar(32),nullzero"`
	PostCommissionAccrualsFlag        string    `bun:"post_commission_accruals_flag,type:char,default:('N')"`
	UpsAccountNo                      string    `bun:"ups_account_no,type:varchar(255),nullzero"`
	UpsOltUserId                      string    `bun:"ups_olt_user_id,type:varchar(255),nullzero"`
	UpsOltPassword                    string    `bun:"ups_olt_password,type:varchar(255),nullzero"`
	UpsOltAccessKey                   string    `bun:"ups_olt_access_key,type:varchar(255),nullzero"`
	SpAllocFromStockVarAcct           string    `bun:"sp_alloc_from_stock_var_acct,type:varchar(32),nullzero"`
	DunsNo                            string    `bun:"duns_no,type:varchar(255),nullzero"`
	GlAcctForLaborWip                 string    `bun:"gl_acct_for_labor_wip,type:varchar(32),nullzero"`
	DefaultFaxCoverUid                int32     `bun:"default_fax_cover_uid,type:int,nullzero"`
	PredefinedCoaCd                   int32     `bun:"predefined_coa_cd,type:int,nullzero"`
	GlAcctLongtermContracts           string    `bun:"gl_acct_longterm_contracts,type:varchar(32),nullzero"`
	ProdAutoTransferReasonId          string    `bun:"prod_auto_transfer_reason_id,type:varchar(5),nullzero"`
	CouponAllowedAcctNo               string    `bun:"coupon_allowed_acct_no,type:varchar(32),nullzero"`
	PedigreeContactId                 string    `bun:"pedigree_contact_id,type:varchar(16),nullzero"`
	ValidateCommissionSplitFlag       string    `bun:"validate_commission_split_flag,type:char,default:('N')"`
	DunsNumber                        string    `bun:"duns_number,type:varchar(255),nullzero"`
	AcceptPymtsWithNoInvFlag          string    `bun:"accept_pymts_with_no_inv_flag,type:char,default:('N')"`
	AcceptIncorrectInvFlag            string    `bun:"accept_incorrect_inv_flag,type:char,default:('N')"`
	AcceptPartialPaymentFlag          string    `bun:"accept_partial_payment_flag,type:char,default:('N')"`
	BranchStart                       int16     `bun:"branch_start,type:smallint,nullzero"`
	BranchLength                      int16     `bun:"branch_length,type:smallint,nullzero"`
	AccountLength                     int16     `bun:"account_length,type:smallint,nullzero"`
	VertexEnabled                     string    `bun:"vertex_enabled,type:char,default:('N')"`
	DefaultSalesTaxPayableAcct        string    `bun:"default_sales_tax_payable_acct,type:varchar(32),nullzero"`
	PallRepNumber                     string    `bun:"pall_rep_number,type:varchar(5),nullzero"`
	IntrastatEnabledFlag              string    `bun:"intrastat_enabled_flag,type:char,default:('N')"`
	UseIntAddressFormatFlag           string    `bun:"use_int_address_format_flag,type:char,default:('N')"`
	UseCogsAcctForOciFlag             string    `bun:"use_cogs_acct_for_oci_flag,type:char,default:('N')"`
	RestockingFeeId                   string    `bun:"restocking_fee_id,type:varchar(40),nullzero"`
	UseQuoteRevisionFlag              string    `bun:"use_quote_revision_flag,type:char,default:('N')"`
	SummaryCommodityCode              string    `bun:"summary_commodity_code,type:varchar(255),nullzero"`
	CompanyTaxgroupByZipcodeFlag      string    `bun:"company_taxgroup_by_zipcode_flag,type:char,default:('N')"`
	ServiceUserNumber                 string    `bun:"service_user_number,type:varchar(6),nullzero"`
	CfnGasCogsAcct                    string    `bun:"cfn_gas_cogs_acct,type:varchar(32),nullzero"`
	CfnReceivableAcct                 string    `bun:"cfn_receivable_acct,type:varchar(32),nullzero"`
	CfnGasRevenueAcct                 string    `bun:"cfn_gas_revenue_acct,type:varchar(32),nullzero"`
	RoundUnitPricesFlag               string    `bun:"round_unit_prices_flag,type:char,default:('N')"`
	AvalaraEnabled                    string    `bun:"avalara_enabled,type:char,default:('N')"`
	IvaEnabled                        string    `bun:"iva_enabled,type:varchar,default:('N')"`
	TrackInvOnWaterBranchFlag         string    `bun:"track_inv_on_water_branch_flag,type:char,default:('Y')"`
	FreightWipAcct                    string    `bun:"freight_wip_acct,type:varchar(32),nullzero"`
	PendingWarrantyAcct               string    `bun:"pending_warranty_acct,type:varchar(32),nullzero"`
	DefaultCustomerTaxClass           string    `bun:"default_customer_tax_class,type:varchar(255),nullzero"`
	CountrySpecificCd                 int32     `bun:"country_specific_cd,type:int,nullzero"`
	BorrowingRateToCarry              float64   `bun:"borrowing_rate_to_carry,type:decimal(19,4),default:((0))"`
	FillOrKillReasonUid               int32     `bun:"fill_or_kill_reason_uid,type:int,nullzero"`
	FillAndKillReasonUid              int32     `bun:"fill_and_kill_reason_uid,type:int,nullzero"`
	InvoiceOnlyLocationId             float64   `bun:"invoice_only_location_id,type:decimal(19,0),nullzero"`
	ExternalTaxCompanyCode            string    `bun:"external_tax_company_code,type:varchar(255),nullzero"`
	ArToApClearingAcct                string    `bun:"ar_to_ap_clearing_acct,type:varchar(32),nullzero"`
	CompanyUid                        int32     `bun:"company_uid,type:int,identity"`
	GlForeignCardlockAcct             string    `bun:"gl_foreign_cardlock_acct,type:varchar(32),nullzero"`
	BinTypeUid                        int32     `bun:"bin_type_uid,type:int,nullzero"`
	PriceRoundingFlag                 string    `bun:"price_rounding_flag,type:char,nullzero"`
	OverUnderRoundingAcct             string    `bun:"over_under_rounding_acct,type:varchar(255),nullzero"`
	FutureCostDefaultFromLocId        float64   `bun:"future_cost_default_from_loc_id,type:decimal(19,0),nullzero"`
	EditTrackingNumberFlag            string    `bun:"edit_tracking_number_flag,type:varchar,default:('N')"`
	RebateCogsAccountNo               string    `bun:"rebate_cogs_account_no,type:varchar(32),nullzero"`
	FillableReasonId                  string    `bun:"fillable_reason_id,type:varchar(5),nullzero"`
	CfnDieselCogsAcct                 string    `bun:"cfn_diesel_cogs_acct,type:varchar(32),nullzero"`
	CfnDieselRevenueAcct              string    `bun:"cfn_diesel_revenue_acct,type:varchar(32),nullzero"`
	BusinessDaysPerYear               int16     `bun:"business_days_per_year,type:smallint,default:((250))"`
	AveragePretaxProfit               float64   `bun:"average_pretax_profit,type:decimal(19,4),default:((0.075))"`
	SbVendorCreditOffsetAcct          string    `bun:"sb_vendor_credit_offset_acct,type:varchar(32),nullzero"`
	EnableMultiCurrencyPayments       string    `bun:"enable_multi_currency_payments,type:char,nullzero"`
	CurrencyClearingAccountNo         string    `bun:"currency_clearing_account_no,type:varchar(255),nullzero"`
	BrokerEmailAddress                string    `bun:"broker_email_address,type:varchar(255),nullzero"`
	WarrantyRmaReceiptClearingAcct    string    `bun:"warranty_rma_receipt_clearing_acct,type:varchar(32),nullzero"`
	WarrInvReceiptsClearingAcct       string    `bun:"warr_inv_receipts_clearing_acct,type:varchar(32),nullzero"`
	TrafficManagerContactId           string    `bun:"traffic_manager_contact_id,type:varchar(16),nullzero"`
	ProFormaSignaturePath             string    `bun:"pro_forma_signature_path,type:varchar(255),nullzero"`
	ProFormaSignatureName             string    `bun:"pro_forma_signature_name,type:varchar(255),nullzero"`
	CostAndRevenueBasedOnSalesrepFlag string    `bun:"cost_and_revenue_based_on_salesrep_flag,type:char,default:('N')"`
	TaCylinderRentalRevAcct           string    `bun:"ta_cylinder_rental_rev_acct,type:varchar(32),nullzero"`
	TaEquipmentRentalRevAcct          string    `bun:"ta_equipment_rental_rev_acct,type:varchar(32),nullzero"`
	RemnantReasonId                   string    `bun:"remnant_reason_id,type:varchar(5),nullzero"`
	RemnantSourceCostCd               int32     `bun:"remnant_source_cost_cd,type:int,default:((3617))"`
	UseXfersrclocRevacctLcFlag        string    `bun:"use_xfersrcloc_revacct_lc_flag,type:char,nullzero"`
	XfersrclocRevenueAcctForLc        string    `bun:"xfersrcloc_revenue_acct_for_lc,type:varchar(32),nullzero"`
	UseDimensions                     string    `bun:"use_dimensions,type:char,default:('N')"`
	ProdOrderWipTrackingCd            int32     `bun:"prod_order_wip_tracking_cd,type:int,default:((3752))"`
	InventoryWipAccountNo             string    `bun:"inventory_wip_account_no,type:varchar(32),nullzero"`
	OtherChargeWipAccountNo           string    `bun:"other_charge_wip_account_no,type:varchar(32),nullzero"`
	ZoneCostExchangeAcct              string    `bun:"zone_cost_exchange_acct,type:varchar(32),nullzero"`
	ZoneCostVarianceAcct              string    `bun:"zone_cost_variance_acct,type:varchar(32),nullzero"`
	ShowVatPerInvLineFlag             string    `bun:"show_vat_per_inv_line_flag,type:char,default:('N')"`
	RetailDeliveryFeePayableAcct      string    `bun:"retail_delivery_fee_payable_acct,type:varchar(32),nullzero"`
}
