package model

type Customer struct {
	bun.BaseModel                        `bun:"table:customer"`
	CustomerId                           float64   `bun:"customer_id,type:decimal(19,0),pk"`
	CompanyId                            string    `bun:"company_id,type:varchar(8),pk"`
	TaxableFlag                          string    `bun:"taxable_flag,type:char"`
	ResaleCertificate                    string    `bun:"resale_certificate,type:varchar(40),nullzero"`
	CreditLimit                          float64   `bun:"credit_limit,type:decimal(22,4),nullzero"`
	CreditLimitUsed                      float64   `bun:"credit_limit_used,type:decimal(22,4),nullzero"`
	TermsId                              string    `bun:"terms_id,type:varchar(2)"`
	SalesrepId                           string    `bun:"salesrep_id,type:varchar(16),nullzero"`
	ArAccountNo                          string    `bun:"ar_account_no,type:varchar(32),nullzero"`
	RevenueAccountNo                     string    `bun:"revenue_account_no,type:varchar(32),nullzero"`
	CosAccountNo                         string    `bun:"cos_account_no,type:varchar(32),nullzero"`
	AllowedAccountNo                     string    `bun:"allowed_account_no,type:varchar(32),nullzero"`
	TermsAccountNo                       string    `bun:"terms_account_no,type:varchar(32),nullzero"`
	DeleteFlag                           string    `bun:"delete_flag,type:char,default:('N')"`
	DateCreated                          time.Time `bun:"date_created,type:datetime,default:(getdate())"`
	DateLastModified                     time.Time `bun:"date_last_modified,type:datetime,default:(getdate())"`
	LastMaintainedBy                     string    `bun:"last_maintained_by,type:varchar(30),default:(user_name(null))"`
	CustomerIdString                     string    `bun:"customer_id_string,type:varchar(22)"`
	FreightAccountNo                     string    `bun:"freight_account_no,type:varchar(32),nullzero"`
	BrokerageAccountNo                   string    `bun:"brokerage_account_no,type:varchar(32),nullzero"`
	Class1id                             string    `bun:"class_1id,type:varchar(255),nullzero"`
	Class2id                             string    `bun:"class_2id,type:varchar(255),nullzero"`
	Class3id                             string    `bun:"class_3id,type:varchar(255),nullzero"`
	Class4id                             string    `bun:"class_4id,type:varchar(255),nullzero"`
	Class5id                             string    `bun:"class_5id,type:varchar(255),nullzero"`
	TradePercentDisc                     float64   `bun:"trade_percent_disc,type:decimal(22,4),nullzero"`
	AcceptPartialOrders                  string    `bun:"accept_partial_orders,type:char,nullzero"`
	AcceptableWaitTime                   float64   `bun:"acceptable_wait_time,type:decimal(22,4),nullzero"`
	PriceFileId                          float64   `bun:"price_file_id,type:decimal(22,4),nullzero"`
	EdiOrPaper                           string    `bun:"edi_or_paper,type:char,nullzero"`
	SecurityInfo                         string    `bun:"security_info,type:varchar(10),nullzero"`
	InterchgReceiverId                   string    `bun:"interchg_receiver_id,type:varchar(15),nullzero"`
	IntlSan                              string    `bun:"intl_san,type:varchar(15),nullzero"`
	CreditCardNo                         string    `bun:"credit_card_no,type:varchar(24),nullzero"`
	CreditCardType                       string    `bun:"credit_card_type,type:varchar(10),nullzero"`
	CreditCardName                       string    `bun:"credit_card_name,type:varchar(41),nullzero"`
	CreditCardExpirationDate             time.Time `bun:"credit_card_expiration_date,type:datetime,nullzero"`
	LastCheckNumber                      string    `bun:"last_check_number,type:varchar(40),nullzero"`
	LastCheckAmount                      float64   `bun:"last_check_amount,type:decimal(22,4),nullzero"`
	LastCheckDate                        time.Time `bun:"last_check_date,type:datetime,nullzero"`
	ReceivableGroupId                    string    `bun:"receivable_group_id,type:varchar(8),nullzero"`
	CreditLimitPerOrder                  float64   `bun:"credit_limit_per_order,type:decimal(19,4),nullzero"`
	OpenItemBalanceForward               string    `bun:"open_item_balance_forward,type:char,nullzero"`
	OrderAcknowledgments                 string    `bun:"order_acknowledgments,type:char,default:('Y')"`
	AcceptInterchangeableItems           string    `bun:"accept_interchangeable_items,type:char,nullzero"`
	BillToContactId                      string    `bun:"bill_to_contact_id,type:varchar(16),nullzero"`
	GenerateFinanceCharges               string    `bun:"generate_finance_charges,type:char,nullzero"`
	LimitMaxShipmentsPerOrder            float64   `bun:"limit_max_shipments_per_order,type:decimal(19,4),nullzero"`
	CreditLimitCheckAtShipment           string    `bun:"credit_limit_check_at_shipment,type:char,nullzero"`
	GenerateCustomerStatements           string    `bun:"generate_customer_statements,type:char,default:('Y')"`
	SicCode                              float64   `bun:"sic_code,type:decimal(6,0),nullzero"`
	MinimumOrderDollarAmount             float64   `bun:"minimum_order_dollar_amount,type:decimal(19,4),nullzero"`
	FederalExemptionNumber               string    `bun:"federal_exemption_number,type:varchar(40),nullzero"`
	OtherExemptionNumber                 string    `bun:"other_exemption_number,type:varchar(40),nullzero"`
	FloorPlanAccount                     string    `bun:"floor_plan_account,type:char"`
	DefaultDisposition                   string    `bun:"default_disposition,type:char"`
	FcPercentage                         float64   `bun:"fc_percentage,type:decimal(19,4),default:(0)"`
	FcGraceDays                          float64   `bun:"fc_grace_days,type:decimal(19,0),default:(0)"`
	MinimumFinanceCharge                 float64   `bun:"minimum_finance_charge,type:decimal(19,4),default:(0)"`
	FcCycle                              string    `bun:"fc_cycle,type:char,nullzero"`
	LastFcDate                           time.Time `bun:"last_fc_date,type:datetime,nullzero"`
	StatementFrequencyId                 string    `bun:"statement_frequency_id,type:varchar(8),nullzero"`
	HighestCreditLimitUsed               float64   `bun:"highest_credit_limit_used,type:decimal(19,4),nullzero"`
	BilledOnGrossNetQty                  string    `bun:"billed_on_gross_net_qty,type:char,nullzero"`
	StateExciseTaxExemptionNo            string    `bun:"state_excise_tax_exemption_no,type:varchar(40),nullzero"`
	CreditStatus                         string    `bun:"credit_status,type:varchar(8),nullzero"`
	DeferredRevenueAccountNo             string    `bun:"deferred_revenue_account_no,type:varchar(32),nullzero"`
	OverrideRevenueByItem                string    `bun:"override_revenue_by_item,type:char,nullzero"`
	PickTicketType                       string    `bun:"pick_ticket_type,type:varchar(2),nullzero"`
	FinanceChgRevenueAccountNo           string    `bun:"finance_chg_revenue_account_no,type:varchar(32),nullzero"`
	FinanceChargeShipToId                float64   `bun:"finance_charge_ship_to_id,type:decimal(19,0),nullzero"`
	CustomerName                         string    `bun:"customer_name,type:varchar(255),nullzero"`
	UseConsolidatedInvoicing             string    `bun:"use_consolidated_invoicing,type:char,default:('N')"`
	CiForCompleteOrdersOnly              string    `bun:"ci_for_complete_orders_only,type:char,default:('N')"`
	CiPrintDetail                        string    `bun:"ci_print_detail,type:char,default:('N')"`
	InvoicePrintQty                      float64   `bun:"invoice_print_qty,type:decimal(5,0),default:(0)"`
	FobRequiredFlag                      string    `bun:"fob_required_flag,type:char,default:('Y')"`
	CodRequiredFlag                      string    `bun:"cod_required_flag,type:char,default:('N')"`
	PricingMethodCd                      int16     `bun:"pricing_method_cd,type:tinyint,nullzero"`
	SourcePriceCd                        int32     `bun:"source_price_cd,type:int,nullzero"`
	Multiplier                           float64   `bun:"multiplier,type:decimal(19,9),nullzero"`
	PoNoRequired                         string    `bun:"po_no_required,type:char,default:('N')"`
	ConsolidatedShipToId                 float64   `bun:"consolidated_ship_to_id,type:decimal(19,0),nullzero"`
	InvoiceBatchUid                      int32     `bun:"invoice_batch_uid,type:int,default:(1)"`
	CustomerStatementHistoryUid          int32     `bun:"customer_statement_history_uid,type:int,nullzero"`
	TradingPartnerName                   string    `bun:"trading_partner_name,type:varchar(255),nullzero"`
	DefaultRebateLocationId              float64   `bun:"default_rebate_location_id,type:decimal(19,0),nullzero"`
	LotBillSummaryOnInvoices             string    `bun:"lot_bill_summary_on_invoices,type:char,default:('Y')"`
	PrintZeroDollarCustomers             string    `bun:"print_zero_dollar_customers,type:char,default:('N')"`
	GenerateStatementsBy                 int16     `bun:"generate_statements_by,type:smallint,default:(1005)"`
	PendingPaymentAccountNo              string    `bun:"pending_payment_account_no,type:varchar(32),nullzero"`
	PrintPricesOnPackinglist             string    `bun:"print_prices_on_packinglist,type:char,default:('N')"`
	JobPricing                           string    `bun:"job_pricing,type:char,default:('N')"`
	RecordType                           int16     `bun:"record_type,type:smallint,nullzero"`
	RecordSource                         string    `bun:"record_source,type:varchar(255),nullzero"`
	SlxContactid                         string    `bun:"slx_contactid,type:varchar(255),nullzero"`
	StatementBatchUid                    int32     `bun:"statement_batch_uid,type:int,default:(1)"`
	AllowAdvanceBilling                  string    `bun:"allow_advance_billing,type:char,default:('N')"`
	AdvanceBillAccountNo                 string    `bun:"advance_bill_account_no,type:varchar(32),nullzero"`
	IncludeNonAllocOnPickTix             int32     `bun:"include_non_alloc_on_pick_tix,type:int,default:(1277)"`
	ExcludeCanceldFromPickTix            string    `bun:"exclude_canceld_from_pick_tix,type:varchar,default:('N')"`
	ExcludeHoldFromPickTix               string    `bun:"exclude_hold_from_pick_tix,type:varchar,default:('N')"`
	ExcludeCanceldFromPackList           string    `bun:"exclude_canceld_from_pack_list,type:varchar,default:('N')"`
	ExcludeHoldFromPackList              string    `bun:"exclude_hold_from_pack_list,type:varchar,default:('N')"`
	ExcludeCanceldFromOrderAck           string    `bun:"exclude_canceld_from_order_ack,type:varchar,default:('N')"`
	ExcludeHoldFromOrderAck              string    `bun:"exclude_hold_from_order_ack,type:varchar,default:('N')"`
	DispAddlInfoOnInvcFlag               string    `bun:"disp_addl_info_on_invc_flag,type:char,nullzero"`
	RemitToAddressId                     float64   `bun:"remit_to_address_id,type:decimal(19,0),nullzero"`
	DefaultBranchId                      string    `bun:"default_branch_id,type:varchar(8),nullzero"`
	CustPartNoGroupHdrUid                int32     `bun:"cust_part_no_group_hdr_uid,type:int,default:(0)"`
	CurrencyId                           float64   `bun:"currency_id,type:decimal(19,0)"`
	OverrideProfitLimit                  string    `bun:"override_profit_limit,type:char,default:('N')"`
	MinimumOrderLineProfit               float64   `bun:"minimum_order_line_profit,type:decimal(19,2),nullzero"`
	MaximumOrderLineProfit               float64   `bun:"maximum_order_line_profit,type:decimal(19,2),nullzero"`
	MinimumOrderProfit                   float64   `bun:"minimum_order_profit,type:decimal(19,2),nullzero"`
	MaximumOrderProfit                   float64   `bun:"maximum_order_profit,type:decimal(19,2),nullzero"`
	DateAcctOpened                       time.Time `bun:"date_acct_opened,type:datetime,nullzero"`
	CreatedBy                            string    `bun:"created_by,type:varchar(255),default:(suser_sname())"`
	IncludeNonAllocOnPackList            int32     `bun:"include_non_alloc_on_pack_list,type:int"`
	PrintPackinglistInShipping           string    `bun:"print_packinglist_in_shipping,type:char,default:('N')"`
	SourceTypeCd                         int32     `bun:"source_type_cd,type:int,nullzero"`
	PricingMethodCdWeb                   int32     `bun:"pricing_method_cd_web,type:int,nullzero"`
	SourcePriceCdWeb                     int32     `bun:"source_price_cd_web,type:int,nullzero"`
	MultiplierWeb                        float64   `bun:"multiplier_web,type:decimal(19,9),nullzero"`
	DefaultOrdersToWillCall              string    `bun:"default_orders_to_will_call,type:char,default:('N')"`
	SendUcc128info                       string    `bun:"send_ucc128info,type:char,nullzero"`
	MfrNo                                string    `bun:"mfr_no,type:varchar(255),nullzero"`
	AlwaysUseJobPrice                    string    `bun:"always_use_job_price,type:char,default:('N')"`
	AllowNonJobItem                      string    `bun:"allow_non_job_item,type:char,default:('N')"`
	PromptForNonJobItem                  string    `bun:"prompt_for_non_job_item,type:char,default:('N')"`
	AllowExceedJobQty                    string    `bun:"allow_exceed_job_qty,type:char,default:('N')"`
	PrintLotAttribOnInvoice              string    `bun:"print_lot_attrib_on_invoice,type:char,default:('N')"`
	PrintLotAttribOnPacklist             string    `bun:"print_lot_attrib_on_packlist,type:char,default:('N')"`
	OverTolerancePercentage              int32     `bun:"over_tolerance_percentage,type:int,nullzero"`
	UnderTolerancePercentage             int32     `bun:"under_tolerance_percentage,type:int,nullzero"`
	CustomerTypeCd                       int32     `bun:"customer_type_cd,type:int,default:(1203)"`
	LeadSourceId                         string    `bun:"lead_source_id,type:varchar(8),nullzero"`
	DataIdentifierGroupUid               int32     `bun:"data_identifier_group_uid,type:int,nullzero"`
	PassportCustomerId                   string    `bun:"passport_customer_id,type:varchar(255),nullzero"`
	CostCenterTrackingOption             int32     `bun:"cost_center_tracking_option,type:int,nullzero"`
	FascorWmsPricingOption               int32     `bun:"fascor_wms_pricing_option,type:int,default:(200)"`
	AllowItemLevelContractFlag           string    `bun:"allow_item_level_contract_flag,type:char,default:('N')"`
	ShipToCreditLimit                    float64   `bun:"ship_to_credit_limit,type:decimal(19,9),default:(0)"`
	LegacyId                             string    `bun:"legacy_id,type:varchar(255),nullzero"`
	ParkerCustomerCd                     string    `bun:"parker_customer_cd,type:varchar(10),nullzero"`
	WebEnabledFlag                       string    `bun:"web_enabled_flag,type:char,default:('N')"`
	AllowLineItemFreightFlag             string    `bun:"allow_line_item_freight_flag,type:char,default:('N')"`
	FreightChargeUid                     int32     `bun:"freight_charge_uid,type:int,nullzero"`
	SendDsc856Flag                       string    `bun:"send_dsc856_flag,type:char,default:('N')"`
	PassThroughOptionFlag                string    `bun:"pass_through_option_flag,type:char,nullzero"`
	EnableBudgetCodesFlag                string    `bun:"enable_budget_codes_flag,type:char,nullzero"`
	EnableAggregateBudgetsFlag           string    `bun:"enable_aggregate_budgets_flag,type:char,nullzero"`
	MaxOrdersPerBudget                   int32     `bun:"max_orders_per_budget,type:int,nullzero"`
	ServiceTermsId                       string    `bun:"service_terms_id,type:varchar(2),nullzero"`
	DownpaymentPercentage                float64   `bun:"downpayment_percentage,type:decimal(19,2),default:((0.00))"`
	ReqPymtUponReleaseOfItems            string    `bun:"req_pymt_upon_release_of_items,type:char,default:('N')"`
	IncludeDpSummaryOnInvoices           string    `bun:"include_dp_summary_on_invoices,type:char,default:('N')"`
	JobNumberRequiredFlag                string    `bun:"job_number_required_flag,type:char,default:('N')"`
	UseLastMarginPricingFlag             string    `bun:"use_last_margin_pricing_flag,type:char,default:('N')"`
	InvoiceCompCostCdTier1               int32     `bun:"invoice_comp_cost_cd_tier1,type:int,default:((2110))"`
	DistrictId                           float64   `bun:"district_id,type:decimal(19,0),nullzero"`
	PreferredFlag                        string    `bun:"preferred_flag,type:char,default:('N')"`
	ApplyFuelSurchargesCd                int32     `bun:"apply_fuel_surcharges_cd,type:int,nullzero"`
	AppliedFuelchargesToDsFlag           string    `bun:"applied_fuelcharges_to_ds_flag,type:char,nullzero"`
	SuppressZeroDollarFlag               string    `bun:"suppress_zero_dollar_flag,type:char,nullzero"`
	InvoiceCompCostCdTier2               int32     `bun:"invoice_comp_cost_cd_tier2,type:int,default:((2111))"`
	InvoiceCompCostCdTier3               int32     `bun:"invoice_comp_cost_cd_tier3,type:int,default:((1195))"`
	SignatureRequiredFlag                string    `bun:"signature_required_flag,type:char,default:('N')"`
	PromiseDateBuffer                    int32     `bun:"promise_date_buffer,type:int,nullzero"`
	DaysUntilQuoteExpires                int32     `bun:"days_until_quote_expires,type:int,nullzero"`
	ReclaimDiscountOnMemosFlag           string    `bun:"reclaim_discount_on_memos_flag,type:char,nullzero"`
	OrderSurchargeUid                    int32     `bun:"order_surcharge_uid,type:int,nullzero"`
	SplitCoresFlag                       string    `bun:"split_cores_flag,type:char,nullzero"`
	SalesrepAssignedDate                 time.Time `bun:"salesrep_assigned_date,type:datetime,nullzero"`
	ClockCellTrackingFlag                string    `bun:"clock_cell_tracking_flag,type:char,default:('N')"`
	EnvironmentalFeeFlag                 string    `bun:"environmental_fee_flag,type:char,default:('N')"`
	AdminFeeFlag                         string    `bun:"admin_fee_flag,type:char,default:('N')"`
	EpaCertOnFileFlag                    string    `bun:"epa_cert_on_file_flag,type:char,default:('N')"`
	OrderDiscType                        int32     `bun:"order_disc_type,type:int,nullzero"`
	OrderDiscFactor                      float64   `bun:"order_disc_factor,type:decimal(19,9),nullzero"`
	UseVendorContractsFlag               string    `bun:"use_vendor_contracts_flag,type:char,default:('N')"`
	PedigreeCustomer                     string    `bun:"pedigree_customer,type:char,default:('N')"`
	NationalAccountFlag                  string    `bun:"national_account_flag,type:char,nullzero"`
	FreightMarkupMultiplier              float64   `bun:"freight_markup_multiplier,type:decimal(19,9),nullzero"`
	OrderPriorityUid                     int32     `bun:"order_priority_uid,type:int,nullzero"`
	ManufacturerDistributorNo            string    `bun:"manufacturer_distributor_no,type:varchar(255),nullzero"`
	ManufacturerProgramTypePct           float64   `bun:"manufacturer_program_type_pct,type:decimal(19,2),nullzero"`
	ManufacturerRebateLoc                string    `bun:"manufacturer_rebate_loc,type:varchar(255),nullzero"`
	FloorPlanTaxableFlag                 string    `bun:"floor_plan_taxable_flag,type:char,nullzero"`
	UseVendorItemTermsFlag               string    `bun:"use_vendor_item_terms_flag,type:char,nullzero"`
	RentalUpdateFlag                     string    `bun:"rental_update_flag,type:char,nullzero"`
	ForeignCurrencyGuaranteeType         string    `bun:"foreign_currency_guarantee_type,type:char,nullzero"`
	SalesMarketGroupUid                  int32     `bun:"sales_market_group_uid,type:int,nullzero"`
	SpecialLabelingFlag                  string    `bun:"special_labeling_flag,type:char,default:('N')"`
	SpecialPackagingFlag                 string    `bun:"special_packaging_flag,type:char,default:('N')"`
	SfdcAccountId                        string    `bun:"sfdc_account_id,type:varchar(255),nullzero"`
	SfdcCreateDate                       time.Time `bun:"sfdc_create_date,type:datetime,nullzero"`
	SfdcUpdateDate                       time.Time `bun:"sfdc_update_date,type:datetime,nullzero"`
	UseSysUpsHandlingChrgFlag            string    `bun:"use_sys_ups_handling_chrg_flag,type:varchar,default:('Y')"`
	UpsHandlingCharge                    float64   `bun:"ups_handling_charge,type:decimal(19,2),default:((0.00))"`
	PrintPickFeeFlag                     string    `bun:"print_pick_fee_flag,type:char,nullzero"`
	Zoom360Grade                         string    `bun:"zoom360_grade,type:varchar(255),nullzero"`
	Zoom360GradeExpirationDate           time.Time `bun:"zoom360_grade_expiration_date,type:datetime,nullzero"`
	PriceLabelFlag                       string    `bun:"price_label_flag,type:char,default:('N')"`
	PrintCompleteOrdersFlag              string    `bun:"print_complete_orders_flag,type:char,nullzero"`
	BuyListHdrUid                        int32     `bun:"buy_list_hdr_uid,type:int,nullzero"`
	DaysOverdueForCreditHold             int32     `bun:"days_overdue_for_credit_hold,type:int,nullzero"`
	GlCodeListHdrUid                     int32     `bun:"gl_code_list_hdr_uid,type:int,nullzero"`
	CmiCustomerNote                      string    `bun:"cmi_customer_note,type:varchar(8000),nullzero"`
	RmaRevenueAccountNo                  string    `bun:"rma_revenue_account_no,type:varchar(32),nullzero"`
	SoPoNoRequiredFlag                   string    `bun:"so_po_no_required_flag,type:char,default:('N')"`
	ArBatchType                          string    `bun:"ar_batch_type,type:char,default:('C')"`
	UseIntAddressFormatFlag              string    `bun:"use_int_address_format_flag,type:char,default:('N')"`
	GlCodeOverrideFlag                   string    `bun:"gl_code_override_flag,type:char,default:('N')"`
	Ucc128FormFilename                   string    `bun:"ucc128_form_filename,type:varchar(255),nullzero"`
	LowestAcrossLibrariesFlag            string    `bun:"lowest_across_libraries_flag,type:char,default:('N')"`
	PriceRoundingFlag                    string    `bun:"price_rounding_flag,type:char,default:('N')"`
	DealerWrrtyClaimsAccountNo           string    `bun:"dealer_wrrty_claims_account_no,type:varchar(32),nullzero"`
	IncludeAgingInfoOnInvoiceFlag        string    `bun:"include_aging_info_on_invoice_flag,type:char,nullzero"`
	DecimalPrecisionPrice                int32     `bun:"decimal_precision_price,type:int,nullzero"`
	PrivateLabelFlag                     string    `bun:"private_label_flag,type:char,nullzero"`
	CfnCostGoodsSoldAccount              string    `bun:"cfn_cost_goods_sold_account,type:varchar(32),nullzero"`
	CfnReceivableAccount                 string    `bun:"cfn_receivable_account,type:varchar(32),nullzero"`
	CfnRevenueAccount                    string    `bun:"cfn_revenue_account,type:varchar(32),nullzero"`
	ServicebenchServicerNo               string    `bun:"servicebench_servicer_no,type:varchar(255),nullzero"`
	ApplyConvenienceFeeFlag              string    `bun:"apply_convenience_fee_flag,type:char,default:('N')"`
	DefaultKitMarkupPercent              float64   `bun:"default_kit_markup_percent,type:decimal(19,9),nullzero"`
	FiscalYearStartMonth                 int16     `bun:"fiscal_year_start_month,type:smallint,nullzero"`
	SalesTaxPayableAccountNo             string    `bun:"sales_tax_payable_account_no,type:varchar(255),nullzero"`
	CustomerTaxClass                     string    `bun:"customer_tax_class,type:varchar(255),nullzero"`
	ConsBackordersFlag                   string    `bun:"cons_backorders_flag,type:char,nullzero"`
	ImportPriceTolerance                 float64   `bun:"import_price_tolerance,type:decimal(19,9),default:((0))"`
	ServicebenchAltServicerNo            string    `bun:"servicebench_alt_servicer_no,type:varchar(255),nullzero"`
	AlwaysUseEftPaymentFlag              string    `bun:"always_use_eft_payment_flag,type:char,nullzero"`
	EftValidationSentFlag                string    `bun:"eft_validation_sent_flag,type:char,nullzero"`
	ScheduledOrderDiscount               float64   `bun:"scheduled_order_discount,type:decimal(19,9),nullzero"`
	WillCallDiscount                     float64   `bun:"will_call_discount,type:decimal(19,9),nullzero"`
	FreightThreshold                     float64   `bun:"freight_threshold,type:decimal(19,9),nullzero"`
	PartnerProgramUid                    int32     `bun:"partner_program_uid,type:int,nullzero"`
	PlaceOrdersOnHold                    string    `bun:"place_orders_on_hold,type:char,nullzero"`
	OrderHoldClassId                     string    `bun:"order_hold_class_id,type:varchar(255),nullzero"`
	DuplicatePoNo                        string    `bun:"duplicate_po_no,type:char,nullzero"`
	FormsOutputPrintFlag                 string    `bun:"forms_output_print_flag,type:char,nullzero"`
	FormsOutputEmailFlag                 string    `bun:"forms_output_email_flag,type:char,nullzero"`
	FormsOutputFaxFlag                   string    `bun:"forms_output_fax_flag,type:char,nullzero"`
	CustomerConsolidationMethod          int32     `bun:"customer_consolidation_method,type:int,nullzero"`
	ConsolidatePerOrder                  string    `bun:"consolidate_per_order,type:char,nullzero"`
	Edi846pasReferenceNo                 int32     `bun:"edi846pas_reference_no,type:int,nullzero"`
	PurchasingContactId                  string    `bun:"purchasing_contact_id,type:varchar(16),nullzero"`
	CustomerDiscPct                      float64   `bun:"customer_disc_pct,type:decimal(19,9),nullzero"`
	HoldInvoiceFlag                      string    `bun:"hold_invoice_flag,type:char,default:('N')"`
	GenerateInvoicesBy                   int16     `bun:"generate_invoices_by,type:smallint,default:((1005))"`
	VendorId                             float64   `bun:"vendor_id,type:decimal(19,0),nullzero"`
	CourtesyPastDueFlag                  string    `bun:"courtesy_past_due_flag,type:char,default:('Y')"`
	GenericDescOnPackinglistFlag         string    `bun:"generic_desc_on_packinglist_flag,type:char,nullzero"`
	GenericDescOnInvoiceAckFlag          string    `bun:"generic_desc_on_invoice_ack_flag,type:char,nullzero"`
	TrackCustomerPackageFlag             string    `bun:"track_customer_package_flag,type:char,nullzero"`
	AutoSubstituteItemsFlag              string    `bun:"auto_substitute_items_flag,type:char,nullzero"`
	FillOrKillFlag                       string    `bun:"fill_or_kill_flag,type:char,nullzero"`
	PreventDcSwitchingFlag               string    `bun:"prevent_dc_switching_flag,type:char,default:('N')"`
	BypassDefItemUomFlag                 string    `bun:"bypass_def_item_uom_flag,type:char,default:('N')"`
	DiscountItemId                       string    `bun:"discount_item_id,type:varchar(255),nullzero"`
	DeliveryChargeInvMastUid             int32     `bun:"delivery_charge_inv_mast_uid,type:int,nullzero"`
	IndividualInvoiceFlag                string    `bun:"individual_invoice_flag,type:char,nullzero"`
	CustomerUid                          int32     `bun:"customer_uid,type:int,identity"`
	MultCustPartNoGroupFlag              string    `bun:"mult_cust_part_no_group_flag,type:char,nullzero"`
	MarketingAllowancePercentage         float64   `bun:"marketing_allowance_percentage,type:decimal(19,9),nullzero"`
	AdAllowancePercentage                float64   `bun:"ad_allowance_percentage,type:decimal(19,9),nullzero"`
	DiscountPercentage                   float64   `bun:"discount_percentage,type:decimal(19,9),nullzero"`
	DiscountGlAccountNo                  string    `bun:"discount_gl_account_no,type:varchar(32),nullzero"`
	ValidateOeImportPricingFlag          string    `bun:"validate_oe_import_pricing_flag,type:char,nullzero"`
	RecordUsageActualLocFlag             string    `bun:"record_usage_actual_loc_flag,type:char,nullzero"`
	StmtFormsOutputPrintFlag             string    `bun:"stmt_forms_output_print_flag,type:char,nullzero"`
	StmtFormsOutputEmailFlag             string    `bun:"stmt_forms_output_email_flag,type:char,nullzero"`
	StmtFormsOutputFaxFlag               string    `bun:"stmt_forms_output_fax_flag,type:char,nullzero"`
	GenPastDueStmtFlag                   string    `bun:"gen_past_due_stmt_flag,type:char,nullzero"`
	PdsFormsOutputPrintFlag              string    `bun:"pds_forms_output_print_flag,type:char,nullzero"`
	PdsFormsOutputEmailFlag              string    `bun:"pds_forms_output_email_flag,type:char,nullzero"`
	PdsFormsOutputFaxFlag                string    `bun:"pds_forms_output_fax_flag,type:char,nullzero"`
	ShippingRecalcPriceFlag              string    `bun:"shipping_recalc_price_flag,type:char,default:('N')"`
	CalculateCanadianCommFlag            string    `bun:"calculate_canadian_comm_flag,type:char,nullzero"`
	ElectronicOrderDiscountIgnoreOverdue string    `bun:"electronic_order_discount_ignore_overdue,type:char,nullzero"`
	UsePalletLabels                      string    `bun:"use_pallet_labels,type:varchar,nullzero"`
	ConsolidatedAsnFlag                  string    `bun:"consolidated_asn_flag,type:char,default:('N')"`
	StartConsolidationDate               time.Time `bun:"start_consolidation_date,type:datetime,nullzero"`
	AllowAutoApplyOrigInv                string    `bun:"allow_auto_apply_orig_inv,type:char,nullzero"`
	DrumDepositFlag                      string    `bun:"drum_deposit_flag,type:char,nullzero"`
	MultiplierPriceLibrary               float64   `bun:"multiplier_price_library,type:decimal(19,9),nullzero"`
	CompleteLotsFlag                     string    `bun:"complete_lots_flag,type:char,nullzero"`
	WeightPerBox                         float64   `bun:"weight_per_box,type:decimal(19,9),nullzero"`
	DoNotChgOeLocToReplenFlag            string    `bun:"do_not_chg_oe_loc_to_replen_flag,type:char,nullzero"`
	NatlAcctPricingEligibleFlag          string    `bun:"natl_acct_pricing_eligible_flag,type:char,default:('N')"`
	ServiceLevelAgreementUid             int32     `bun:"service_level_agreement_uid,type:int,nullzero"`
	DistributorCode                      string    `bun:"distributor_code,type:varchar(255),nullzero"`
	ReqSuppOrderNoForDispatch            string    `bun:"req_supp_order_no_for_dispatch,type:char,nullzero"`
	GlAppliedLaborAcct                   string    `bun:"gl_applied_labor_acct,type:varchar(32),nullzero"`
	GlLaborCosAcct                       string    `bun:"gl_labor_cos_acct,type:varchar(32),nullzero"`
	GlServiceCosAcct                     string    `bun:"gl_service_cos_acct,type:varchar(32),nullzero"`
	GlServiceRevenueAcct                 string    `bun:"gl_service_revenue_acct,type:varchar(32),nullzero"`
	FreightDiscountAcct                  string    `bun:"freight_discount_acct,type:varchar(32),nullzero"`
	WtyClaimApprCreditThreshold          float64   `bun:"wty_claim_appr_credit_threshold,type:decimal(19,9),nullzero"`
	PrntCartonLabelAfterFinalPkgFlag     string    `bun:"prnt_carton_label_after_final_pkg_flag,type:char,default:('N')"`
	PrntShippingLblAfterFinalPkgFlag     string    `bun:"prnt_shipping_lbl_after_final_pkg_flag,type:char,default:('N')"`
	PrntUcc128LabelAfterFinalPkgFlag     string    `bun:"prnt_ucc128_label_after_final_pkg_flag,type:char,default:('N')"`
	UseScanPackFlag                      string    `bun:"use_scan_pack_flag,type:char,default:('Y')"`
	ExcludeFromExternalTaxCalc           string    `bun:"exclude_from_external_tax_calc,type:char,nullzero"`
	AdvancedBillingFlag                  string    `bun:"advanced_billing_flag,type:char,nullzero"`
	ConsolidatedInvoicingTypeCd          int32     `bun:"consolidated_invoicing_type_cd,type:int,nullzero"`
	AsnByJobContractLineFlag             string    `bun:"asn_by_job_contract_line_flag,type:char,nullzero"`
	Edi832LastFullRunDate                time.Time `bun:"edi832_last_full_run_date,type:datetime,nullzero"`
	OverrideFcPriceConversionFlag        string    `bun:"override_fc_price_conversion_flag,type:char,nullzero"`
	OverrideFcReceiptDefaults            string    `bun:"override_fc_receipt_defaults,type:char,default:('N')"`
	FcReceiptDefaultPrint                string    `bun:"fc_receipt_default_print,type:char,default:('N')"`
	FcReceiptDefaultEmail                string    `bun:"fc_receipt_default_email,type:char,default:('N')"`
	FcReceiptDefaultUnpriced             string    `bun:"fc_receipt_default_unpriced,type:char,default:('N')"`
	FcReceiptDefaultSkinny               string    `bun:"fc_receipt_default_skinny,type:char,default:('N')"`
	LegalName                            string    `bun:"legal_name,type:varchar(255),nullzero"`
}
