package model

type InvLoc struct {
	bun.BaseModel                   `bun:"table:inv_loc"`
	LocationId                      float64   `bun:"location_id,type:decimal(19,0),pk"`
	QtyOnHand                       float64   `bun:"qty_on_hand,type:decimal(19,9),default:(0)"`
	QtyInProcess                    float64   `bun:"qty_in_process,type:decimal(19,9),default:(0)"`
	DateCreated                     time.Time `bun:"date_created,type:datetime"`
	DateLastModified                time.Time `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy                string    `bun:"last_maintained_by,type:varchar(30),default:(user_name())"`
	CompanyId                       string    `bun:"company_id,type:varchar(8),pk"`
	LastRecPo                       float64   `bun:"last_rec_po,type:decimal(19,9),nullzero"`
	LastRecPoWithDisc               float64   `bun:"last_rec_po_with_disc,type:decimal(19,9),nullzero"`
	GlAccountNo                     string    `bun:"gl_account_no,type:varchar(32),nullzero"`
	PurchOrTransfer                 string    `bun:"purch_or_transfer,type:char,nullzero"`
	NextDueInPoCost                 float64   `bun:"next_due_in_po_cost,type:decimal(19,9),nullzero"`
	NextDueInPoDate                 time.Time `bun:"next_due_in_po_date,type:datetime,nullzero"`
	RevenueAccountNo                string    `bun:"revenue_account_no,type:varchar(32),nullzero"`
	CosAccountNo                    string    `bun:"cos_account_no,type:varchar(32),nullzero"`
	Sellable                        string    `bun:"sellable,type:char,nullzero"`
	MovingAverageCost               float64   `bun:"moving_average_cost,type:decimal(19,9),nullzero"`
	StandardCost                    float64   `bun:"standard_cost,type:decimal(19,9),nullzero"`
	ProtectedStockQty               float64   `bun:"protected_stock_qty,type:decimal(19,9),nullzero"`
	InvMin                          float64   `bun:"inv_min,type:decimal(19,9),nullzero"`
	InvMax                          float64   `bun:"inv_max,type:decimal(19,9),nullzero"`
	SafetyStock                     float64   `bun:"safety_stock,type:decimal(19,9),nullzero"`
	Stockable                       string    `bun:"stockable,type:char,nullzero"`
	ReplenishmentLocation           float64   `bun:"replenishment_location,type:decimal(19,0),nullzero"`
	MonthsInSeason                  float64   `bun:"months_in_season,type:decimal(2,0),nullzero"`
	AverageMonthlyUsage             float64   `bun:"average_monthly_usage,type:decimal(19,9),nullzero"`
	ProductGroupId                  string    `bun:"product_group_id,type:varchar(8),nullzero"`
	PurchaseClass                   string    `bun:"purchase_class,type:varchar(8),nullzero"`
	CycleCountingCategory           float64   `bun:"cycle_counting_category,type:decimal(19,0),nullzero"`
	PurchaseDiscountGroup           string    `bun:"purchase_discount_group,type:varchar(8),nullzero"`
	SalesDiscountGroup              string    `bun:"sales_discount_group,type:varchar(8),nullzero"`
	NoCharge                        string    `bun:"no_charge,type:char,nullzero"`
	Price1                          float64   `bun:"price1,type:decimal(19,9),nullzero"`
	Price2                          float64   `bun:"price2,type:decimal(19,9),nullzero"`
	Price3                          float64   `bun:"price3,type:decimal(19,9),nullzero"`
	Price4                          float64   `bun:"price4,type:decimal(19,9),nullzero"`
	Price5                          float64   `bun:"price5,type:decimal(19,9),nullzero"`
	Price6                          float64   `bun:"price6,type:decimal(19,9),nullzero"`
	Price7                          float64   `bun:"price7,type:decimal(19,9),nullzero"`
	Price8                          float64   `bun:"price8,type:decimal(19,9),nullzero"`
	Price9                          float64   `bun:"price9,type:decimal(19,9),nullzero"`
	Price10                         float64   `bun:"price10,type:decimal(19,9),nullzero"`
	ReplenishmentMethod             string    `bun:"replenishment_method,type:varchar(8),nullzero"`
	OrderQuantity                   float64   `bun:"order_quantity,type:decimal(19,9),default:(0)"`
	QtyAllocated                    float64   `bun:"qty_allocated,type:decimal(19,9),default:(0)"`
	QtyBackordered                  float64   `bun:"qty_backordered,type:decimal(19,9),default:(0)"`
	QtyInTransit                    float64   `bun:"qty_in_transit,type:decimal(19,9),default:(0)"`
	TrackBins                       string    `bun:"track_bins,type:char,nullzero"`
	DefaultInOe                     string    `bun:"default_in_oe,type:char,nullzero"`
	PeriodFirstStocked              float64   `bun:"period_first_stocked,type:decimal(3,0),nullzero"`
	YearFirstStocked                float64   `bun:"year_first_stocked,type:decimal(4,0),nullzero"`
	UsageLock                       string    `bun:"usage_lock,type:char,nullzero"`
	UsageLockPeriod                 float64   `bun:"usage_lock_period,type:decimal(3,0),nullzero"`
	UsageLockYear                   float64   `bun:"usage_lock_year,type:decimal(4,0),nullzero"`
	PrimaryBin                      string    `bun:"primary_bin,type:varchar(10),nullzero"`
	TaxGroupId                      string    `bun:"tax_group_id,type:varchar(10),nullzero"`
	QtyReservedDueIn                float64   `bun:"qty_reserved_due_in,type:decimal(19,9),default:(0)"`
	DateLastCounted                 string    `bun:"date_last_counted,type:smalldatetime,nullzero"`
	InvMastUid                      int32     `bun:"inv_mast_uid,type:int,pk"`
	Requisition                     string    `bun:"requisition,type:char,default:('N')"`
	DeadstockFlag                   string    `bun:"deadstock_flag,type:char,default:('N')"`
	LotBinIntegration               string    `bun:"lot_bin_integration,type:char,nullzero"`
	AddToCycleCount                 string    `bun:"add_to_cycle_count,type:char,default:('N')"`
	DefaultShipment                 int32     `bun:"default_shipment,type:int,default:(1138)"`
	PrimarySupplierId               float64   `bun:"primary_supplier_id,type:decimal(19,0),nullzero"`
	OnObtFlag                       string    `bun:"on_obt_flag,type:char,default:('N')"`
	OnReleaseScheduleFlag           string    `bun:"on_release_schedule_flag,type:char,default:('N')"`
	OnBackorderFlag                 string    `bun:"on_backorder_flag,type:char,default:('N')"`
	LastSaleDate                    time.Time `bun:"last_sale_date,type:datetime,default:('01/01/1990')"`
	LastPurchaseDate                time.Time `bun:"last_purchase_date,type:datetime,nullzero"`
	Buy                             string    `bun:"buy,type:char,default:('Y')"`
	Make                            string    `bun:"make,type:char,default:('N')"`
	CreatedBy                       string    `bun:"created_by,type:varchar(255),default:(suser_sname())"`
	PeriodsToSupplyMin              int16     `bun:"periods_to_supply_min,type:tinyint,default:(0)"`
	PeriodsToSupplyMax              int16     `bun:"periods_to_supply_max,type:tinyint,default:(0)"`
	PutawayRank                     string    `bun:"putaway_rank,type:varchar(8),nullzero"`
	InvLastChangedDate              time.Time `bun:"inv_last_changed_date,type:datetime,nullzero"`
	IvaTaxableFlag                  string    `bun:"iva_taxable_flag,type:char,nullzero"`
	ItemPutawayAttributeUid         int32     `bun:"item_putaway_attribute_uid,type:int,nullzero"`
	SplittableFlag                  string    `bun:"splittable_flag,type:char,nullzero"`
	MinReplenishmentQty             float64   `bun:"min_replenishment_qty,type:decimal(19,9),nullzero"`
	Discontinued                    string    `bun:"discontinued,type:char,default:('N')"`
	AllowDsDiscontinuedItems        string    `bun:"allow_ds_discontinued_items,type:char,default:('N')"`
	AllowSpDiscontinuedItems        string    `bun:"allow_sp_discontinued_items,type:char,default:('N')"`
	SafetyStockType                 int32     `bun:"safety_stock_type,type:int,nullzero"`
	ServiceLevelMeasure             int32     `bun:"service_level_measure,type:int,nullzero"`
	ServiceLevelPctGoal             float64   `bun:"service_level_pct_goal,type:decimal(19,2),nullzero"`
	DemandPatternCd                 int32     `bun:"demand_pattern_cd,type:int,nullzero"`
	DemandPatternEvaluationDate     time.Time `bun:"demand_pattern_evaluation_date,type:datetime,nullzero"`
	DemandForecastFormulaUid        int32     `bun:"demand_forecast_formula_uid,type:int,nullzero"`
	PatternManuallyEditedFlag       string    `bun:"pattern_manually_edited_flag,type:char,nullzero"`
	DemandPatternBehaviorCd         int32     `bun:"demand_pattern_behavior_cd,type:int,nullzero"`
	PatternLikeInvMastUid           int32     `bun:"pattern_like_inv_mast_uid,type:int,nullzero"`
	PatternLikeLocationId           float64   `bun:"pattern_like_location_id,type:decimal(19,0),nullzero"`
	BehavesLikeLockFlag             string    `bun:"behaves_like_lock_flag,type:char,nullzero"`
	BehavesLikeLockPeriod           int32     `bun:"behaves_like_lock_period,type:int,nullzero"`
	BehavesLikeLockYear             int32     `bun:"behaves_like_lock_year,type:int,nullzero"`
	LandedCostAccountNo             string    `bun:"landed_cost_account_no,type:varchar(255),nullzero"`
	PriceFamilyUid                  int32     `bun:"price_family_uid,type:int,nullzero"`
	DeleteFlag                      string    `bun:"delete_flag,type:char,nullzero"`
	CardlockProductId               string    `bun:"cardlock_product_id,type:varchar(255),nullzero"`
	DefaultSellingUnit              string    `bun:"default_selling_unit,type:varchar(8),nullzero"`
	LocItemTypeCd                   int32     `bun:"loc_item_type_cd,type:int,nullzero"`
	LocCustParentInvMastUid         int32     `bun:"loc_cust_parent_inv_mast_uid,type:int,nullzero"`
	MainBulkLocationFlag            string    `bun:"main_bulk_location_flag,type:char,nullzero"`
	DfltSourceLocFlag               string    `bun:"dflt_source_loc_flag,type:char,nullzero"`
	CycleCountFlag                  string    `bun:"cycle_count_flag,type:char,nullzero"`
	PromotionalFlag                 string    `bun:"promotional_flag,type:char,nullzero"`
	RmaRevenueAccountNo             string    `bun:"rma_revenue_account_no,type:varchar(32),nullzero"`
	FutureStandardCost              float64   `bun:"future_standard_cost,type:decimal(19,9),nullzero"`
	EffectiveDate                   time.Time `bun:"effective_date,type:datetime,nullzero"`
	AssemblyPromptOption            int32     `bun:"assembly_prompt_option,type:int,nullzero"`
	RestrictedFlag                  string    `bun:"restricted_flag,type:char,nullzero"`
	DrpItemFlag                     string    `bun:"drp_item_flag,type:char,default:('N')"`
	SavedDemandForecastFormulaUid   int32     `bun:"saved_demand_forecast_formula_uid,type:int,nullzero"`
	DemandFormulaComputedYearPeriod int32     `bun:"demand_formula_computed_year_period,type:int,nullzero"`
	DemandPatternComputedYearPeriod int32     `bun:"demand_pattern_computed_year_period,type:int,nullzero"`
	YearPeriodLastForecast          int32     `bun:"year_period_last_forecast,type:int,nullzero"`
	VendorRebateAccountNo           string    `bun:"vendor_rebate_account_no,type:varchar(32),nullzero"`
	TransferUsagePercent            float64   `bun:"transfer_usage_percent,type:decimal(19,9),nullzero"`
	ManufacturerReqStockFlag        string    `bun:"manufacturer_req_stock_flag,type:char,default:('N')"`
	FcBin                           string    `bun:"fc_bin,type:varchar(10),nullzero"`
	PumpoffItem                     string    `bun:"pumpoff_item,type:varchar(40),nullzero"`
	PumpoffUom                      string    `bun:"pumpoff_uom,type:varchar(8),nullzero"`
	OnFutureOrderFlag               string    `bun:"on_future_order_flag,type:char,default:('N')"`
	OnFutureProdOrderFlag           string    `bun:"on_future_prod_order_flag,type:char,default:('N')"`
	MaxLiability                    float64   `bun:"max_liability,type:decimal(19,9),nullzero"`
	MaxTransferQty                  float64   `bun:"max_transfer_qty,type:decimal(19,9),nullzero"`
	AltTaxGroupId                   string    `bun:"alt_tax_group_id,type:varchar(10),nullzero"`
	ReturnableFlag                  string    `bun:"returnable_flag,type:char,default:('Y')"`
	IqsItemFlag                     string    `bun:"iqs_item_flag,type:char,nullzero"`
	SlabTrackBinsFlag               string    `bun:"slab_track_bins_flag,type:char,nullzero"`
	Edi832DiscontinuedSentFlag      string    `bun:"edi_832_discontinued_sent_flag,type:char,nullzero"`
	BuyerId                         string    `bun:"buyer_id,type:varchar(16),nullzero"`
	TaRentalRevenueAccountNo        string    `bun:"ta_rental_revenue_account_no,type:varchar(32),nullzero"`
	CycleCountNo                    float64   `bun:"cycle_count_no,type:decimal(19,0),nullzero"`
	CycleCountQty                   float64   `bun:"cycle_count_qty,type:decimal(19,9),nullzero"`
	TaRentalTaxGroupId              string    `bun:"ta_rental_tax_group_id,type:varchar(10),nullzero"`
	TransferConversionUom           string    `bun:"transfer_conversion_uom,type:varchar(8),nullzero"`
	EccEnabledFlag                  string    `bun:"ecc_enabled_flag,type:char,default:('N')"`
	InvMastUidDupUsage              int32     `bun:"inv_mast_uid_dup_usage,type:int,nullzero"`
	TransferOrderPoint              float64   `bun:"transfer_order_point,type:decimal(19,9),nullzero"`
	TransferOrderQty                float64   `bun:"transfer_order_qty,type:decimal(19,9),nullzero"`
	OsmiItemFlag                    string    `bun:"osmi_item_flag,type:char,default:('N')"`
	LocalItemFlag                   string    `bun:"local_item_flag,type:char,default:('N')"`
	CriticalItemFlag                string    `bun:"critical_item_flag,type:char,nullzero"`
	DeviationLookbackPds            int32     `bun:"deviation_lookback_pds,type:int,nullzero"`
	DeviationMultOnePd              float64   `bun:"deviation_mult_one_pd,type:decimal(19,9),nullzero"`
	DeviationMultTwoPd              float64   `bun:"deviation_mult_two_pd,type:decimal(19,9),nullzero"`
	DeviationMultThreePd            float64   `bun:"deviation_mult_three_pd,type:decimal(19,9),nullzero"`
	MinSafetyStockDays              float64   `bun:"min_safety_stock_days,type:decimal(19,9),nullzero"`
	MaxSafetyStockDays              float64   `bun:"max_safety_stock_days,type:decimal(19,9),nullzero"`
	CritItemDeviationMult           float64   `bun:"crit_item_deviation_mult,type:decimal(19,9),nullzero"`
	CritMinSafetyStockDays          float64   `bun:"crit_min_safety_stock_days,type:decimal(19,9),nullzero"`
	CritMaxSafetyStockDays          float64   `bun:"crit_max_safety_stock_days,type:decimal(19,9),nullzero"`
}
