package model

import (
	"github.com/uptrace/bun"
	"time"
)

type InvMast struct {
	bun.BaseModel                 `bun:"table:inv_mast"`
	InvMastUid                    int32     `bun:"inv_mast_uid,type:int,pk"`
	ItemId                        string    `bun:"item_id,type:varchar(40)"`
	ItemDesc                      string    `bun:"item_desc,type:varchar(40)"`
	DeleteFlag                    string    `bun:"delete_flag,type:char"`
	Weight                        float64   `bun:"weight,type:decimal(19,12),nullzero"`
	NetWeight                     float64   `bun:"net_weight,type:decimal(19,12),nullzero"`
	DateCreated                   time.Time `bun:"date_created,type:datetime"`
	DateLastModified              time.Time `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy              string    `bun:"last_maintained_by,type:varchar(30),default:(user_name())"`
	Inactive                      string    `bun:"inactive,type:char"`
	Cube                          float64   `bun:"cube,type:decimal(19,12),nullzero"`
	DateInactive                  time.Time `bun:"date_inactive,type:datetime,nullzero"`
	DateReactive                  time.Time `bun:"date_reactive,type:datetime,nullzero"`
	CatchWeightIndicator          string    `bun:"catch_weight_indicator,type:char"`
	PurchasingWeight              float64   `bun:"purchasing_weight,type:decimal(19,12),nullzero"`
	ClassId1                      string    `bun:"class_id1,type:varchar(255),nullzero"`
	ClassId2                      string    `bun:"class_id2,type:varchar(255),nullzero"`
	ClassId3                      string    `bun:"class_id3,type:varchar(255),nullzero"`
	ClassId4                      string    `bun:"class_id4,type:varchar(255),nullzero"`
	ClassId5                      string    `bun:"class_id5,type:varchar(255),nullzero"`
	UpcOrEan                      string    `bun:"upc_or_ean,type:varchar(3),nullzero"`
	UpcOrEanId                    string    `bun:"upc_or_ean_id,type:varchar(15),nullzero"`
	Serialized                    string    `bun:"serialized,type:char"`
	ProductType                   string    `bun:"product_type,type:char"`
	Hose                          string    `bun:"hose,type:char"`
	Fitting                       string    `bun:"fitting,type:char"`
	DLength                       float64   `bun:"d_length,type:decimal(6,4),nullzero"`
	CatalogItem                   string    `bun:"catalog_item,type:char"`
	ShortCode                     string    `bun:"short_code,type:varchar(30),nullzero"`
	TrackLots                     string    `bun:"track_lots,type:char"`
	Requisition                   string    `bun:"requisition,type:char,default:('N')"`
	Price1                        float64   `bun:"price1,type:decimal(19,9),nullzero"`
	Price2                        float64   `bun:"price2,type:decimal(19,9),nullzero"`
	Price3                        float64   `bun:"price3,type:decimal(19,9),nullzero"`
	Price4                        float64   `bun:"price4,type:decimal(19,9),nullzero"`
	Price5                        float64   `bun:"price5,type:decimal(19,9),nullzero"`
	Price6                        float64   `bun:"price6,type:decimal(19,9),nullzero"`
	Price7                        float64   `bun:"price7,type:decimal(19,9),nullzero"`
	Price8                        float64   `bun:"price8,type:decimal(19,9),nullzero"`
	Price9                        float64   `bun:"price9,type:decimal(19,9),nullzero"`
	Price10                       float64   `bun:"price10,type:decimal(19,9),nullzero"`
	DefaultProductGroup           string    `bun:"default_product_group,type:varchar(8),nullzero"`
	DefaultSalesDiscountGroup     string    `bun:"default_sales_discount_group,type:varchar(8),nullzero"`
	DefaultPurchaseDiscGroup      string    `bun:"default_purchase_disc_group,type:varchar(8),nullzero"`
	SalesPricingUnit              string    `bun:"sales_pricing_unit,type:varchar(8),nullzero"`
	SalesPricingUnitSize          float64   `bun:"sales_pricing_unit_size,type:decimal(19,4),nullzero"`
	PurchasePricingUnit           string    `bun:"purchase_pricing_unit,type:varchar(8),nullzero"`
	PurchasePricingUnitSize       float64   `bun:"purchase_pricing_unit_size,type:decimal(19,4),nullzero"`
	ExtendedDesc                  string    `bun:"extended_desc,type:varchar(255),nullzero"`
	CommissionClassId             string    `bun:"commission_class_id,type:varchar(8),nullzero"`
	OtherChargeItem               string    `bun:"other_charge_item,type:char,nullzero"`
	InvoiceType                   string    `bun:"invoice_type,type:varchar(2),nullzero"`
	PickTicketType                string    `bun:"pick_ticket_type,type:varchar(2),nullzero"`
	DefaultSellingUnit            string    `bun:"default_selling_unit,type:varchar(8),nullzero"`
	UpdateViaPricingService       string    `bun:"update_via_pricing_service,type:char,nullzero"`
	DefaultPurchasingUnit         string    `bun:"default_purchasing_unit,type:varchar(8),nullzero"`
	Hi                            float64   `bun:"hi,type:decimal(6,0),nullzero"`
	Ti                            float64   `bun:"ti,type:decimal(6,0),nullzero"`
	ConvertQuantities             string    `bun:"convert_quantities,type:char,nullzero"`
	HazMatFlag                    string    `bun:"haz_mat_flag,type:char,default:('N')"`
	ClassCode                     float64   `bun:"class_code,type:decimal(6,2),nullzero"`
	ItemTermsDiscountPct          float64   `bun:"item_terms_discount_pct,type:decimal(19,2),default:(0)"`
	TpcxStatus                    int32     `bun:"tpcx_status,type:int,nullzero"`
	DefaultTransferUnit           string    `bun:"default_transfer_unit,type:varchar(8),nullzero"`
	Keywords                      string    `bun:"keywords,type:text(2147483647),nullzero"`
	FulltextTimestamp             string    `bun:"fulltext_timestamp,type:timestamp,nullzero"`
	VendorConsigned               string    `bun:"vendor_consigned,type:char,default:('N')"`
	CreatedBy                     string    `bun:"created_by,type:varchar(255),default:(suser_sname())"`
	Disposition                   string    `bun:"disposition,type:char,default:('N')"`
	SourceTypeCd                  int32     `bun:"source_type_cd,type:int,nullzero"`
	UseTagsFlag                   string    `bun:"use_tags_flag,type:char,default:('N')"`
	BaseUnit                      string    `bun:"base_unit,type:varchar(8)"`
	TagHoldClassUid               int32     `bun:"tag_hold_class_uid,type:int,nullzero"`
	ShippableUnitFlag             string    `bun:"shippable_unit_flag,type:char,default:('N')"`
	AutoAllocationFlag            string    `bun:"auto_allocation_flag,type:char,nullzero"`
	ParkerProductCd               string    `bun:"parker_product_cd,type:varchar(255),nullzero"`
	ParkerDivisionCd              string    `bun:"parker_division_cd,type:varchar(255),nullzero"`
	IvaTaxableFlag                string    `bun:"iva_taxable_flag,type:char,nullzero"`
	RestrictedFlag                string    `bun:"restricted_flag,type:char,nullzero"`
	SoldOutsideUsFlag             string    `bun:"sold_outside_us_flag,type:char,default:('N')"`
	CurrencyId                    float64   `bun:"currency_id,type:decimal(19,0),nullzero"`
	ServiceTermsDiscountPct       float64   `bun:"service_terms_discount_pct,type:decimal(19,2),default:((0))"`
	ServiceCommissionClassId      string    `bun:"service_commission_class_id,type:varchar(8),nullzero"`
	OverrideSpecificCosting       string    `bun:"override_specific_costing,type:char,default:('Y')"`
	ConfigurableFlag              string    `bun:"configurable_flag,type:char,default:('N')"`
	LastPricingServiceDate        time.Time `bun:"last_pricing_service_date,type:datetime,nullzero"`
	CommodityCode                 string    `bun:"commodity_code,type:varchar(255),nullzero"`
	DefaultPriceFamilyUid         int32     `bun:"default_price_family_uid,type:int,nullzero"`
	SpaItemFlag                   string    `bun:"spa_item_flag,type:char,default:('N')"`
	AvailForSchDeliveryFlag       string    `bun:"avail_for_sch_delivery_flag,type:char,nullzero"`
	ItemTypeCd                    int32     `bun:"item_type_cd,type:int,default:((300))"`
	CustParentInvMastUid          int32     `bun:"cust_parent_inv_mast_uid,type:int,nullzero"`
	UnspscCode                    string    `bun:"unspsc_code,type:varchar(255),nullzero"`
	DciCode                       string    `bun:"dci_code,type:varchar(255),nullzero"`
	EpaCertReqFlag                string    `bun:"epa_cert_req_flag,type:char,default:('N')"`
	AiaEnabledFlag                string    `bun:"aia_enabled_flag,type:char,nullzero"`
	AiaRemnantQty                 float64   `bun:"aia_remnant_qty,type:decimal(19,9),nullzero"`
	ManufacturerProgramTypeUid    int32     `bun:"manufacturer_program_type_uid,type:int,nullzero"`
	ManufacturerProgramTypePct    float64   `bun:"manufacturer_program_type_pct,type:decimal(19,2),nullzero"`
	Length                        float64   `bun:"length,type:decimal(19,9),nullzero"`
	Width                         float64   `bun:"width,type:decimal(19,9),nullzero"`
	Height                        float64   `bun:"height,type:decimal(19,9),nullzero"`
	UseOcTaxRulesFlag             string    `bun:"use_oc_tax_rules_flag,type:char,default:('N')"`
	TallyFlag                     string    `bun:"tally_flag,type:char,nullzero"`
	OcPrintOnPickTicketFlag       string    `bun:"oc_print_on_pick_ticket_flag,type:char,nullzero"`
	OcPrintOnInvoiceFlag          string    `bun:"oc_print_on_invoice_flag,type:char,nullzero"`
	UseRevisionsFlag              string    `bun:"use_revisions_flag,type:char,default:('N')"`
	SingleUseOrReusable           string    `bun:"single_use_or_reusable,type:char,nullzero"`
	UnitconvOverrideOeFlag        string    `bun:"unitconv_override_oe_flag,type:char,nullzero"`
	UnitconvOverridePurcFlag      string    `bun:"unitconv_override_purc_flag,type:char,nullzero"`
	ItemSalesTaxClass             string    `bun:"item_sales_tax_class,type:varchar(255),nullzero"`
	LifoPoolItemClass             string    `bun:"lifo_pool_item_class,type:varchar(8),nullzero"`
	CountryOfOriginReqFlag        string    `bun:"country_of_origin_req_flag,type:char,nullzero"`
	NmfcHdrUid                    int32     `bun:"nmfc_hdr_uid,type:int,nullzero"`
	CatchLotWeightFlag            string    `bun:"catch_lot_weight_flag,type:char,default:('N')"`
	Ucc128PackTypeCd              int32     `bun:"ucc128_pack_type_cd,type:int,nullzero"`
	Ucc128StandardPackSize        int32     `bun:"ucc128_standard_pack_size,type:int,nullzero"`
	RedemptionItemFlag            string    `bun:"redemption_item_flag,type:char,nullzero"`
	RedemptionValue               float64   `bun:"redemption_value,type:decimal(19,9),nullzero"`
	BoFillCanadianPurchaseFlag    string    `bun:"bo_fill_canadian_purchase_flag,type:char,default:('N')"`
	CountryOfOriginCode           string    `bun:"country_of_origin_code,type:char(2),nullzero"`
	ApplyStateFuelSurchargeFlag   string    `bun:"apply_state_fuel_surcharge_flag,type:char,default:('N')"`
	TypeOfSale                    string    `bun:"type_of_sale,type:varchar(255),nullzero"`
	CommissionCostMultiplier      float64   `bun:"commission_cost_multiplier,type:decimal(19,9),nullzero"`
	ItemLabelTypeCd               int32     `bun:"item_label_type_cd,type:int,nullzero"`
	DrumPickupFlag                string    `bun:"drum_pickup_flag,type:char,default:('N')"`
	ItemNotes                     string    `bun:"item_notes,type:varchar(255),nullzero"`
	RetailAccessories             string    `bun:"retail_accessories,type:varchar(255),nullzero"`
	HazmatOrmdFlag                string    `bun:"hazmat_ormd_flag,type:char,default:('N')"`
	HazmatOrmdQty                 int32     `bun:"hazmat_ormd_qty,type:int,nullzero"`
	FunctionalClass               string    `bun:"functional_class,type:varchar(10),nullzero"`
	SalesSetQuantity              int32     `bun:"sales_set_quantity,type:int,nullzero"`
	SuppressFromWebFlag           string    `bun:"suppress_from_web_flag,type:char,default:('N')"`
	VndrStock                     int32     `bun:"vndr_stock,type:int,nullzero"`
	PtlxStock                     int32     `bun:"ptlx_stock,type:int,nullzero"`
	PfStock                       int32     `bun:"pf_stock,type:int,nullzero"`
	RoundPrices                   string    `bun:"round_prices,type:char,default:('N')"`
	PumpoffItem                   string    `bun:"pumpoff_item,type:varchar(40),nullzero"`
	PumpoffUom                    string    `bun:"pumpoff_uom,type:varchar(8),nullzero"`
	ConocoDivisionClassId         string    `bun:"conoco_division_class_id,type:varchar(8),nullzero"`
	BuyGetClass                   string    `bun:"buy_get_class,type:varchar(8),nullzero"`
	DiscontinuedDate              time.Time `bun:"discontinued_date,type:datetime,nullzero"`
	LabelGroupItemFlag            string    `bun:"label_group_item_flag,type:char,nullzero"`
	CylinderItemFlag              string    `bun:"cylinder_item_flag,type:char,nullzero"`
	CoreItemFlag                  string    `bun:"core_item_flag,type:char,nullzero"`
	GenericItemDesc               string    `bun:"generic_item_desc,type:varchar(40),nullzero"`
	AllowCustomDescFlag           string    `bun:"allow_custom_desc_flag,type:char,default:('N')"`
	ManufacturerName              string    `bun:"manufacturer_name,type:varchar(255),nullzero"`
	BrandName                     string    `bun:"brand_name,type:varchar(255),nullzero"`
	PartNumber                    string    `bun:"part_number,type:varchar(255),nullzero"`
	DoNotAutoAllocateDesc         string    `bun:"do_not_auto_allocate_desc,type:varchar(255),nullzero"`
	ExcludeOrderLevelDiscountFlag string    `bun:"exclude_order_level_discount_flag,type:char,nullzero"`
	SampleItemFlag                string    `bun:"sample_item_flag,type:char,default:('N')"`
	SampleInvMastUid              int32     `bun:"sample_inv_mast_uid,type:int,nullzero"`
	CoreParentItemId              string    `bun:"core_parent_item_id,type:varchar(40),nullzero"`
	AttributeGroupUid             int32     `bun:"attribute_group_uid,type:int,nullzero"`
	PartnerProgramLaborItemFlag   string    `bun:"partner_program_labor_item_flag,type:char,nullzero"`
	BrandType                     int32     `bun:"brand_type,type:int,nullzero"`
	IqsItemFlag                   string    `bun:"iqs_item_flag,type:char,nullzero"`
	ImportAsDirectShipFlag        string    `bun:"import_as_direct_ship_flag,type:char,default:('N')"`
	DoNotFieldDestroyFlag         string    `bun:"do_not_field_destroy_flag,type:char,nullzero"`
	InvMastUidDupUsage            int32     `bun:"inv_mast_uid_dup_usage,type:int,nullzero"`
	RolledItemFlag                string    `bun:"rolled_item_flag,type:char,nullzero"`
	ExcludeFromEdi832Flag         string    `bun:"exclude_from_edi832_flag,type:char,nullzero"`
	OrderHoldClassId              string    `bun:"order_hold_class_id,type:varchar(255),nullzero"`
	DefaultDirectShipDispFlag     string    `bun:"default_direct_ship_disp_flag,type:char,default:('N')"`
	BuyerId                       string    `bun:"buyer_id,type:varchar(16),nullzero"`
	TariffSurchargePct            float64   `bun:"tariff_surcharge_pct,type:decimal(19,9),nullzero"`
	TariffSurchargeInvMastUid     int32     `bun:"tariff_surcharge_inv_mast_uid,type:int,nullzero"`
	PackingWeightTrackingOption   string    `bun:"packing_weight_tracking_option,type:char,nullzero"`
	ExcludeFromAutoShortBuyFlag   string    `bun:"exclude_from_auto_short_buy_flag,type:char,nullzero"`
	ItemClassificationId          string    `bun:"item_classification_id,type:varchar(255),nullzero"`
	HazmatFeeInvMastUid           int32     `bun:"hazmat_fee_inv_mast_uid,type:int,nullzero"`
	BolClass                      string    `bun:"bol_class,type:varchar(8),nullzero"`
	RentalItemFlag                string    `bun:"rental_item_flag,type:char,default:('N')"`
	RentalItemUid                 int32     `bun:"rental_item_uid,type:int,nullzero"`
	DfltDimensionScale            string    `bun:"dflt_dimension_scale,type:varchar(2),nullzero"`
	EccEnabledFlag                string    `bun:"ecc_enabled_flag,type:char,default:('N')"`
	LocalItemFlag                 string    `bun:"local_item_flag,type:char,default:('N')"`
}
