package model

type InvoiceHdr struct {
	bun.BaseModel              `bun:"table:invoice_hdr"`
	InvoiceNo                  string    `bun:"invoice_no,type:varchar(10),pk"`
	OrderNo                    string    `bun:"order_no,type:varchar(8),nullzero"`
	OrderDate                  time.Time `bun:"order_date,type:datetime,nullzero"`
	InvoiceDate                time.Time `bun:"invoice_date,type:datetime"`
	CustomerId                 string    `bun:"customer_id,type:varchar(12)"`
	Bill2Name                  string    `bun:"bill2_name,type:varchar(50),nullzero"`
	Bill2Contact               string    `bun:"bill2_contact,type:varchar(30),nullzero"`
	Bill2Address1              string    `bun:"bill2_address1,type:varchar(50),nullzero"`
	Bill2Address2              string    `bun:"bill2_address2,type:varchar(50),nullzero"`
	Bill2City                  string    `bun:"bill2_city,type:varchar(50),nullzero"`
	Bill2State                 string    `bun:"bill2_state,type:varchar(50),nullzero"`
	Bill2PostalCode            string    `bun:"bill2_postal_code,type:varchar(10),nullzero"`
	Ship2Name                  string    `bun:"ship2_name,type:varchar(50),nullzero"`
	Ship2Contact               string    `bun:"ship2_contact,type:varchar(30),nullzero"`
	Ship2Address1              string    `bun:"ship2_address1,type:varchar(50),nullzero"`
	Ship2Address2              string    `bun:"ship2_address2,type:varchar(50),nullzero"`
	Ship2City                  string    `bun:"ship2_city,type:varchar(50),nullzero"`
	Ship2State                 string    `bun:"ship2_state,type:varchar(50),nullzero"`
	Ship2PostalCode            string    `bun:"ship2_postal_code,type:varchar(10),nullzero"`
	CarrierName                string    `bun:"carrier_name,type:varchar(50),nullzero"`
	Fob                        string    `bun:"fob,type:varchar(20),nullzero"`
	TermsDesc                  string    `bun:"terms_desc,type:varchar(20),nullzero"`
	PoNo                       string    `bun:"po_no,type:varchar(255),nullzero"`
	SalesrepId                 string    `bun:"salesrep_id,type:varchar(16),nullzero"`
	SalesrepName               string    `bun:"salesrep_name,type:varchar(40),nullzero"`
	Brokerage                  float64   `bun:"brokerage,type:decimal(19,4),nullzero"`
	Freight                    float64   `bun:"freight,type:decimal(19,4),nullzero"`
	ArAccountNo                string    `bun:"ar_account_no,type:varchar(32),nullzero"`
	GlFreightAccountNo         string    `bun:"gl_freight_account_no,type:varchar(32),nullzero"`
	GlBrokerageAccountNo       string    `bun:"gl_brokerage_account_no,type:varchar(32),nullzero"`
	BrokerageAmt               float64   `bun:"brokerage_amt,type:decimal(19,4),nullzero"`
	Period                     float64   `bun:"period,type:decimal(3,0),nullzero"`
	YearForPeriod              float64   `bun:"year_for_period,type:decimal(4,0),nullzero"`
	StoreNo                    string    `bun:"store_no,type:varchar(5),nullzero"`
	InvoiceType                string    `bun:"invoice_type,type:varchar(2),nullzero"`
	ShipToId                   float64   `bun:"ship_to_id,type:decimal(19,0),nullzero"`
	ShipDate                   time.Time `bun:"ship_date,type:datetime,nullzero"`
	TotalAmount                float64   `bun:"total_amount,type:decimal(19,4),default:(0)"`
	AmountPaid                 float64   `bun:"amount_paid,type:decimal(19,4),default:(0)"`
	TermsTaken                 float64   `bun:"terms_taken,type:decimal(19,4),default:(0)"`
	Allowed                    float64   `bun:"allowed,type:decimal(19,4),default:(0)"`
	PaidInFullFlag             string    `bun:"paid_in_full_flag,type:char,default:('N')"`
	PaidByCheckNo              float64   `bun:"paid_by_check_no,type:decimal(19,4),nullzero"`
	DatePaid                   time.Time `bun:"date_paid,type:datetime,nullzero"`
	PrintFlag                  string    `bun:"print_flag,type:char,nullzero"`
	PrintDate                  time.Time `bun:"print_date,type:datetime,nullzero"`
	CompanyNo                  string    `bun:"company_no,type:varchar(8)"`
	CustomerIdNumber           float64   `bun:"customer_id_number,type:decimal(19,0)"`
	DateCreated                time.Time `bun:"date_created,type:datetime"`
	DateLastModified           time.Time `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy           string    `bun:"last_maintained_by,type:varchar(30),default:(user_name())"`
	Printed                    string    `bun:"printed,type:char,nullzero"`
	PrintedDate                time.Time `bun:"printed_date,type:datetime,nullzero"`
	CorpAddressId              float64   `bun:"corp_address_id,type:decimal(19,0),nullzero"`
	ShippingCost               float64   `bun:"shipping_cost,type:decimal(19,4),nullzero"`
	Bill2Country               string    `bun:"bill2_country,type:varchar(50),nullzero"`
	Ship2Country               string    `bun:"ship2_country,type:varchar(50),nullzero"`
	InvoiceReferenceNo         string    `bun:"invoice_reference_no,type:varchar(10)"`
	InvoiceAdjustmentType      string    `bun:"invoice_adjustment_type,type:char,nullzero"`
	InvoiceDesc                string    `bun:"invoice_desc,type:varchar(255),nullzero"`
	MemoAmount                 float64   `bun:"memo_amount,type:decimal(19,4),default:(0)"`
	BadDebtAmount              float64   `bun:"bad_debt_amount,type:decimal(19,4),default:(0)"`
	InvoiceClass               string    `bun:"invoice_class,type:varchar(8),nullzero"`
	PeriodFullyPaid            float64   `bun:"period_fully_paid,type:decimal(3,0),nullzero"`
	YearFullyPaid              float64   `bun:"year_fully_paid,type:decimal(4,0),nullzero"`
	Approved                   string    `bun:"approved,type:char,nullzero"`
	FcThruDate                 time.Time `bun:"fc_thru_date,type:datetime,nullzero"`
	CumulativeFc               float64   `bun:"cumulative_fc,type:decimal(19,4),nullzero"`
	NetDueDate                 time.Time `bun:"net_due_date,type:datetime,nullzero"`
	TermsDueDate               time.Time `bun:"terms_due_date,type:datetime,nullzero"`
	TermsId                    string    `bun:"terms_id,type:varchar(2),nullzero"`
	BranchId                   string    `bun:"branch_id,type:varchar(8)"`
	DisputedFlag               string    `bun:"disputed_flag,type:char,nullzero"`
	StatementPeriod            float64   `bun:"statement_period,type:decimal(3,0),nullzero"`
	StatementYear              float64   `bun:"statement_year,type:decimal(4,0),nullzero"`
	OtherChargeAmount          float64   `bun:"other_charge_amount,type:decimal(19,4),default:(0)"`
	TaxAmount                  float64   `bun:"tax_amount,type:decimal(19,4),default:(0)"`
	OriginalDocumentType       string    `bun:"original_document_type,type:char"`
	Consolidated               string    `bun:"consolidated,type:char"`
	SoldToAhUid                int32     `bun:"sold_to_ah_uid,type:int"`
	SoldToCustomerId           float64   `bun:"sold_to_customer_id,type:decimal(19,0)"`
	ShipToPhone                string    `bun:"ship_to_phone,type:varchar(20),nullzero"`
	InvoiceBatchUid            int32     `bun:"invoice_batch_uid,type:int,default:(1)"`
	FreightCodeUid             int32     `bun:"freight_code_uid,type:int,nullzero"`
	ShippingRouteUid           int32     `bun:"shipping_route_uid,type:int,nullzero"`
	TransmissionMethod         int32     `bun:"transmission_method,type:int,nullzero"`
	TermsAmount                float64   `bun:"terms_amount,type:decimal(19,4),default:(0)"`
	SalesLocationId            float64   `bun:"sales_location_id,type:decimal(19,0),nullzero"`
	SourceTypeCd               int32     `bun:"source_type_cd,type:int,nullzero"`
	Ship2EmailAddress          string    `bun:"ship2_email_address,type:varchar(255),nullzero"`
	CurrencyLineUid            int32     `bun:"currency_line_uid,type:int,nullzero"`
	CreatedBy                  string    `bun:"created_by,type:varchar(255),default:(suser_sname())"`
	TaxTermsTaken              float64   `bun:"tax_terms_taken,type:decimal(19,9),default:((0.00))"`
	CarrierInsuranceAmt        float64   `bun:"carrier_insurance_amt,type:decimal(19,9),nullzero"`
	InvNoDisplay               string    `bun:"inv_no_display,type:varchar(255),nullzero"`
	IvaExemptionNumber         string    `bun:"iva_exemption_number,type:varchar(30),nullzero"`
	IvaTaxableFlag             string    `bun:"iva_taxable_flag,type:char,nullzero"`
	JobId                      string    `bun:"job_id,type:varchar(32),nullzero"`
	InvoicePaidPeriod          int32     `bun:"invoice_paid_period,type:int,nullzero"`
	InvoicePeriod              int32     `bun:"invoice_period,type:int,nullzero"`
	CreditMemoForTermsFlag     string    `bun:"credit_memo_for_terms_flag,type:char,nullzero"`
	RecordTypeCd               int32     `bun:"record_type_cd,type:int,nullzero"`
	CommissionCost             float64   `bun:"commission_cost,type:decimal(19,9),default:((0))"`
	ReceiverName               string    `bun:"receiver_name,type:varchar(255),nullzero"`
	CartonCount                int32     `bun:"carton_count,type:int,default:(NULL)"`
	StrategicFreightIn         float64   `bun:"strategic_freight_in,type:decimal(19,9),nullzero"`
	StrategicFreightOut        float64   `bun:"strategic_freight_out,type:decimal(19,9),nullzero"`
	AffiliatedTrainingCenter   float64   `bun:"affiliated_training_center,type:decimal(19,0),nullzero"`
	ExternalReferenceNo        string    `bun:"external_reference_no,type:varchar(255),nullzero"`
	TotalFreightchargeWeight   float64   `bun:"total_freightcharge_weight,type:decimal(19,4),nullzero"`
	CardlockConsInvoiceFlag    string    `bun:"cardlock_cons_invoice_flag,type:char,nullzero"`
	RemoveFromOpenDefRevWindow string    `bun:"remove_from_open_def_rev_window,type:char,nullzero"`
	RecordTypeReferenceNo      string    `bun:"record_type_reference_no,type:varchar(10),nullzero"`
	RebillInvoiceReasonUid     int32     `bun:"rebill_invoice_reason_uid,type:int,nullzero"`
	EdiOrderPrintedFlag        string    `bun:"edi_order_printed_flag,type:char,nullzero"`
	DownpaymentApplied         float64   `bun:"downpayment_applied,type:decimal(19,2),nullzero"`
	ReverseRedemptionFlag      string    `bun:"reverse_redemption_flag,type:char,default:('N')"`
	SentToCarrierDate          time.Time `bun:"sent_to_carrier_date,type:datetime,nullzero"`
	TaxTermsAmt                float64   `bun:"tax_terms_amt,type:decimal(19,9),default:((0))"`
	TaxAmountPaid              float64   `bun:"tax_amount_paid,type:decimal(19,9),default:((0))"`
	ReasonCreditMemoCodeUid    int32     `bun:"reason_credit_memo_code_uid,type:int,nullzero"`
	SourceCreditMemoCodeUid    int32     `bun:"source_credit_memo_code_uid,type:int,nullzero"`
	ExternalClaimId            string    `bun:"external_claim_id,type:varchar(255),nullzero"`
	Bill2Address3              string    `bun:"bill2_address3,type:varchar(50),nullzero"`
	Ship2Address3              string    `bun:"ship2_address3,type:varchar(50),nullzero"`
	EftExportedDate            time.Time `bun:"eft_exported_date,type:datetime,nullzero"`
	CourtesyInvoiceFlag        string    `bun:"courtesy_invoice_flag,type:char,default:('N')"`
	IvaWithheldAmount          float64   `bun:"iva_withheld_amount,type:decimal(19,2),default:((0))"`
	CarrierId                  float64   `bun:"carrier_id,type:decimal(19,0),nullzero"`
	FreeOutFreightMinMetFlag   string    `bun:"free_out_freight_min_met_flag,type:char,default:('N')"`
	RegNumOfPackages           string    `bun:"reg_num_of_packages,type:varchar(255),nullzero"`
	Ship2Latitude              string    `bun:"ship2_latitude,type:varchar(20),nullzero"`
	Ship2Longitude             string    `bun:"ship2_longitude,type:varchar(20),nullzero"`
	DeliveryNo                 int32     `bun:"delivery_no,type:int,nullzero"`
	AllowedAmtReasonId         string    `bun:"allowed_amt_reason_id,type:varchar(255),nullzero"`
	TotalServiceAmountRedeemed float64   `bun:"total_service_amount_redeemed,type:decimal(19,9),nullzero"`
	CustomerClaimNo            string    `bun:"customer_claim_no,type:varchar(255),nullzero"`
	ClaimType                  string    `bun:"claim_type,type:varchar(255),nullzero"`
	ClaimCoopFlag              string    `bun:"claim_coop_flag,type:char,nullzero"`
	BillToSupplierFlag         string    `bun:"bill_to_supplier_flag,type:char,nullzero"`
	CustPriceProtVarAcctNo     string    `bun:"cust_price_prot_var_acct_no,type:varchar(32),nullzero"`
	ConsolidatedTypeFlag       string    `bun:"consolidated_type_flag,type:char,nullzero"`
	MerchandiseInvoiceFlag     string    `bun:"merchandise_invoice_flag,type:char,nullzero"`
	SalesMarketGroupUid        int32     `bun:"sales_market_group_uid,type:int,nullzero"`
	ActualFreightCost          float64   `bun:"actual_freight_cost,type:decimal(19,9),nullzero"`
	EcoFeeAmt                  float64   `bun:"eco_fee_amt,type:decimal(19,9),nullzero"`
	FrghtDiscTaken             float64   `bun:"frght_disc_taken,type:decimal(19,4),default:((0.00))"`
	RentalInvoiceNo            string    `bun:"rental_invoice_no,type:varchar(10),nullzero"`
}
