package model

type Location struct {
	bun.BaseModel                  `bun:"table:location"`
	CompanyId                      string    `bun:"company_id,type:varchar(8)"`
	LocationId                     float64   `bun:"location_id,type:decimal(19,0),pk"`
	DefaultBranchId                string    `bun:"default_branch_id,type:varchar(8),nullzero"`
	DeleteFlag                     string    `bun:"delete_flag,type:char"`
	DateCreated                    time.Time `bun:"date_created,type:datetime"`
	DateLastModified               time.Time `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy               string    `bun:"last_maintained_by,type:varchar(30),default:(user_name())"`
	ShippingGroupId                string    `bun:"shipping_group_id,type:varchar(8),nullzero"`
	TaxGroupId                     string    `bun:"tax_group_id,type:varchar(10),nullzero"`
	LocationName                   string    `bun:"location_name,type:varchar(255),nullzero"`
	LotBinIntegration              string    `bun:"lot_bin_integration,type:char,nullzero"`
	LocationType                   int32     `bun:"location_type,type:int"`
	NoOfPeriodsToSupply            int16     `bun:"no_of_periods_to_supply,type:tinyint,nullzero"`
	AvailableToTransferCalcCd      int32     `bun:"available_to_transfer_calc_cd,type:int,nullzero"`
	UseTagsFlag                    string    `bun:"use_tags_flag,type:char,default:('N')"`
	TagPrefix                      string    `bun:"tag_prefix,type:varchar(255),nullzero"`
	RfEnabledFlag                  string    `bun:"rf_enabled_flag,type:char,default:('N')"`
	FedexLocAcctNo                 string    `bun:"fedex_loc_acct_no,type:varchar(255),nullzero"`
	FedexMeterNo                   string    `bun:"fedex_meter_no,type:varchar(255),nullzero"`
	DeaCode                        string    `bun:"dea_code,type:char,nullzero"`
	DeaNumber                      string    `bun:"dea_number,type:varchar(255),nullzero"`
	WwmsShowBinAllocWarning        string    `bun:"wwms_show_bin_alloc_warning,type:char,default:('Y')"`
	ParkerDistributorNo            string    `bun:"parker_distributor_no,type:varchar(255),nullzero"`
	RfFrontcounterpickingFlag      string    `bun:"rf_frontcounterpicking_flag,type:char,nullzero"`
	DefaultOeSourceLocId           float64   `bun:"default_oe_source_loc_id,type:decimal(19,0),nullzero"`
	RegionUid                      int32     `bun:"region_uid,type:int,nullzero"`
	ConsignedShipToId              float64   `bun:"consigned_ship_to_id,type:decimal(19,0),nullzero"`
	PoReceiptsBinUid               int32     `bun:"po_receipts_bin_uid,type:int,nullzero"`
	TransferReceiptsBinUid         int32     `bun:"transfer_receipts_bin_uid,type:int,nullzero"`
	AutoconfirmProdPickTicket      string    `bun:"autoconfirm_prod_pick_ticket,type:char"`
	PrintProdPickTicket            string    `bun:"print_prod_pick_ticket,type:char,default:('N')"`
	UpsAccountNo                   string    `bun:"ups_account_no,type:varchar(255),nullzero"`
	UpsPickupTypeCd                int32     `bun:"ups_pickup_type_cd,type:int,nullzero"`
	UpsCustomerTypeCd              int32     `bun:"ups_customer_type_cd,type:int,nullzero"`
	GeneralManagerSalesrepId       string    `bun:"general_manager_salesrep_id,type:varchar(16),nullzero"`
	InvGroupHdrUid                 int32     `bun:"inv_group_hdr_uid,type:int,nullzero"`
	DefaultFaxCoverUid             int32     `bun:"default_fax_cover_uid,type:int,nullzero"`
	AssociatedLocationId           float64   `bun:"associated_location_id,type:decimal(19,0),nullzero"`
	UpsOltAccessKey                string    `bun:"ups_olt_access_key,type:varchar(255),nullzero"`
	UpsOltPassword                 string    `bun:"ups_olt_password,type:varchar(255),nullzero"`
	UpsOltUserId                   string    `bun:"ups_olt_user_id,type:varchar(255),nullzero"`
	AiaPromptFlag                  string    `bun:"aia_prompt_flag,type:char,nullzero"`
	CardlockAcctNo                 string    `bun:"cardlock_acct_no,type:varchar(255),nullzero"`
	PedigreeContactId              string    `bun:"pedigree_contact_id,type:varchar(16),nullzero"`
	StrategicRetailLocationFlag    string    `bun:"strategic_retail_location_flag,type:char,default:('N')"`
	WwmsDefaultPrimaryBinPo        string    `bun:"wwms_default_primary_bin_po,type:char,default:('N')"`
	WwmsDefaultPrimaryBinTrans     string    `bun:"wwms_default_primary_bin_trans,type:char,default:('N')"`
	ManufacturerRebateLoc          string    `bun:"manufacturer_rebate_loc,type:varchar(255),nullzero"`
	TrackCustomerPackageFlag       string    `bun:"track_customer_package_flag,type:char,default:('N')"`
	WeightPerBox                   float64   `bun:"weight_per_box,type:decimal(19,9),default:((0))"`
	RoadnetDoNotRouteFlag          string    `bun:"roadnet_do_not_route_flag,type:char,nullzero"`
	DistributionCenter             string    `bun:"distribution_center,type:char,default:('N')"`
	NonstockAvailableToTransfer    int32     `bun:"nonstock_available_to_transfer,type:int,nullzero"`
	NonstockNoPeriodsToSupply      int32     `bun:"nonstock_no_periods_to_supply,type:int,nullzero"`
	ServerTimeZoneOffset           int32     `bun:"server_time_zone_offset,type:int,nullzero"`
	SalesTaxPayableGlAccount       string    `bun:"sales_tax_payable_gl_account,type:varchar(32),nullzero"`
	ExternalTaxBackupPercent       float64   `bun:"external_tax_backup_percent,type:decimal(19,9),nullzero"`
	RegionFlag                     string    `bun:"region_flag,type:char,nullzero"`
	UseBinsForTransScheduleFlag    string    `bun:"use_bins_for_trans_schedule_flag,type:char,default:('N')"`
	UsePalletsFlag                 string    `bun:"use_pallets_flag,type:char,default:('N')"`
	UsePalletTypesFlag             string    `bun:"use_pallet_types_flag,type:char,default:('N')"`
	VoucherClass                   string    `bun:"voucher_class,type:varchar(8),nullzero"`
	AllowMultipleAssembliesFlag    string    `bun:"allow_multiple_assemblies_flag,type:char,nullzero"`
	UndershipmentAllocationFlag    string    `bun:"undershipment_allocation_flag,type:char,default:('N')"`
	RatelinxLocationId             int32     `bun:"ratelinx_location_id,type:int,nullzero"`
	CenteronDefaultTaker           string    `bun:"centeron_default_taker,type:varchar(30),nullzero"`
	StartPickSeqTagBulk            int32     `bun:"start_pick_seq_tag_bulk,type:int,nullzero"`
	HighVelocityLevel              float64   `bun:"high_velocity_level,type:decimal(19,9),nullzero"`
	MidVelocityLevel               float64   `bun:"mid_velocity_level,type:decimal(19,9),nullzero"`
	TaxBySourceLocFlag             string    `bun:"tax_by_source_loc_flag,type:char,nullzero"`
	ShippingLocationFlag           string    `bun:"shipping_location_flag,type:char,nullzero"`
	GstRegistrationNo              string    `bun:"gst_registration_no,type:varchar(20),nullzero"`
	WwmsDefaultDepositBin          string    `bun:"wwms_default_deposit_bin,type:varchar(10),nullzero"`
	QuotebuilderDefaultTaker       string    `bun:"quotebuilder_default_taker,type:varchar(30),nullzero"`
	ExcludeOtfItemsFlag            string    `bun:"exclude_otf_items_flag,type:char,default:('N')"`
	ExtTaxCompanyCode              string    `bun:"ext_tax_company_code,type:varchar(255),nullzero"`
	FcaBinUid                      int32     `bun:"fca_bin_uid,type:int,nullzero"`
	FcaReasonId                    string    `bun:"fca_reason_id,type:varchar(5),nullzero"`
	PreventAutoAssignLotsFlag      string    `bun:"prevent_auto_assign_lots_flag,type:char,default:('N')"`
	FedexLabelSizeCd               int32     `bun:"fedex_label_size_cd,type:int,nullzero"`
	FedexLabelOrientationCd        int32     `bun:"fedex_label_orientation_cd,type:int,nullzero"`
	FedexLabelFormatCd             int32     `bun:"fedex_label_format_cd,type:int,nullzero"`
	PreventAutoTsCreationFlag      string    `bun:"prevent_auto_ts_creation_flag,type:char,default:('N')"`
	TrReceiptsUsePrimaryBinCd      int32     `bun:"tr_receipts_use_primary_bin_cd,type:int,default:((3406))"`
	DamagedBinUid                  int32     `bun:"damaged_bin_uid,type:int,nullzero"`
	NostockBinUid                  int32     `bun:"nostock_bin_uid,type:int,nullzero"`
	ConsignmentCustomerId          float64   `bun:"consignment_customer_id,type:decimal(19,0),nullzero"`
	RollupLocationId               float64   `bun:"rollup_location_id,type:decimal(19,0),nullzero"`
	PrintPackinglistInWwms         string    `bun:"print_packinglist_in_wwms,type:char,nullzero"`
	PrintTransferPackinglistInWwms string    `bun:"print_transfer_packinglist_in_wwms,type:char,nullzero"`
	PickProblemBinUid              int32     `bun:"pick_problem_bin_uid,type:int,nullzero"`
	RfTransferPackListPrinter      string    `bun:"rf_transfer_pack_list_printer,type:varchar(255),nullzero"`
	PrintUcc128WithPtFlag          string    `bun:"print_ucc128_with_pt_flag,type:char,default:('N')"`
	AutoAllocateInPoImportFlag     string    `bun:"auto_allocate_in_po_import_flag,type:char,nullzero"`
	DefaultFieldDestroyBinUid      int32     `bun:"default_field_destroy_bin_uid,type:int,nullzero"`
	DefaultFieldDestroyReasonId    string    `bun:"default_field_destroy_reason_id,type:varchar(255),nullzero"`
	WarrantyReturnInvMastUid       int32     `bun:"warranty_return_inv_mast_uid,type:int,nullzero"`
	WarrantyReturnBinUid           int32     `bun:"warranty_return_bin_uid,type:int,nullzero"`
	UseDqRoutingFlag               string    `bun:"use_dq_routing_flag,type:char,nullzero"`
	UseCatchWeightProcessingFlag   string    `bun:"use_catch_weight_processing_flag,type:char,nullzero"`
	RmaReceiptsUsePrimaryBin       string    `bun:"rma_receipts_use_primary_bin,type:char,nullzero"`
	FedexDefaultPhoneNumber        string    `bun:"fedex_default_phone_number,type:varchar(20),nullzero"`
	SkipParkerExportInOe           string    `bun:"skip_parker_export_in_oe,type:char,default:('N')"`
	AdjustFoundItemsFlag           string    `bun:"adjust_found_items_flag,type:char,default:('N')"`
	RmaDefaultWarrantyBinUid       int32     `bun:"rma_default_warranty_bin_uid,type:int,nullzero"`
	DamagedFlag                    string    `bun:"damaged_flag,type:char,nullzero"`
	CardlockNexusLocation          string    `bun:"cardlock_nexus_location,type:char,nullzero"`
	FedexSmartpostHubCd            int32     `bun:"fedex_smartpost_hub_cd,type:int,nullzero"`
	DatagateSupplierNo             int32     `bun:"datagate_supplier_no,type:int,nullzero"`
	DatagateInvSeqNo               int32     `bun:"datagate_inv_seq_no,type:int,nullzero"`
	DatagateSalesSeqNo             int32     `bun:"datagate_sales_seq_no,type:int,nullzero"`
	PriorityLocationId             float64   `bun:"priority_location_id,type:decimal(19,0),nullzero"`
	ExtTaxFreightBkupTaxExempt     string    `bun:"ext_tax_freight_bkup_tax_exempt,type:char,default:('N')"`
	SporadicItemThresholdPeriods   int32     `bun:"sporadic_item_threshold_periods,type:int,nullzero"`
	RfnavigatorUrl                 `bun:"rfnavigator_url,type:nvarchar(500),nullzero"`
	RfnavigatorUserName            string `bun:"rfnavigator_user_name,type:varchar(255),nullzero"`
	RfnavigatorPassword            string `bun:"rfnavigator_password,type:varchar(255),nullzero"`
	UpdateVelocitySettings         string `bun:"update_velocity_settings,type:varchar,default:('N')"`
	TrackaboutLocationTid          int32  `bun:"trackabout_location_tid,type:int,nullzero"`
	RfnavigatorDropLocation        string `bun:"rfnavigator_drop_location,type:varchar(8),nullzero"`
	RfnavigatorStartUnitNo         int32  `bun:"rfnavigator_start_unit_no,type:int,nullzero"`
}
