package model

import (
	"github.com/uptrace/bun"
	"time"
)

type OeLine struct {
	bun.BaseModel               `bun:"table:oe_line"`
	OrderNo                     string    `bun:"order_no,type:varchar(8),pk"`
	UnitPrice                   float64   `bun:"unit_price,type:decimal(19,9),nullzero"`
	QtyOrdered                  float64   `bun:"qty_ordered,type:decimal(19,9),nullzero"`
	QtyPerAssembly              float64   `bun:"qty_per_assembly,type:decimal(19,9)"`
	CompanyNo                   string    `bun:"company_no,type:varchar(8)"`
	DeleteFlag                  string    `bun:"delete_flag,type:char"`
	ManualPriceOveride          string    `bun:"manual_price_overide,type:char,nullzero"`
	DateCreated                 time.Time `bun:"date_created,type:datetime"`
	DateLastModified            time.Time `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy            string    `bun:"last_maintained_by,type:varchar(30)"`
	ExtendedPrice               float64   `bun:"extended_price,type:decimal(19,4),nullzero"`
	SalesTax                    float64   `bun:"sales_tax,type:decimal(19,4),nullzero"`
	LineNo                      float64   `bun:"line_no,type:decimal(19,0),pk"`
	Complete                    string    `bun:"complete,type:char,nullzero"`
	UnitOfMeasure               string    `bun:"unit_of_measure,type:varchar(8),nullzero"`
	BaseUtPrice                 float64   `bun:"base_ut_price,type:decimal(19,9),nullzero"`
	CalcType                    string    `bun:"calc_type,type:varchar(10),nullzero"`
	CalcValue                   float64   `bun:"calc_value,type:decimal(19,4),nullzero"`
	Combinable                  string    `bun:"combinable,type:char,nullzero"`
	Disposition                 string    `bun:"disposition,type:char,nullzero"`
	QtyAllocated                float64   `bun:"qty_allocated,type:decimal(19,9),nullzero"`
	QtyOnPickTickets            float64   `bun:"qty_on_pick_tickets,type:decimal(19,9),nullzero"`
	QtyInvoiced                 float64   `bun:"qty_invoiced,type:decimal(19,9),nullzero"`
	ExpediteDate                time.Time `bun:"expedite_date,type:datetime,nullzero"`
	RequiredDate                time.Time `bun:"required_date,type:datetime,nullzero"`
	SourceLocId                 float64   `bun:"source_loc_id,type:decimal(19,0),nullzero"`
	ShipLocId                   float64   `bun:"ship_loc_id,type:decimal(19,0),nullzero"`
	SupplierId                  float64   `bun:"supplier_id,type:decimal(19,0),nullzero"`
	ProductGroupId              string    `bun:"product_group_id,type:varchar(8),nullzero"`
	Assembly                    string    `bun:"assembly,type:char,nullzero"`
	Scheduled                   string    `bun:"scheduled,type:char,nullzero"`
	LotBill                     string    `bun:"lot_bill,type:char"`
	ExtendedDesc                string    `bun:"extended_desc,type:varchar(255),nullzero"`
	UnitSize                    float64   `bun:"unit_size,type:decimal(19,4)"`
	UnitQuantity                float64   `bun:"unit_quantity,type:decimal(19,9)"`
	NextBreak                   float64   `bun:"next_break,type:decimal(19,9),nullzero"`
	NextUtPrice                 float64   `bun:"next_ut_price,type:decimal(19,9),nullzero"`
	CustomerPartNumber          string    `bun:"customer_part_number,type:varchar(40)"`
	TaxItem                     string    `bun:"tax_item,type:char,nullzero"`
	OkToInterchange             string    `bun:"ok_to_interchange,type:char,nullzero"`
	OtherCharge                 string    `bun:"other_charge,type:char"`
	SalesCost                   float64   `bun:"sales_cost,type:decimal(19,9),nullzero"`
	CommissionCost              float64   `bun:"commission_cost,type:decimal(19,9),nullzero"`
	RequestedDownpayment        float64   `bun:"requested_downpayment,type:decimal(19,9),nullzero"`
	DownpaymentDate             time.Time `bun:"downpayment_date,type:datetime,nullzero"`
	WillCall                    string    `bun:"will_call,type:char,nullzero"`
	OtherCost                   float64   `bun:"other_cost,type:decimal(19,9),nullzero"`
	DownpaymentRemaining        float64   `bun:"downpayment_remaining,type:decimal(19,9),nullzero"`
	CancelFlag                  string    `bun:"cancel_flag,type:char,nullzero"`
	CommissionCostEdited        string    `bun:"commission_cost_edited,type:char,nullzero"`
	OtherCostEdited             string    `bun:"other_cost_edited,type:char,nullzero"`
	PoCost                      float64   `bun:"po_cost,type:decimal(19,9),nullzero"`
	QtyCanceled                 float64   `bun:"qty_canceled,type:decimal(19,9),nullzero"`
	PricingUnit                 string    `bun:"pricing_unit,type:varchar(8),nullzero"`
	PricingUnitSize             float64   `bun:"pricing_unit_size,type:decimal(19,4),nullzero"`
	QtyStaged                   float64   `bun:"qty_staged,type:decimal(19,9),nullzero"`
	ItemSource                  int16     `bun:"item_source,type:smallint"`
	OeHdrUid                    int32     `bun:"oe_hdr_uid,type:int"`
	ParentOeLineUid             int32     `bun:"parent_oe_line_uid,type:int"`
	OeLineUid                   int32     `bun:"oe_line_uid,type:int"`
	PricePageUid                int32     `bun:"price_page_uid,type:int,nullzero"`
	PricingOption               int32     `bun:"pricing_option,type:int"`
	DetailType                  int32     `bun:"detail_type,type:int"`
	UserLineNo                  string    `bun:"user_line_no,type:varchar(25),nullzero"`
	ItemTermsDiscountPct        float64   `bun:"item_terms_discount_pct,type:decimal(19,2),default:(0)"`
	DefaultInOe                 string    `bun:"default_in_oe,type:char,default:('N')"`
	InvMastUid                  int32     `bun:"inv_mast_uid,type:int"`
	FreightIn                   float64   `bun:"freight_in,type:decimal(19,4),default:(0)"`
	PeerOeLineUid               int32     `bun:"peer_oe_line_uid,type:int,default:(0)"`
	PeerType                    int32     `bun:"peer_type,type:int,default:(0)"`
	SubstituteItem              string    `bun:"substitute_item,type:char,default:('N')"`
	AllocateUsageToOriginalItem string    `bun:"allocate_usage_to_original_item,type:char,default:('N')"`
	OrderCostEdited             string    `bun:"order_cost_edited,type:char,default:('N')"`
	CaptureUsage                string    `bun:"capture_usage,type:char"`
	PurchaseClassId             string    `bun:"purchase_class_id,type:varchar(8),nullzero"`
	PickDate                    time.Time `bun:"pick_date,type:datetime,nullzero"`
	ShippingRouteUid            int32     `bun:"shipping_route_uid,type:int,nullzero"`
	InvXrefUid                  int32     `bun:"inv_xref_uid,type:int,nullzero"`
	HoseQtyNeeded               float64   `bun:"hose_qty_needed,type:decimal(19,9),default:(0)"`
	CreatedBy                   string    `bun:"created_by,type:varchar(255),default:(suser_sname())"`
	OriginalQtyOrdered          float64   `bun:"original_qty_ordered,type:decimal(19,9),nullzero"`
	TagHoldClassUid             int32     `bun:"tag_hold_class_uid,type:int,nullzero"`
	CostCenter                  string    `bun:"cost_center,type:varchar(255),nullzero"`
	DispositionEditedFlag       string    `bun:"disposition_edited_flag,type:char,nullzero"`
	JobPriceHdrUid              int32     `bun:"job_price_hdr_uid,type:int,nullzero"`
	DeaRestrictionFailed        string    `bun:"dea_restriction_failed,type:char,nullzero"`
	RestockFeePercentage        float64   `bun:"restock_fee_percentage,type:decimal(19,9),nullzero"`
	CustomerConfiguredPrice     float64   `bun:"customer_configured_price,type:decimal(19,9),nullzero"`
	CustomerPickedFlag          string    `bun:"customer_picked_flag,type:char,nullzero"`
	JobPriceLineUid             int32     `bun:"job_price_line_uid,type:int,nullzero"`
	CustPoNo                    string    `bun:"cust_po_no,type:varchar(255),nullzero"`
	JobPriceBinUid              int32     `bun:"job_price_bin_uid,type:int,nullzero"`
	UseContractCost             string    `bun:"use_contract_cost,type:char,default:('Y')"`
	CostPricePageUid            int32     `bun:"cost_price_page_uid,type:int,nullzero"`
	PackageTypeUid              int32     `bun:"package_type_uid,type:int,nullzero"`
	TagPackageQtyPer            float64   `bun:"tag_package_qty_per,type:decimal(19,0),nullzero"`
	FreightCodeUid              int32     `bun:"freight_code_uid,type:int,nullzero"`
	AcknowledgementDate         time.Time `bun:"acknowledgement_date,type:datetime,nullzero"`
	UsedSpecificCostFlag        string    `bun:"used_specific_cost_flag,type:char,default:('N')"`
	OperationUid                int32     `bun:"operation_uid,type:int,nullzero"`
	ServiceLaborUid             int32     `bun:"service_labor_uid,type:int,nullzero"`
	QuoteOutcomeCd              int32     `bun:"quote_outcome_cd,type:int,nullzero"`
	ItemCommissionClassId       string    `bun:"item_commission_class_id,type:varchar(8),nullzero"`
	FromAltPrevRequestsFlag     string    `bun:"from_alt_prev_requests_flag,type:char,nullzero"`
	UdCost                      float64   `bun:"ud_cost,type:decimal(19,9),nullzero"`
	TankName                    string    `bun:"tank_name,type:varchar(255),nullzero"`
	ItemBillToId                float64   `bun:"item_bill_to_id,type:decimal(19,0),nullzero"`
	BuybackNo                   string    `bun:"buyback_no,type:varchar(255),nullzero"`
	RoutingStatusFlag           string    `bun:"routing_status_flag,type:char,nullzero"`
	SplitFlag                   string    `bun:"split_flag,type:char,nullzero"`
	AdditionalDescription       string    `bun:"additional_description,type:varchar(255),nullzero"`
	BillHoldFlag                string    `bun:"bill_hold_flag,type:char,nullzero"`
	CorePrice                   float64   `bun:"core_price,type:decimal(19,9),nullzero"`
	Clock                       string    `bun:"clock,type:varchar(255),nullzero"`
	Cell                        string    `bun:"cell,type:varchar(255),nullzero"`
	EnvironmentalFee            float64   `bun:"environmental_fee,type:decimal(19,4),nullzero"`
	AdminFee                    float64   `bun:"admin_fee,type:decimal(19,4),nullzero"`
	ExtDiscAmt                  float64   `bun:"ext_disc_amt,type:decimal(19,9),nullzero"`
	SystemCalcUnitPrice         float64   `bun:"system_calc_unit_price,type:decimal(19,9),nullzero"`
	Buyer                       string    `bun:"buyer,type:varchar(255),nullzero"`
	Recipient                   string    `bun:"recipient,type:varchar(255),nullzero"`
	StrategicUnitPrice          float64   `bun:"strategic_unit_price,type:decimal(19,9),nullzero"`
	StrategicPricePageUid       int32     `bun:"strategic_price_page_uid,type:int,nullzero"`
	VerifiedFlag                string    `bun:"verified_flag,type:char,nullzero"`
	VerifiedCode                string    `bun:"verified_code,type:varchar(255),nullzero"`
	CoreStatusCd                int32     `bun:"core_status_cd,type:int,nullzero"`
	UsedStrategicPricingFlag    string    `bun:"used_strategic_pricing_flag,type:char,nullzero"`
	LoanUid                     int32     `bun:"loan_uid,type:int,nullzero"`
	LoanItemUid                 int32     `bun:"loan_item_uid,type:int,nullzero"`
	OriginalUnitPrice           float64   `bun:"original_unit_price,type:decimal(19,9),default:((0))"`
	OriginalFreightIn           float64   `bun:"original_freight_in,type:decimal(19,9),nullzero"`
	StrategicListCostValue      float64   `bun:"strategic_list_cost_value,type:decimal(19,9),nullzero"`
	StrategicListCostCd         int32     `bun:"strategic_list_cost_cd,type:int,nullzero"`
	SalesMarketGroupUid         int32     `bun:"sales_market_group_uid,type:int,nullzero"`
	SpecialItemIndicator        int32     `bun:"special_item_indicator,type:int,nullzero"`
	AwardedDate                 time.Time `bun:"awarded_date,type:datetime,nullzero"`
	SampleFlag                  string    `bun:"sample_flag,type:char,nullzero"`
	RoutingAllocationChange     float64   `bun:"routing_allocation_change,type:decimal(19,9),nullzero"`
	Price1                      float64   `bun:"price1,type:decimal(19,9),nullzero"`
	UnitPickFee                 float64   `bun:"unit_pick_fee,type:decimal(19,9),nullzero"`
	OeLineAltCode               string    `bun:"oe_line_alt_code,type:varchar(40),nullzero"`
	RetailPrice                 float64   `bun:"retail_price,type:decimal(19,9),nullzero"`
	QuotePriceOeLineUid         int32     `bun:"quote_price_oe_line_uid,type:int,nullzero"`
	CoreItemCost                float64   `bun:"core_item_cost,type:decimal(19,9),nullzero"`
	ItemCommitmentDetailUid     int32     `bun:"item_commitment_detail_uid,type:int,nullzero"`
	SuppressCustomCost          string    `bun:"suppress_custom_cost,type:char,nullzero"`
	BuyListApprovalInitial      string    `bun:"buy_list_approval_initial,type:varchar(3),nullzero"`
	GeocomForcedSendFlag        string    `bun:"geocom_forced_send_flag,type:char,default:('N')"`
	GeocomForcedQuantity        float64   `bun:"geocom_forced_quantity,type:decimal(19,0),nullzero"`
	SuppressPickTicketIndicator int32     `bun:"suppress_pick_ticket_indicator,type:int,nullzero"`
	BeltingWidth                float64   `bun:"belting_width,type:decimal(19,9),nullzero"`
	BeltingLength               float64   `bun:"belting_length,type:decimal(19,9),nullzero"`
	BeltingNumCuts              int32     `bun:"belting_num_cuts,type:int,nullzero"`
	CarrierId                   float64   `bun:"carrier_id,type:decimal(19,0),nullzero"`
	FreightInEditedFlag         string    `bun:"freight_in_edited_flag,type:char,nullzero"`
	SalesDiscountGroupId        string    `bun:"sales_discount_group_id,type:varchar(8),nullzero"`
	PriceFamilyUid              int32     `bun:"price_family_uid,type:int,nullzero"`
	CostCarrierContractLineUid  int32     `bun:"cost_carrier_contract_line_uid,type:int,nullzero"`
	PriceCarrierContractLineUid int32     `bun:"price_carrier_contract_line_uid,type:int,nullzero"`
	PumpOffFlag                 string    `bun:"pump_off_flag,type:char,default:('N')"`
	CostCarrierContractZLineUid int32     `bun:"cost_carrier_contract_z_line_uid,type:int,nullzero"`
	TargetPrice                 float64   `bun:"target_price,type:decimal(19,9),nullzero"`
	Edi830LastShipmentNo        string    `bun:"edi830_last_shipment_no,type:varchar(255),nullzero"`
	Edi830LastReceiveQty        float64   `bun:"edi830_last_receive_qty,type:decimal(19,9),nullzero"`
	Edi830LastReceiveDate       time.Time `bun:"edi830_last_receive_date,type:datetime,nullzero"`
	FaspacYtdQtyInvoiced        float64   `bun:"faspac_ytd_qty_invoiced,type:decimal(19,9),nullzero"`
	CompetitorUid               int32     `bun:"competitor_uid,type:int,nullzero"`
	PriceAdjNote                string    `bun:"price_adj_note,type:varchar(255),nullzero"`
	ImportedPrice               float64   `bun:"imported_price,type:decimal(19,9),nullzero"`
	GlCode                      string    `bun:"gl_code,type:varchar(255),nullzero"`
	RfqIndicatorFlag            string    `bun:"rfq_indicator_flag,type:char,default:('Y')"`
	BuyGetRewardsFlag           string    `bun:"buy_get_rewards_flag,type:char,default:('N')"`
	BuyGetXRewardsProgramUid    int32     `bun:"buy_get_x_rewards_program_uid,type:int,nullzero"`
	CarrierRebateCost           float64   `bun:"carrier_rebate_cost,type:decimal(19,9),nullzero"`
	ExtendedDescLocation        string    `bun:"extended_desc_location,type:varchar(255),nullzero"`
	ExtendedDescCustomer        string    `bun:"extended_desc_customer,type:varchar(255),nullzero"`
	LineDiscount                float64   `bun:"line_discount,type:decimal(19,9),nullzero"`
	LineDiscountDescription     string    `bun:"line_discount_description,type:varchar(255),nullzero"`
	UnitDistributorNet          float64   `bun:"unit_distributor_net,type:decimal(19,9),nullzero"`
	ExtendedDistributorNet      float64   `bun:"extended_distributor_net,type:decimal(19,4),nullzero"`
	EcoFeeAmount                float64   `bun:"eco_fee_amount,type:decimal(19,9),nullzero"`
	BypassProdOrderProcessing   string    `bun:"bypass_prod_order_processing,type:char,nullzero"`
	GenericCustomDescription    string    `bun:"generic_custom_description,type:varchar(255),nullzero"`
	LineSeqNo                   int32     `bun:"line_seq_no,type:int,nullzero"`
	OeBuyGetRewardsUid          int32     `bun:"oe_buy_get_rewards_uid,type:int,nullzero"`
	RestrictedByAddressFlag     string    `bun:"restricted_by_address_flag,type:char,default:('N')"`
	SecondaryUnitPrice          float64   `bun:"secondary_unit_price,type:decimal(19,9),nullzero"`
	SecondaryExtendedPrice      float64   `bun:"secondary_extended_price,type:decimal(19,9),nullzero"`
	OriginalDisposition         string    `bun:"original_disposition,type:char,nullzero"`
	SecondaryManualPriceOveride string    `bun:"secondary_manual_price_overide,type:char,default:('N')"`
	ExtendedItemFlag            string    `bun:"extended_item_flag,type:char,nullzero"`
	PrintDescOnFormsFlag        string    `bun:"print_desc_on_forms_flag,type:char,nullzero"`
	PrintPartNo                 string    `bun:"print_part_no,type:varchar(40),nullzero"`
	CourtesyCoreReturnFlag      string    `bun:"courtesy_core_return_flag,type:char,nullzero"`
	CurrentbinUid               int32     `bun:"currentbin_uid,type:int,nullzero"`
	QaStatus                    string    `bun:"qa_status,type:varchar(255),nullzero"`
	ServiceItemFlag             string    `bun:"service_item_flag,type:char,nullzero"`
	PrediscountUnitPrice        float64   `bun:"prediscount_unit_price,type:decimal(19,9),nullzero"`
	CustPercentageDisc          float64   `bun:"cust_percentage_disc,type:decimal(19,9),nullzero"`
	OriginalQtyAllocated        float64   `bun:"original_qty_allocated,type:decimal(19,9),default:((0))"`
	PriceLockFlag               string    `bun:"price_lock_flag,type:char,nullzero"`
	ExtElectronicDiscAmt        float64   `bun:"ext_electronic_disc_amt,type:decimal(19,9),nullzero"`
	ServiceItemId               string    `bun:"service_item_id,type:varchar(255),nullzero"`
	PoContractNumber            string    `bun:"po_contract_number,type:varchar(255),nullzero"`
	ExcludeFromEdi844867Flag    string    `bun:"exclude_from_edi_844_867_flag,type:char,nullzero"`
	AddToOpenPtFlag             string    `bun:"add_to_open_pt_flag,type:char,default:('N')"`
	SplitToOeLineUid            int32     `bun:"split_to_oe_line_uid,type:int,nullzero"`
	SplitFromOeLineUid          int32     `bun:"split_from_oe_line_uid,type:int,nullzero"`
	FullRolledItemCd            int32     `bun:"full_rolled_item_cd,type:int,nullzero"`
	RequiredTransferShipDate    time.Time `bun:"required_transfer_ship_date,type:datetime,nullzero"`
	ReasonId                    string    `bun:"reason_id,type:varchar(5),nullzero"`
	DamagedItemSerialNumber     string    `bun:"damaged_item_serial_number,type:varchar(40),nullzero"`
	ExportParkerPrinterName     string    `bun:"export_parker_printer_name,type:varchar(255),nullzero"`
	ExportParkerLabelCopies     int32     `bun:"export_parker_label_copies,type:int,nullzero"`
	CreateTrackaboutLeaseFlag   string    `bun:"create_trackabout_lease_flag,type:char,default:('N')"`
	JobPriceShipControlNoUid    int32     `bun:"job_price_ship_control_no_uid,type:int,nullzero"`
	PricingMultiplierFromLot    float64   `bun:"pricing_multiplier_from_lot,type:decimal(19,9),nullzero"`
	RentalFlag                  string    `bun:"rental_flag,type:char,default:('N')"`
	RentalReturnQty             float64   `bun:"rental_return_qty,type:decimal(19,9),nullzero"`
	RentalPrice                 float64   `bun:"rental_price,type:decimal(19,9),nullzero"`
	QuoteConversionListPrice    float64   `bun:"quote_conversion_list_price,type:decimal(19,9),nullzero"`
	QuotedPrice                 float64   `bun:"quoted_price,type:decimal(19,9),nullzero"`
	ConversionOrderCost         float64   `bun:"conversion_order_cost,type:decimal(19,9),nullzero"`
	DirectShipFreightAmount     float64   `bun:"direct_ship_freight_amount,type:decimal(19,4),nullzero"`
	ReturnCylinderQuantity      int32     `bun:"return_cylinder_quantity,type:int,nullzero"`
	LinkedChargeParentOeLineUid int32     `bun:"linked_charge_parent_oe_line_uid,type:int,nullzero"`
	LinkedChargeScaleQtyFlag    string    `bun:"linked_charge_scale_qty_flag,type:char,nullzero"`
	SourceQuoteOeLineUid        int32     `bun:"source_quote_oe_line_uid,type:int,nullzero"`
	RestrictedClassUid          int32     `bun:"restricted_class_uid,type:int,nullzero"`
}
