package model

type ShipTo struct {
	bun.BaseModel                 `bun:"table:ship_to"`
	CompanyId                     string    `bun:"company_id,type:varchar(8),pk"`
	ShipToId                      float64   `bun:"ship_to_id,type:decimal(19,0),pk"`
	CustomerId                    float64   `bun:"customer_id,type:decimal(19,0)"`
	DefaultBranch                 string    `bun:"default_branch,type:varchar(8)"`
	FederalExemptionNumber        string    `bun:"federal_exemption_number,type:varchar(40),nullzero"`
	StateExemptionNumber          string    `bun:"state_exemption_number,type:varchar(40),nullzero"`
	OtherExemptionNumber          string    `bun:"other_exemption_number,type:varchar(40),nullzero"`
	PriceFileId                   float64   `bun:"price_file_id,type:decimal(19,0),nullzero"`
	PreferredLocationId           float64   `bun:"preferred_location_id,type:decimal(19,0),nullzero"`
	DefaultShipTime               time.Time `bun:"default_ship_time,type:datetime,nullzero"`
	DefaultCarrierId              float64   `bun:"default_carrier_id,type:decimal(19,0),nullzero"`
	Fob                           string    `bun:"fob,type:varchar(20),nullzero"`
	DeliveryInstructions          string    `bun:"delivery_instructions,type:varchar(255),nullzero"`
	MorningBegDelivery            time.Time `bun:"morning_beg_delivery,type:datetime,nullzero"`
	MorningEndDelivery            time.Time `bun:"morning_end_delivery,type:datetime,nullzero"`
	EveningBegDelivery            time.Time `bun:"evening_beg_delivery,type:datetime,nullzero"`
	EveningEndDelivery            time.Time `bun:"evening_end_delivery,type:datetime,nullzero"`
	AcceptPartialOrders           string    `bun:"accept_partial_orders,type:char"`
	AcceptableWaitTime            float64   `bun:"acceptable_wait_time,type:decimal(3,0),nullzero"`
	Class1Id                      string    `bun:"class1_id,type:varchar(255),nullzero"`
	Class2Id                      string    `bun:"class2_id,type:varchar(255),nullzero"`
	Class3Id                      string    `bun:"class3_id,type:varchar(255),nullzero"`
	Class4Id                      string    `bun:"class4_id,type:varchar(255),nullzero"`
	Class5Id                      string    `bun:"class5_id,type:varchar(255),nullzero"`
	PackingBasis                  string    `bun:"packing_basis,type:varchar(16),nullzero"`
	DateCreated                   time.Time `bun:"date_created,type:datetime,default:(getdate())"`
	DateLastModified              time.Time `bun:"date_last_modified,type:datetime,default:(getdate())"`
	LastMaintainedBy              string    `bun:"last_maintained_by,type:varchar(30),default:(user_name(null))"`
	DeleteFlag                    string    `bun:"delete_flag,type:char,default:('N')"`
	TermsId                       string    `bun:"terms_id,type:varchar(2),nullzero"`
	InvoiceType                   string    `bun:"invoice_type,type:varchar(2),nullzero"`
	BilledOnGrossNetQty           string    `bun:"billed_on_gross_net_qty,type:char,nullzero"`
	StateExciseTaxExemptionNo     string    `bun:"state_excise_tax_exemption_no,type:varchar(40),nullzero"`
	PickTicketType                string    `bun:"pick_ticket_type,type:varchar(2),nullzero"`
	TaxGroupId                    string    `bun:"tax_group_id,type:varchar(10),nullzero"`
	HandlingChargeReqFlag         string    `bun:"handling_charge_req_flag,type:char,default:('N')"`
	ThirdPartyBillingFlag         string    `bun:"third_party_billing_flag,type:char,default:('S')"`
	DaysEarly                     int32     `bun:"days_early,type:int,default:(0)"`
	DaysLate                      int32     `bun:"days_late,type:int,default:(0)"`
	TransitDays                   int32     `bun:"transit_days,type:int,default:(1)"`
	FreightCodeUid                int32     `bun:"freight_code_uid,type:int,nullzero"`
	SignatureRequired             string    `bun:"signature_required,type:char,default:('N')"`
	ShippingRouteUid              int32     `bun:"shipping_route_uid,type:int,nullzero"`
	PdaOrderEntry                 string    `bun:"pda_order_entry,type:char,default:('N')"`
	PdaOelistCriteriaUid          int32     `bun:"pda_oelist_criteria_uid,type:int,nullzero"`
	ExcludeHoldFromPickTix        string    `bun:"exclude_hold_from_pick_tix,type:varchar,default:('N')"`
	ExcludeCanceldFromPackList    string    `bun:"exclude_canceld_from_pack_list,type:varchar,default:('N')"`
	ExcludeHoldFromPackList       string    `bun:"exclude_hold_from_pack_list,type:varchar,default:('N')"`
	ExcludeCanceldFromOrderAck    string    `bun:"exclude_canceld_from_order_ack,type:varchar,default:('N')"`
	ExcludeHoldFromOrderAck       string    `bun:"exclude_hold_from_order_ack,type:varchar,default:('N')"`
	IncludeNonAllocOnPickTix      int32     `bun:"include_non_alloc_on_pick_tix,type:int,default:(1277)"`
	ExcludeCanceldFromPickTix     string    `bun:"exclude_canceld_from_pick_tix,type:char,default:('N')"`
	CreatedBy                     string    `bun:"created_by,type:varchar(255),default:(suser_sname())"`
	IncludeNonAllocOnPackList     int32     `bun:"include_non_alloc_on_pack_list,type:int"`
	PrintPackinglistInShipping    string    `bun:"print_packinglist_in_shipping,type:char,default:('N')"`
	PrintPricesOnPackinglist      string    `bun:"print_prices_on_packinglist,type:char,default:('Y')"`
	SourceTypeCd                  int32     `bun:"source_type_cd,type:int,nullzero"`
	DataIdentifierGroupUid        int32     `bun:"data_identifier_group_uid,type:int,nullzero"`
	FedexFreightMarkup            float64   `bun:"fedex_freight_markup,type:decimal(19,9),nullzero"`
	CreditStatus                  string    `bun:"credit_status,type:varchar(8),nullzero"`
	CreditLimit                   float64   `bun:"credit_limit,type:decimal(19,2),nullzero"`
	CreditLimitUsed               float64   `bun:"credit_limit_used,type:decimal(19,2),nullzero"`
	DefaultCustomerPoNo           string    `bun:"default_customer_po_no,type:varchar(255),nullzero"`
	BudgetCodeApprovalFlag        string    `bun:"budget_code_approval_flag,type:char,nullzero"`
	ServiceTermsId                string    `bun:"service_terms_id,type:varchar(2),nullzero"`
	DefaultFreightMarkupPct       float64   `bun:"default_freight_markup_pct,type:decimal(19,4),default:((0))"`
	FreightChargeByMileHdrUid     int32     `bun:"freight_charge_by_mile_hdr_uid,type:int,nullzero"`
	FreightMileageAmt             float64   `bun:"freight_mileage_amt,type:decimal(19,2),nullzero"`
	DegreeDaysFlag                string    `bun:"degree_days_flag,type:char,nullzero"`
	CalendarDaysFlag              string    `bun:"calendar_days_flag,type:char,nullzero"`
	HeatAndHotWaterCd             int32     `bun:"heat_and_hot_water_cd,type:int,nullzero"`
	DrumDepositExemptFlag         string    `bun:"drum_deposit_exempt_flag,type:char,default:('N')"`
	TaxableFlag                   string    `bun:"taxable_flag,type:char,nullzero"`
	BillHoldFlag                  string    `bun:"bill_hold_flag,type:char,nullzero"`
	DisplayPoNoFlag               string    `bun:"display_po_no_flag,type:char,nullzero"`
	PoNoRequiredFlag              string    `bun:"po_no_required_flag,type:char,nullzero"`
	DisplayBadgeFlag              string    `bun:"display_badge_flag,type:char,nullzero"`
	BadgeRequiredFlag             string    `bun:"badge_required_flag,type:char,nullzero"`
	DelSchSourceLocation          float64   `bun:"del_sch_source_location,type:decimal(19,0),nullzero"`
	ServiceSourceLocation         float64   `bun:"service_source_location,type:decimal(19,0),nullzero"`
	DistributorAccountId          string    `bun:"distributor_account_id,type:varchar(255),nullzero"`
	CardlockCalcPriceFlag         string    `bun:"cardlock_calc_price_flag,type:char,default:('N')"`
	CourtesyAddressId             float64   `bun:"courtesy_address_id,type:decimal(19,0),nullzero"`
	DfoaShipToId                  string    `bun:"dfoa_ship_to_id,type:varchar(255),nullzero"`
	ErouterTranType               string    `bun:"erouter_tran_type,type:char,nullzero"`
	CardlockDiscount              float64   `bun:"cardlock_discount,type:decimal(19,9),nullzero"`
	OrderPriorityUid              int32     `bun:"order_priority_uid,type:int,nullzero"`
	DeliveryZoneUid               int32     `bun:"delivery_zone_uid,type:int,nullzero"`
	PlantCode                     string    `bun:"plant_code,type:varchar(255),nullzero"`
	FreightChargeUid              int32     `bun:"freight_charge_uid,type:int,nullzero"`
	UpsRoadnetAcctTypeId          string    `bun:"ups_roadnet_acct_type_id,type:varchar(255),nullzero"`
	UpsRoadnetDeliveryDays        string    `bun:"ups_roadnet_delivery_days,type:varchar(255),nullzero"`
	UpsRoadnetZoneId              string    `bun:"ups_roadnet_zone_id,type:varchar(255),nullzero"`
	UseCustUpsHandlngChrgFlag     string    `bun:"use_cust_ups_handlng_chrg_flag,type:varchar,default:('Y')"`
	UpsHandlingCharge             float64   `bun:"ups_handling_charge,type:decimal(19,2),default:((0.00))"`
	SalesTaxPayableAccountNo      string    `bun:"sales_tax_payable_account_no,type:varchar(255),nullzero"`
	VertexTaxableFlag             string    `bun:"vertex_taxable_flag,type:char,nullzero"`
	CustomerTaxClass              string    `bun:"customer_tax_class,type:varchar(255),nullzero"`
	TaxExemptReasonUid            int32     `bun:"tax_exempt_reason_uid,type:int,nullzero"`
	ServiceCenterUid              int32     `bun:"service_center_uid,type:int,nullzero"`
	DunsNumber                    string    `bun:"duns_number,type:varchar(20),nullzero"`
	SmallTruckFlag                string    `bun:"small_truck_flag,type:char,nullzero"`
	DeliveryTimeOffset            int32     `bun:"delivery_time_offset,type:int,default:((0))"`
	TermsOfDeliveryCd             int32     `bun:"terms_of_delivery_cd,type:int,nullzero"`
	ModeOfTransportCd             int32     `bun:"mode_of_transport_cd,type:int,nullzero"`
	UpsRoadnetExcludeFlag         string    `bun:"ups_roadnet_exclude_flag,type:char,default:('N')"`
	DfoaSoldToId                  string    `bun:"dfoa_sold_to_id,type:varchar(255),nullzero"`
	InvoiceBatchUid               int32     `bun:"invoice_batch_uid,type:int,nullzero"`
	DateAcctOpened                time.Time `bun:"date_acct_opened,type:datetime,nullzero"`
	CourtesyContractShipToId      float64   `bun:"courtesy_contract_ship_to_id,type:decimal(19,0),nullzero"`
	UpsThirdPartyBillingNo        string    `bun:"ups_third_party_billing_no,type:varchar(255),nullzero"`
	ReqLotDocWithInvoiceFlag      string    `bun:"req_lot_doc_with_invoice_flag,type:char,nullzero"`
	ReqLotDocWithPackinglistFlag  string    `bun:"req_lot_doc_with_packinglist_flag,type:char,nullzero"`
	LimitOnlineWarrantiesFlag     string    `bun:"limit_online_warranties_flag,type:char,default:('N')"`
	RemoteMargin                  float64   `bun:"remote_margin,type:decimal(19,9),nullzero"`
	CfnResaleFlag                 string    `bun:"cfn_resale_flag,type:char,default:('N')"`
	SeparateInvoiceFlag           string    `bun:"separate_invoice_flag,type:char,default:('N')"`
	DoNotAutoInvoiceFlag          string    `bun:"do_not_auto_invoice_flag,type:char,default:('N')"`
	SicCode                       float64   `bun:"sic_code,type:decimal(6,0),nullzero"`
	ValvolineNumber               string    `bun:"valvoline_number,type:varchar(255),nullzero"`
	ConocoShipToId                string    `bun:"conoco_ship_to_id,type:varchar(255),nullzero"`
	ConocoSoldToId                string    `bun:"conoco_sold_to_id,type:varchar(255),nullzero"`
	SalesMarketGroupUid           int32     `bun:"sales_market_group_uid,type:int,nullzero"`
	OrderByBinPickTicketFlag      string    `bun:"order_by_bin_pick_ticket_flag,type:char,nullzero"`
	AltTaxRateEligibleFlag        string    `bun:"alt_tax_rate_eligible_flag,type:char,nullzero"`
	ResidentialAddressFlag        string    `bun:"residential_address_flag,type:char,nullzero"`
	ExcludePrintPackinglistInWwms string    `bun:"exclude_print_packinglist_in_wwms,type:char,nullzero"`
	RecordUsageActualLocFlag      string    `bun:"record_usage_actual_loc_flag,type:char,nullzero"`
	ShipToLinkingId               int32     `bun:"ship_to_linking_id,type:int,nullzero"`
	ServiceLevelAgreementUid      int32     `bun:"service_level_agreement_uid,type:int,nullzero"`
	ScanAndPackFlag               string    `bun:"scan_and_pack_flag,type:char,default:('N')"`
	LotAgeRestrictionMonths       int32     `bun:"lot_age_restriction_months,type:int,nullzero"`
	FreightForwardAddressId       float64   `bun:"freight_forward_address_id,type:decimal(19,0),nullzero"`
	AsbDeliveryMethodUid          int32     `bun:"asb_delivery_method_uid,type:int,nullzero"`
	StopNo                        int32     `bun:"stop_no,type:int,nullzero"`
	AdvancedBillingFlag           string    `bun:"advanced_billing_flag,type:char,nullzero"`
	TrackaboutBillByShipTo        string    `bun:"trackabout_bill_by_ship_to,type:char,default:('N')"`
	FreeFreightDays               int32     `bun:"free_freight_days,type:int,nullzero"`
	ProtectedFlag                 string    `bun:"protected_flag,type:char,default:('N')"`
}
