package model

import (
	"github.com/uptrace/bun"
	"time"
)

type Users struct {
	bun.BaseModel                     `bun:"table:users"`
	Id                                string    `bun:"id,type:varchar(30),pk"`
	Name                              string    `bun:"name,type:varchar(40)"`
	Password                          string    `bun:"password,type:varchar(40),nullzero"`
	DateCreated                       time.Time `bun:"date_created,type:datetime"`
	DateLastModified                  time.Time `bun:"date_last_modified,type:datetime"`
	LastMaintainedBy                  string    `bun:"last_maintained_by,type:varchar(30),default:(user_name())"`
	Active                            string    `bun:"active,type:char"`
	DeleteFlag                        string    `bun:"delete_flag,type:char"`
	LanguageId                        string    `bun:"language_id,type:varchar(8),default:(1)"`
	DefaultCompany                    string    `bun:"default_company,type:varchar(8),nullzero"`
	DefaultBranch                     string    `bun:"default_branch,type:varchar(8),nullzero"`
	DefaultQuoteOrder                 string    `bun:"default_quote_order,type:char,default:('N')"`
	CreateCustomers                   string    `bun:"create_customers,type:char,nullzero"`
	CreateShipTos                     string    `bun:"create_ship_tos,type:char,nullzero"`
	DefaultLocationId                 float64   `bun:"default_location_id,type:decimal(19,0),nullzero"`
	PromptBeforeClearing              string    `bun:"prompt_before_clearing,type:char,nullzero"`
	DefaultCustomerId                 float64   `bun:"default_customer_id,type:decimal(19,0),nullzero"`
	RemoteUser                        string    `bun:"remote_user,type:char"`
	CompanySecurity                   string    `bun:"company_security,type:char"`
	WindowSecurity                    string    `bun:"window_security,type:char"`
	SystemSecurity                    string    `bun:"system_security,type:char"`
	CreateItemsAtOe                   string    `bun:"create_items_at_oe,type:char,nullzero"`
	DefaultApplication                string    `bun:"default_application,type:varchar(40),nullzero"`
	ScriptPath                        string    `bun:"script_path,type:varchar(255),nullzero"`
	CreatePoFromOe                    int32     `bun:"create_po_from_oe,type:int"`
	RoleUid                           int32     `bun:"role_uid,type:int"`
	DesignerRights                    string    `bun:"designer_rights,type:varchar(8),default:('USER')"`
	ContactId                         string    `bun:"contact_id,type:varchar(16),nullzero"`
	PrintPreviewZoomPercentage        int16     `bun:"print_preview_zoom_percentage,type:smallint"`
	ClassId                           string    `bun:"class_id,type:varchar(8),nullzero"`
	AutoGenerateTransferInOe          string    `bun:"auto_generate_transfer_in_oe,type:char,default:('N')"`
	EmailAddress                      string    `bun:"email_address,type:varchar(255),nullzero"`
	ReceiveSystemAlerts               string    `bun:"receive_system_alerts,type:char,default:('N')"`
	SalesrepId                        string    `bun:"salesrep_id,type:varchar(16),nullzero"`
	ReceiveImportFailureAlert         string    `bun:"receive_import_failure_alert,type:char,default:('N')"`
	DefaultToAdvancedSearch           string    `bun:"default_to_advanced_search,type:char,default:('N')"`
	AdjQtyAvailableAtOe               int32     `bun:"adj_qty_available_at_oe,type:int,default:(1391)"`
	LinkStockItemToPo                 string    `bun:"link_stock_item_to_po,type:char,default:('N')"`
	HistoricalCostInSalesHist         string    `bun:"historical_cost_in_sales_hist,type:char,default:('N')"`
	OrderCostBasisOrderCost           string    `bun:"order_cost_basis_order_cost,type:char,default:('Y')"`
	OrderCostBasisCommCost            string    `bun:"order_cost_basis_comm_cost,type:char,default:('Y')"`
	OrderCostBasisOtherCost           string    `bun:"order_cost_basis_other_cost,type:char,default:('Y')"`
	DefaultCostingBasis               int32     `bun:"default_costing_basis,type:int,default:(1)"`
	TimeZoneCd                        int32     `bun:"time_zone_cd,type:int,nullzero"`
	CurrentCashdrawerCounter          int32     `bun:"current_cashdrawer_counter,type:int,default:(0)"`
	MaxCashdrawerCounter              int32     `bun:"max_cashdrawer_counter,type:int,default:(0)"`
	CurrentOeLineCounter              int32     `bun:"current_oe_line_counter,type:int,default:(0)"`
	MaxOeLineCounter                  int32     `bun:"max_oe_line_counter,type:int,default:(0)"`
	CurrentInvoiceLineCounter         int32     `bun:"current_invoice_line_counter,type:int,default:(0)"`
	MaxInvoiceLineCounter             int32     `bun:"max_invoice_line_counter,type:int,default:(0)"`
	TaskVisibilityCd                  int32     `bun:"task_visibility_cd,type:int,default:(1418)"`
	CreateVendorRfqCd                 int32     `bun:"create_vendor_rfq_cd,type:int,default:(986)"`
	UpdateCostFromRfqReceipt          string    `bun:"update_cost_from_rfq_receipt,type:char,default:('N')"`
	DisplayTransactionTasks           string    `bun:"display_transaction_tasks,type:char,default:('Y')"`
	AllowNonstockTbo                  string    `bun:"allow_nonstock_tbo,type:char,default:('N')"`
	CurrentInvTranCounter             int32     `bun:"current_inv_tran_counter,type:int,default:(0)"`
	MaxInvTranCounter                 int32     `bun:"max_inv_tran_counter,type:int,default:(0)"`
	CurrentGlCounter                  int32     `bun:"current_gl_counter,type:int,default:(0)"`
	MaxGlCounter                      int32     `bun:"max_gl_counter,type:int,default:(0)"`
	CreateContractFromOe              string    `bun:"create_contract_from_oe,type:char,default:('N')"`
	MgmtAllowBranchEdit               string    `bun:"mgmt_allow_branch_edit,type:char,default:('Y')"`
	MgmtUseDefaultBranch              string    `bun:"mgmt_use_default_branch,type:char,default:('N')"`
	OePriceLibraryOverrideFlag        string    `bun:"oe_price_library_override_flag,type:char,default:('N')"`
	DefaultLabelPrinter               string    `bun:"default_label_printer,type:varchar(255),nullzero"`
	UpdateProspectsOnlyFlag           string    `bun:"update_prospects_only_flag,type:char,default:('N')"`
	DefaultItemSearch                 int32     `bun:"default_item_search,type:int,default:(1935)"`
	SuppressManualAdjAllocFlag        string    `bun:"suppress_manual_adj_alloc_flag,type:char,default:('N')"`
	ShippingControlFlag               string    `bun:"shipping_control_flag,type:char,default:('N')"`
	CnvrtProspectToCustomerOe         string    `bun:"cnvrt_prospect_to_customer_oe,type:char,default:('N')"`
	AutoDisplayRooms                  string    `bun:"auto_display_rooms,type:char,default:('N')"`
	DisplayPurchasepriceBreaks        string    `bun:"display_purchaseprice_breaks,type:char,default:('N')"`
	DefaultSalesrepOnOrder            string    `bun:"default_salesrep_on_order,type:varchar(16),nullzero"`
	DefaultRepOnCommRptFlag           string    `bun:"default_rep_on_comm_rpt_flag,type:char,default:('N')"`
	OrderValidationPassword           string    `bun:"order_validation_password,type:varchar(255),nullzero"`
	BypassCheckVerifyPassword         string    `bun:"bypass_check_verify_password,type:varchar(255),nullzero"`
	MachineName                       string    `bun:"machine_name,type:varchar(255),nullzero"`
	SalesSupervisorFlag               string    `bun:"sales_supervisor_flag,type:char,default:('N')"`
	VacationEndDate                   time.Time `bun:"vacation_end_date,type:datetime,nullzero"`
	DoeSalesrepId                     string    `bun:"doe_salesrep_id,type:varchar(16),nullzero"`
	DoeUserFlag                       string    `bun:"doe_user_flag,type:char,default:('N')"`
	VacationEndDateModFlag            string    `bun:"vacation_end_date_mod_flag,type:char,default:('N')"`
	UsersUid                          int32     `bun:"users_uid,type:int,identity"`
	InvGroupHdrUid                    int32     `bun:"inv_group_hdr_uid,type:int,nullzero"`
	UsePoApprovalThresholdFlag        string    `bun:"use_po_approval_threshold_flag,type:char,default:('N')"`
	PoApprovalThreshold               float64   `bun:"po_approval_threshold,type:decimal(19,9),nullzero"`
	PrevRequestsSearch                string    `bun:"prev_requests_search,type:char,default:('N')"`
	ViewCostOnOeLine                  string    `bun:"view_cost_on_oe_line,type:varchar,default:('N')"`
	ActiveDirectoryRole               string    `bun:"active_directory_role,type:varchar(255),nullzero"`
	UpdateBranchOeReportsFlag         string    `bun:"update_branch_oe_reports_flag,type:char,nullzero"`
	OeAllowShipmentEdits              string    `bun:"oe_allow_shipment_edits,type:char,nullzero"`
	OeAllowPackingListReprint         string    `bun:"oe_allow_packing_list_reprint,type:char,nullzero"`
	SalesrepSecurityType              string    `bun:"salesrep_security_type,type:char,nullzero"`
	UserSalesrepId                    string    `bun:"user_salesrep_id,type:varchar(16),nullzero"`
	DefaultAsTakerFlag                string    `bun:"default_as_taker_flag,type:char,default:('N')"`
	SearchItemCatalogFlag             string    `bun:"search_item_catalog_flag,type:char,default:('N')"`
	ClearItemCatalogFlag              string    `bun:"clear_item_catalog_flag,type:char,default:('N')"`
	MakeItemsSellableInOeFlag         string    `bun:"make_items_sellable_in_oe_flag,type:char,default:('N')"`
	AddItemLocationsInOeFlag          string    `bun:"add_item_locations_in_oe_flag,type:char,default:('N')"`
	ConfirmDeaPtFlag                  string    `bun:"confirm_dea_pt_flag,type:char,nullzero"`
	StrategicPricingRoleUid           int32     `bun:"strategic_pricing_role_uid,type:int,nullzero"`
	CashDrawerId                      string    `bun:"cash_drawer_id,type:varchar(8),nullzero"`
	DfltWwmsFormsPrinter              string    `bun:"dflt_wwms_forms_printer,type:varchar(255),nullzero"`
	ShowComponentsInSalesHist         string    `bun:"show_components_in_sales_hist,type:char,default:('N')"`
	FieldChooserPermCd                int32     `bun:"field_chooser_perm_cd,type:int,default:((300))"`
	CustomerProfitRoleUid             int32     `bun:"customer_profit_role_uid,type:int,nullzero"`
	AllowPostToClosedGlPeriod         string    `bun:"allow_post_to_closed_gl_period,type:char,nullzero"`
	DefaultSendToOutlookFlag          string    `bun:"default_send_to_outlook_flag,type:char,default:('N')"`
	DisplayOpenQuoteLinesCd           int32     `bun:"display_open_quote_lines_cd,type:int,nullzero"`
	CreateItemsAtSoe                  string    `bun:"create_items_at_soe,type:char,nullzero"`
	RestrictedClassOverrideFlag       string    `bun:"restricted_class_override_flag,type:char,default:('N')"`
	AllowShipToEditInOeFlag           string    `bun:"allow_ship_to_edit_in_oe_flag,type:char,default:('N')"`
	ShowCcPaymentAcctOnSave           int32     `bun:"show_cc_payment_acct_on_save,type:int,nullzero"`
	ShowArCcFailed                    string    `bun:"show_ar_cc_failed,type:char,nullzero"`
	OverrideCustPalletWarnFlag        string    `bun:"override_cust_pallet_warn_flag,type:char,default:('N')"`
	LogoPathFilename                  string    `bun:"logo_path_filename,type:varchar(255),nullzero"`
	UserReportPath                    string    `bun:"user_report_path,type:varchar(255),nullzero"`
	AllowShipmentConfirmation         string    `bun:"allow_shipment_confirmation,type:char,default:('N')"`
	ViewVendorTypeCd                  int32     `bun:"view_vendor_type_cd,type:int,default:((2981))"`
	OverRedeemRewardsFlag             string    `bun:"over_redeem_rewards_flag,type:char,default:('N')"`
	ExtendedItemInfoPorgFlag          string    `bun:"extended_item_info_porg_flag,type:char,nullzero"`
	FedexLabelPrinterPath             string    `bun:"fedex_label_printer_path,type:varchar(255),nullzero"`
	DefaultItemSearchInImi            string    `bun:"default_item_search_in_imi,type:char,default:('N')"`
	PoThresholdCurrencyId             int32     `bun:"po_threshold_currency_id,type:int,nullzero"`
	AddCustomerPartNumberInOe         string    `bun:"add_customer_part_number_in_oe,type:varchar,default:('N')"`
	Override754Flag                   string    `bun:"override_754_flag,type:char,default:('N')"`
	AllowAddLaborToCompletedPo        string    `bun:"allow_add_labor_to_completed_po,type:char,default:('N')"`
	AllowPostprintEditLaborEst        string    `bun:"allow_postprint_edit_labor_est,type:char,default:('N')"`
	DoNotExportCarrierPoFlag          string    `bun:"do_not_export_carrier_po_flag,type:char,default:('N')"`
	NetworkName                       string    `bun:"network_name,type:varchar(30),nullzero"`
	OrderCostBasisRebateCost          string    `bun:"order_cost_basis_rebate_cost,type:char,default:('N')"`
	ConvertQuoteToOrderPromptFlag     string    `bun:"convert_quote_to_order_prompt_flag,type:char,default:('Y')"`
	DefaultPickTicketPrinter          string    `bun:"default_pick_ticket_printer,type:varchar(255),nullzero"`
	DefaultInvoicePrinter             string    `bun:"default_invoice_printer,type:varchar(255),nullzero"`
	UserSignaturePath                 string    `bun:"user_signature_path,type:varchar(255),nullzero"`
	DisableItemCategoryTreeByDescFlag string    `bun:"disable_item_category_tree_by_desc_flag,type:char,default:('N')"`
	ImiDefaultUserLocation            string    `bun:"imi_default_user_location,type:char,default:('N')"`
	DfltUcc128LabelPrinter            string    `bun:"dflt_ucc128_label_printer,type:varchar(255),nullzero"`
	AllowEdi855ManualOrdersFlag       string    `bun:"allow_edi_855_manual_orders_flag,type:char,nullzero"`
	EmailSignature                    string    `bun:"email_signature,type:varchar,nullzero"`
	OeChangeCustomerWithItems         string    `bun:"oe_change_customer_with_items,type:char,default:('N')"`
	AllowEditLaborTimeEntry           string    `bun:"allow_edit_labor_time_entry,type:char,default:('N')"`
	DefaultBssCustomerId              float64   `bun:"default_bss_customer_id,type:decimal(19,0),nullzero"`
	RebuildDrillSecurityFlag          string    `bun:"rebuild_drill_security_flag,type:char,default:('N')"`
	CheckCreationRole                 int32     `bun:"check_creation_role,type:int,nullzero"`
	ShowCcOnSaveCashReceipts          string    `bun:"show_cc_on_save_cash_receipts,type:char,default:('N')"`
	P21ClientLogPath                  string    `bun:"p21_client_log_path,type:varchar(255),nullzero"`
	EnterpriseSearchUrl               string    `bun:"enterprise_search_url,type:varchar(255),nullzero"`
	AllowReportCreationInStudio       int32     `bun:"allow_report_creation_in_studio,type:int,default:((1418))"`
}
