name: "Release"
on:
  push:
    tags:
      - '*'
jobs:
  buf:
    name: "Push BSR tag"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - name: "push release name to BSR"
        run:
          "buf push proto --tag ${{ github.ref_name }}"
        env:
          BUF_TOKEN: "${{ secrets.BUF_REGISTRY_TOKEN }}"
